### ISSUE TITLE
Underlined text in description

### ISSUE THREAD

**Issue by thany** [mapsme/omim#10367]
I've written this description:
```
Fee: ¥200/60min
```
The `200/60` is blue and underlined after saving. When I tap it, the phone app opens and wants to call `20060`.

First of all, I don't want phone number recognition if it doesn't work properly. No one uses a `/` in a phone number! Why would you recognize it as such?? Secondly, if you do think it looks like a phone number, try to validate it against local phone number rules. For example, a phone number must always start with a country code, or a zero.

Too many false positives is annoying, and you might as well disable it because calling a POI isn't that common, especially from a phone number in the description as opposed to the dedicated phone number field.

If you're unwilling to change this behaviour (as you have for at least a couple of years) please let us know what the recognition algorithm is. Probably a pretty simple regex by the looks of things.

**Comment by thany** [comment]
Guy, it's either one of these options:

1. You fix this issue and make us happy
2. You don't fix this is at all, and let us know by giving us the finger
3. You let us know what the current algorithm is, so we can write things in such a way that it averts false positives

You don't leave people in the dark by not responding at all. That's just not cool.

**Comment by rokuz** [comment]
Guy, there is the only option. You write polite and precisely what kind of description do you mean. We've several in the app.

**Comment by thany** [comment]
Polite didn't work. You keep ignoring issues that are compromising usability of the app, and keep jamming in features and other commerical crap that no one asked for. At least I don't see tickets of people wanting those things.

Please start fixing some of those issues, and then we can talk politeness, thank you very much.

**Comment by rokuz** [comment]
Since you don't clarify what kind of description you mean, issue is closed.

**Comment by thany** [comment]
Really? You couldn't figure out that the only kind of description that *can* be written and where that text makes sense, is of a bookmark? You didn't even bother to try it out yourself, did you?

**Comment by rokuz** [comment]
1. Description for a bookmark.
2. Description for a list of bookmarks.
3. One of fields in the POI editor.

**Comment by thany** [comment]
Are you saying pattern detection is different for each of those fields?

**Comment by rokuz** [comment]
You won't believe :) We don't use any pattern detection, at all. But it can be system behaviour, e.g. Android makes this by default. If we know the exact window in which you see this, probably, we can tune it.

**Comment by thany** [comment]
Well, like I said, bookmarks description.
Recently I've found out that it's possible to put HTML there (who knew, right... inputting html on a mobile keyboard, good luck with all the angle brackets 🤷‍♀️). This tells me all formatting detection should be turned off, because we can reason that HTML formatting then becomes responsible for making hyperlinks.

I'm seeing it when viewing a bookmark, not when editing one. I haven't checked any other multiline fields, but if nothing specials has been done to them, chances are my original post was correct in not specifying where, which means everywhere.
