### ISSUE TITLE
Build failed: "private.h" file not found

### ISSUE THREAD

**Issue by RahulGusain** [mapsme/omim#10440]

**Comment by Zverik** [comment]
Please read [CONTRIBUTING.md](https://github.com/mapsme/omim/blob/master/docs/CONTRIBUTING.md) thouroughly. Especially the big about running `configure.sh`.

**Comment by RahulGusain** [comment]
Sorry but i don't able to understand how can I run configure.sh from root. please can you tell the command.

**Comment by RahulGusain** [comment]
Ok , I got it. Thanks for your advise.
