### ISSUE TITLE
System error while creating route

### ISSUE THREAD

**Issue by alexx7676** [mapsme/omim#10656]
"System error" dialog appears while creating a route on self made map.
![photo_2019-04-09_14-34-55](https://user-images.githubusercontent.com/44890785/55796071-8743ff80-5ae2-11e9-8561-c2ab025ea008.jpg)

 Steps to reproduce:
0. Have downloaded source from GitHub, branch 'release-90', latest revision, configured.
1. Build omim:
```
export CC=/usr/bin/clang-6.0
export CXX=/usr/bin/clang++-6.0
tools/unix/build_omim -csr generator_tool
```
build log: 
[build.log](https://github.com/mapsme/omim/files/3058593/build.log)

2. Download pbf-file:
`
wget http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf -O Uzbekistan.pbf
`
3. Create map:
`
omim/tools/unix/generate_mwm.sh Uzbekistan.pbf
`
Log: 
[generate_mwm.log](https://github.com/mapsme/omim/files/3058619/generate_mwm.log)

4. Install application on phone from Google Play.
5. Replace automatically downloaded map of Uzbekistan with generated one.
6. Try to create route between near points.
7. Got error.

**Comment by tatiana-yan** [comment]
you do not have routing data
provide BORDERS_PATH to omim/tools/unix/generate_mwm.sh (see help at the top of file) and rebuild the map

**Comment by tatiana-yan** [comment]
you can find borders in data/borders

**Comment by alexx7676** [comment]
Thanks, it helped me.
