### ISSUE TITLE
[Q] Get city info through lng and lat

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#1066]
Hi, Could I get the city info through lng and lat.

**Comment by deathbaba** [comment]
Can you please clarify your question? What info are you asking about?

**Comment by simon247** [comment]
Does MapMe provide any api to get the City name, City code through Coordinates (longitude, latitude).

**Comment by deathbaba** [comment]
No at the moment.

**Comment by simon247** [comment]
Is there any other way to know  which city belongs when  the POI clicked on the map? (offline modle)

**Comment by deathbaba** [comment]
I don't know other ways, sorry.

**Comment by simon247** [comment]
OK, I see.  Thank you!
