### ISSUE TITLE
App (F-Droid) won't start, can't download initial map

### ISSUE THREAD

**Issue by ElDifinitivo** [mapsme/omim#10686]
App version: v8.6.2-2
Android version: LineageOS 16
LOS Build number: lineage_cheesburger-userdebug 9 PQ2A.190405.003 c8d3970a07

Opening up the app gives the expected "Before you start using the app, allow us to download the general world map to your device. It will use 50 MB of storage."

Clicking download will make it seem like it's working fine, but a few seconds later an error message states "Download has failed. Touch to try again." Every subsequent retry brings up the same message.

[Pastebin of all "MapsmeCore" error messages](http://paste.debian.net/hidden/6522c82d/)

**Comment by roseswe** [comment]
Same problem with Lineage OS15, also this link from the readme.md is dead, maybe root cause?
daily.mapswithme.com/direct/latest

**Comment by Darellur** [comment]
The same problem on Android 5.1.1

**Comment by ForkWithMe** [comment]
What a piece of impudence, F-Droid version has nothing to do with the app. There is no point to post such issues here, you should contact author of F-Droid build directly.

**Comment by mxmilkb** [comment]
It appears there is a possibility that you might not know what the definition of "impudence" is.
