### ISSUE TITLE
Paid ad free version

### ISSUE THREAD

**Issue by ghost** [mapsme/omim#1074]
I know you used to have one, but would you consider adding an option to fund development and remove ads by charging a fair price for your worthy software product?

**Comment by deathbaba** [comment]
You can turn off partners offers in app’s Settings if you want.

**Comment by wkfobixp** [comment]
That's a gracious option, and more than most apps offer! I don't want to tell you how you should run your business, but I wish that users could choose to support you. :)

**Comment by socketpair** [comment]
Yes. I want to pay for that good application. Even if it is open source. I dont want to be a sponsor of mail.ru group, but want my money to go to developers pocket.

**Comment by deathbaba** [comment]
You can buy some gift and deliver it to MAPS.ME’s office in Moscow, on 25th floor :) https://corp.mail.ru/en/company/contacts/ <https://corp.mail.ru/en/company/contacts/>
