### ISSUE TITLE
Wiki link to strings.txt broken

### ISSUE THREAD

**Issue by nmxcgeo** [mapsme/omim#10812]
Hi,

I wanted to correct some translations and found that the links to strings.txt file in https://github.com/mapsme/omim/wiki/strings.txt and https://github.com/mapsme/omim/wiki/categories.txt are broken.

Please link the correct location to simplify contributing to your translations.

Greetings
nmxcgeo

**Comment by mpimenov** [comment]
Thanks. The information on these two pages is now up to date.
