### ISSUE TITLE
В сгенерированных картах отсутствует слой метрополитена

### ISSUE THREAD

**Issue by alexx7676** [mapsme/omim#10864]
Собрал OMIM из ветки release-91, генерирую карту из Uzbekistan.pbf, взятого у Geofabrik.de. В сгенерированной карте отсутствует слой метро в Ташкенте. При этом в карте, скачанной самим приложением, этот слой есть.
Надо что-то включать при сборке OMIM / генерации карты?

**Comment by alexx7676** [comment]
Параметры сборки:
```
CC=/usr/bin/gcc-8
CXX=/usr/bin/g++-8
CFLAGS="-O3 -march=amdfam10"
CXXFLAGS="-O3 -march=amdfam10"
```
OMIM, ветка `release-91`, коммит 3f0b68be84.
```
./configure.sh
tools/unix/build_omim.sh -csr generator_tool
```
При сборке выпала ошибка:
```
/home/alex/projects/osm/omim/generator/generator_tool/generator_tool.cpp:71:10: fatal error: boost/stacktrace.hpp: Нет такого файла или каталога
 #include <boost/stacktrace.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [generator/generator_tool/CMakeFiles/generator_tool.dir/generator_tool.cpp.o] Ошибка 1
```
Скачал boost_1_70_0, развернул, указал путь в BOOST_ROOT, снова запустил сборку.

**Comment by alexx7676** [comment]
Теперь проект собрался успешно.
Скачиваю исходные данные для карты:
`wget http://download.geofabrik.de/asia/uzbekistan-latest.osm.pbf -O Uzbekistan.pbf`
Генерирую карту:
`omim/tools/unix/generate_mwm.sh Uzbekistan.pbf`
Лог генерации карты:
[log.txt](https://github.com/mapsme/omim/files/3174066/log.txt)
Загружаю карту в мобилку, maps.me версии 9.1.5.
Очищаю кэш приложения, запускаю.
Выбираю слой карты "Метро", в ответ "Карта метро недоступна".
![изображение](https://user-images.githubusercontent.com/44890785/57641506-97159e80-75ce-11e9-9921-6d8b3685ec9e.png)

**Comment by alexx7676** [comment]
Что я делаю не так?

**Comment by alexey-zakharenkov** [comment]
alexx7676,
подключение слоя метро в настоящий момент не автоматизировано, над этим ведётся работа.

**Comment by alexx7676** [comment]
Алексей, спасибо.
Просьба, как подключение автоматизируется, пожалуйста, закройте тикет.
Спасибо.

**Comment by alexx7676** [comment]
@alexey-zakharenkov , как включить слой метрополитена в свои карты вручную?

**Comment by dimqua** [comment]
@alexx7676  https://github.com/mapsme/omim/blob/master/tools/python/maps_generator/README.md

**Comment by dimqua** [comment]
@alexey-zakharenkov Речь идет об автоматическом получении с сервера mapsme или автоматической генерации этого слоя?

**Comment by maksimandrianov** [comment]
В  https://github.com/mapsme/omim/blob/master/tools/python/maps_generator/README.md по умолчанию выкачивается ежедневная сборка метро, т.е. с недавнего момента метро будет по умолчанию.
Так же вы можете собрать файл для метро по инструкции
https://github.com/mapsme/omim/blob/master/docs/SUBWAY_GENERATION.md и указать ссылку на него в кофиге maps_generator

**Comment by tatiana-yan** [comment]
По просьбе автора, закрываю issue после автоматизации генерации данных для метро.
