### ISSUE TITLE
Translations don't appear (Follow up #10859)

### ISSUE THREAD

**Issue by nmxcgeo** [mapsme/omim#11017]
After merging #10859 (#10924) I assumed, that the changes would be incorporated into the next release. However none of the changes appeared at the assumed places. Searching for the new aliases in data/categories.txt doesn't work and the new names in strings.txt don't appear (see screenshot for example, should be "Wettbüro", not "Buchmacher").

Or didn't I do the changes at the right place?

![buchmacher](https://user-images.githubusercontent.com/25130823/59086014-bf0fcd80-8900-11e9-8434-8324c1c9748c.jpg)

**Comment by tatiana-yan** [comment]
Hello! Request was merged after release 9.1 code freeze.
Changes will appear in release 9.2.

**Comment by nmxcgeo** [comment]
Thanks for your reply. You could perhaps tag the relevant commits to avoid such questions in the future.
