### ISSUE TITLE
Option to stop "Jump to here" on open

### ISSUE THREAD

**Issue by GhostInTheKayak** [mapsme/omim#11061]
The iPad app always jumps to the current location when the app is opened.

I am looking at a location on the map.
I put the iPad down and after a couple of minutes the iPad "rests".
I open the iPad again and go back to the app to look at the place I found a moment ago.
The app immediately  jumps to my current location and I lose the location I was looking at.

There needs to be an option to turn off this behaviour.
There is the "Jump to here" button on the app so this behaviour is not needed.

**Comment by burivuh** [comment]
Hi!

We've found an ugly bug, that in some cases forced viewport to jump. The correct behaviour is to jump only after an hour or more without usage.

Please, check 9.2 release in a couple of weeks.

**Comment by GhostInTheKayak** [comment]
This is indeed solved.
Many thanks
