### ISSUE TITLE
Unable to build Android version: invalid path to compiler

### ISSUE THREAD

**Issue by dsmelov** [mapsme/omim#113]
There is no llvm-3.6 directory in my NDK r10d for some reason - llvm-3.5 only, so Android build fails with the following error:

./set_up_android.py --sdk /Users/dns/bin/android-sdk-macosx/ --ndk /Users/dns/bin/android-ndk-r10d/

./gradlew clean assembleWebRelease

…

/Users/dns/bin/android-ndk-r10d//toolchains/llvm-3.6/prebuilt/darwin-x86_64/bin/clang -c -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mthumb -fomit-frame-pointer -fno-strict-aliasing -fno-integrated-as -march=armv7-a -mfpu=vfpv3-d16 -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -DANDROID -gcc-toolchain /Users/dns/bin/android-ndk-r10d//toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64 -target armv7-none-linux-androideabi -Wa,--noexecstack -Wformat -Werror=format-security -Wno-extern-c-compat -Wno-deprecated-register --sysroot=/Users/dns/bin/android-ndk-r10d//platforms/android-15/arch-arm/usr/include/../.. -O3 -g -DNDEBUG -DRELEASE -D_RELEASE -O3 -ffast-math -fvisibility=hidden -DRELEASE -D_RELEASE -DNDEBUG -DOMIM_PRODUCTION -DHAVE_CONFIG_H -DQT_NO_DEBUG -I/Users/dns/Projects/maps.me/omim/3party/fribidi -I/Users/dns/Projects/maps.me/omim-android-production-armeabi-v7a-hard/3party/fribidi -I/Users/dns/Projects/maps.me/omim/3party/fribidi/lib -I/Users/dns/Projects/maps.me/omim/3party/fribidi -I/Users/dns/Projects/maps.me/omim -I/Users/dns/Projects/maps.me/omim/3party/boost -I/Users/dns/Projects/maps.me/omim/3party/glm -I/Users/dns/bin/android-ndk-r10d/sources/cxx-stl/llvm-libc++/libcxx/include -I/Users/dns/bin/android-ndk-r10d/sources/cxx-stl/llvm-libc++abi/libcxxabi/include -I/Users/dns/bin/android-ndk-r10d/sources/android/support/include -I/Users/dns/bin/android-ndk-r10d/platforms/android-15/arch-arm/usr/include -I/Users/dns/Projects/maps.me/omim/tools/mkspecs/android-clang -o ../../out/production/tmp/fribidi/fribidi-shape.o /Users/dns/Projects/maps.me/omim/3party/fribidi/lib/fribidi-shape.c
make[2]: /Users/dns/bin/android-ndk-r10d//toolchains/llvm-3.6/prebuilt/darwin-x86_64/bin/clang: No such file or directory
make[2]: *** [../../out/production/tmp/freetype/afangles.o] Error 1
make[2]: *** [../../out/production/tmp/fribidi/fribidi-shape.o] Error 1
make[1]: *** [sub-freetype-make_first] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [sub-fribidi-make_first] Error 2
make: *** [sub-3party-make_first-ordered] Error 2
+ echo 'ERROR while building armeabi-v7a-hard config'
+ exit 1
ERROR while building armeabi-v7a-hard config

**Comment by dsmelov** [comment]
ln -s llvm-3.5 llvm-3.6 solves problem

**Comment by Mixaill** [comment]
Clang 3.6 was added in NDK 10e.

**Comment by dsmelov** [comment]
Noted. I think INSTALL.md needs to be slightly updated to avoid such issues - any references to sdk/ndk versions should be removed:

--ndk /Users/yourusername/Library/Android/android-ndk-r10d
