### ISSUE TITLE
Failed to build generator_tool

### ISSUE THREAD

**Issue by Vascom** [mapsme/omim#11330]
I am try build maps_generator from instructions and first step failed.

Here https://github.com/mapsme/omim/tree/master/tools/python/maps_generator instruction:
0. Build and install generator_tool.
omim/tools/unix/build_omim.sh -sr generator_tool

I have this error:
```
CMake Error at shaders/CMakeLists.txt:53 (add_library):
  Cannot find source file:

    gl_shaders.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at shaders/CMakeLists.txt:53 (add_library):
  No SOURCES given to target: shaders
```
generator_tool not built.

How to solve this problem?

**Comment by Vascom** [comment]
I am comment **add_subdirectory(shaders)** line in CMakeLists.txt.

**Comment by tatiana-yan** [comment]
run 
`echo | ./configure.sh` 
before 
`omim/tools/unix/build_omim.sh -sr generator_tool`

**Comment by Vascom** [comment]
```
$ echo | ./configure.sh
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Unicode/ICU support for Boost.Regex?... /usr
Backing up existing Boost.Build configuration in project-config.jam.1
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2
    
To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help
     
   - Getting started guide: 
     http://www.boost.org/more/getting_started/unix-variants.html
     
   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)
    - symlinks supported       : yes (cached)
...found 1104 targets...
If you are developer from MAPS.ME team, please specify a private repository url here.
If not [yet :)], then just press Enter.
> Initializing repository with default values in Open-Source mode.
```
Problem still here:
$ tools/unix/build_omim.sh -sr generator_tool
-- The C compiler identification is GNU 9.1.1
-- The CXX compiler identification is GNU 9.1.1
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Configure build version ...
-- Found Git: /usr/bin/git (found version "2.21.0") 
Setting PLATFORM_LINUX to true
Build type: Release
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib64/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:200 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib64/libOpenGL.so   
Doing nothing, because we know nothing about developer frameworks dir
Skipping pybindings subdirectory pymwm_diff
Skipping pybindings subdirectory pykmlib
Skipping pybindings subdirectory pylocal_ads
Skipping pybindings subdirectory pysearch
Skipping pybindings subdirectory pytracking
Skipping pybindings subdirectory pytraffic
Skipping pybindings subdirectory pytrack_generator
-- Configuring done
CMake Error at shaders/CMakeLists.txt:53 (add_library):
  Cannot find source file:

    gl_shaders.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at shaders/CMakeLists.txt:53 (add_library):
  No SOURCES given to target: shaders


-- Build files have been written to: /home/vascom/omim-build-release
```

**Comment by gmoryes** [comment]
This is strange, because these files generated by shaders/CMakeLists.txt:3
```
execute_process(
  COMMAND python ${OMIM_ROOT}/shaders/gl_shaders_preprocessor.py
  ${OMIM_ROOT}/shaders/GL
  shader_index.txt
  programs.hpp
  shaders_lib.glsl
  ${OMIM_ROOT}/shaders
  gl_shaders
)
```

1) Does `python` installed on your computer?
if no try to install and run `build_omim` again, If yes, try
```
python /home/vascom/omim/shaders/gl_shaders_preprocessor.py /home/vascom/omim/shaders/GL shader_index.txt programs.hpp shaders_lib.glsl /home/vascom/omim/shaders gl_shaders
```
Does this command execute correctly? 
If no, send command's output here and say the your's python version

**Comment by Vascom** [comment]
I found it.
You use `COMMAND python` but Fedora Linux has no unversioned python command by default.
Please change your code to `COMMAND python3`.

**Comment by gmoryes** [comment]
> I found it.
> You use `COMMAND python` but Fedora Linux has no unversioned python command by default.
> Please change your code to `COMMAND python3`.

https://github.com/mapsme/omim/pull/11355

**Comment by gmoryes** [comment]
Make `git pull` and try again

**Comment by Vascom** [comment]
All good now.
Thanks.
