### ISSUE TITLE
release versions & changelog

### ISSUE THREAD

**Issue by porjo** [mapsme/omim#114]
Dropbox release folder contains files with version `5.1.1` yet on my Android phone the 'About MAPS.ME' screen shows version `5.1.3-Google`. Can someone explain the difference?

Also, is there a changelog that shows what has changed between releases?  I can look at Git log, but as git tags aren't being used, it makes it hard to know what has changed between specific release versions.

Thanks.

**Comment by therearesomewhocallmetim** [comment]
We increase the version number before the corresponding release, and in some cases we release from a release branch, not master, which may sometimes result in the old version number still being in the master branch. 

We will think how we can make it more clear, which build is uploaded to the dropbox share.

Best regards, 
Timofey
