### ISSUE TITLE
Routing fails on weekly map builds

### ISSUE THREAD

**Issue by nmxcgeo** [mapsme/omim#11499]
When using the weekly map builds via direct download (btw. THANKS, they are really valueable) routing fails. Once you have chosen the target and the route is supposed to be calculated the app crashes and has to be restarted. 

Android 9.1 Huawei P20 Lite
Maps.Me 9.1.7

**Comment by maksimandrianov** [comment]
Hello, we generated maps using generator_tool building from the master branch. Please try to update maps.me app.

**Comment by thany** [comment]
Is there documentation on how to use generator_tool? Then these folks can use it from the correct branch.

**Comment by maksimandrianov** [comment]
https://github.com/mapsme/dockerfiles/tree/master/maps_generator/
It has worked form release 9.2. Please try to run docker container with the option --build-arg TAG=release-92.

**Comment by nmxcgeo** [comment]
> Hello, we generated maps using generator_tool building from the master branch. Please try to update maps.me app.

Works for me.
