### ISSUE TITLE
Route planner likes to zigzag

### ISSUE THREAD

**Issue by grinapo** [mapsme/omim#1151]
Not a large bug just a tidbit to help to make it more useful (=real life aware).

I was planning from wherever Hungary (say Budapest) to Altenmarkt im Pongau, Austria (great place :-)), and this one was somewhere in middle Austria. 

I try to include a screenshot if github permits.....

![screenshot_2015-12-26-10-14-43](https://cloud.githubusercontent.com/assets/1056054/12005901/bc29b0e2-abbc-11e5-8fb1-64f38cc08b25.png)

**Comment by Zverik** [comment]
http://www.openstreetmap.org/directions?engine=osrm_car&route=47.5606%2C14.2491%3B47.5660%2C14.2360#map=16/47.5634/14.2426

**Comment by Zverik** [comment]
Thanks for reporting this. Somebody drew an impassable traffic lights, and maps.me tried to route around it. I've [fixed it](http://www.openstreetmap.org/node/455868437/history), but you will have to wait until January to see it in maps.me.

**Comment by grinapo** [comment]
I usually cross-check with other programs (osmand and mapsfactor are the usual picks) so it seems they've ignored this pretty weird combination; if I try to find some logic in it this tagging may mean that the crossing is forbidden for pedestrians but it shouldn't affect the traffic of the way. But I can accept the approach that a no-access node on a way may mean no access from any direction.
(I have updated it again as foot=no, it's a crossing leading to a supermarket under construction thus closed. Lucky someone drove there with mapillary; Austria is street no-view.)
