### ISSUE TITLE
Use of undeclared identifier 'CROWN_PERCENT_OF_DEVICES'

### ISSUE THREAD

**Issue by VMironiuk** [mapsme/omim#11647]
**OS:**

- MacOS Mojave 10.14.6

**Steps to reproduce:**

- Clone the project recursively
- Run configure.sh
- Build the MAPS.ME scheme in Xcode

**Comment by limingchina** [comment]
Same build failure on Linux. this seems to be a general build failure. I'm wondering that there is no CI build check for the project?

**Comment by VMironiuk** [comment]
@limingchina This can be fixed by adding CROWN_PERCENT_OF_DEVICES constant to private.h manually and waiting for official fix
