### ISSUE TITLE
Bug: Crash due to OSRM Routing Assertion Fail (TurnsGenerator/LoadedPathSegment)

### ISSUE THREAD

**Issue by stangls** [mapsme/omim#1172]
Hello,
I'm experiencing a reproducable crash with MAPS.ME on Android when routing from the coordinates 47.798609,12.121383 to 47.801317,12.1205 using car-navigation (walking directions are fine).
After building and executing the latest version (5.4-Web-debug) from master-branch (a6d040b95bb) I get in android-studio (latest three lines are most important):
```

12-29 13:17:36.136 23013-23041/com.mapswithme.maps.pro.debug D/MapsWithMe_JNI: routing/async_router.cpp:291 CalculateRoute()  Calculating the route from m2::Point<d>(12.121094799999999836, 54.558763652061500693) to m2::Point<d>(12.120576622594141369, 54.562324689059543914) startDirection m2::Point<d>(0, 0)
12-29 13:17:36.236 23013-23041/com.mapswithme.maps.pro.debug D/MapsWithMe_JNI: platform/platform_android.cpp:86 ~DbgLogger()  Source for file /storage/emulated/0/MapsWithMe/151103/Germany_Bavaria.mwm is 4
12-29 13:17:36.276 23013-23041/com.mapswithme.maps.pro.debug I/MapsWithMe_JNI: routing/osrm_router.cpp:254 CalculateRoute()  Duration of the MWM loading 82102000
12-29 13:17:36.356 23013-23041/com.mapswithme.maps.pro.debug D/MapsWithMe_JNI: platform/platform_android.cpp:86 ~DbgLogger()  Source for file /storage/emulated/0/MapsWithMe/151103/Germany_Bavaria.mwm is 4
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug I/MapsWithMe_JNI: routing/osrm_router.cpp:281 CalculateRoute()  Duration of the start/stop points lookup 462682000
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug I/MapsWithMe_JNI: routing/osrm_router.cpp:294 CalculateRoute()  Single mwm routing case
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug D/MapsWithMe_JNI: routing/osrm_router.cpp:383 MakeTurnAnnotation()  Shortest path length: 78
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug A/MapsWithMe_JNI: routing/turns_generator.cpp:489 LoadPathGeometry()  CHECK(startIndex < endIndex) 3 1 
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug A/libc: jni/com/mapswithme/core/logging.cpp:53: void jni::AndroidAssertMessage(const my::SrcPoint &, const string &): assertion "false" failed
12-29 13:17:36.736 23013-23041/com.mapswithme.maps.pro.debug A/libc: Fatal signal 6 (SIGABRT) at 0x000059e5 (code=-6), thread 23041 (.maps.pro.debug)
```

The crash happens also with the released version available on Google Play (version 5.4-Google) and original maps.

**Comment by deathbaba** [comment]
Thanks! @gardster can you please take a look on this crash?

**Comment by gardster** [comment]
Hello!
What version of the mwm file do you use? Seems like it was broken.

**Comment by stangls** [comment]
The crash occured with:
* the original mwm file for Germany/Bavaria (downloaded from the server via MAPS.ME from Google Play Version 5.4-Google) on one android device.
* mvm converted from OpenStreetMap Data (oberbayern-latest.osm.pbf, 25.11.2015)

I will now download and convert newest OSM data from http://download.geofabrik.de/europe/germany/bayern/oberbayern.html to verify if updated map-data solves this problem.

**Comment by stangls** [comment]
I used oberbayern-latest.osm.pbf with OSM data up to 2015-12-28T20:14:01Z and cut out a smaller rectangle (11.999313356163,47.722639017669,12.19931335619,47.883424917193) using *osmconvert*.
Then I converted the resulting osm-file using *omim/tools/unix/generate_mwm.sh* with routing data. See [this log-file](https://github.com/mapsme/omim/files/74036/bavaria-rectangle-conversion-mwm.out.zip).
After pushing to the device via:
```
adb push -p bavaria-rectangle.mwm.routing /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria.mwm.routing
adb push -p bavaria-rectangle.mwm. /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria.mwm
```

Crash still occurs.

**Comment by stangls** [comment]
If you can/want to investigate the map-data, please see [this zip-file](https://github.com/mapsme/omim/files/74050/bavaria-rectangle.zip) for OSM and MWM data. It includes the rectangle as described above.

**Comment by gardster** [comment]
It is necessary completely remove all index files if you manually update the mwm file. Please, manually remove Germany_Bavaria.bftsegbits   Germany_Bavaria.bftsegnodes and  Germany_Bavaria.offsets from /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria/ .

**Comment by stangls** [comment]
I stopped the application and removed the files using:
```
adb shell "rm -rf /storage/emulated/legacy/MapsWithMe/151103/"
adb shell "mkdir -p /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria/"
adb push -p bavaria-rectangle.mwm.routing /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria.mwm.routing
adb push -p bavaria-rectangle.mwm /storage/emulated/legacy/MapsWithMe/151103/Germany_Bavaria.mwm
```
Sadly, the crash still occurs.

**Comment by gardster** [comment]
I have reproduce this crash on my computer. Fixing this issue will take some time. Thank you for report.

**Comment by stangls** [comment]
Ok thank you.
I would try to help, but I do not have time to fully understand the file-format. In order to do so, I'd like to debug the application under Ubuntu, which is not so easy, but that's another issue (for next year)...
Looking forward to hearing from you about the crash-fix :)

**Comment by gardster** [comment]
@stangls check out our new master. #1272 must fix this crash.

**Comment by stangls** [comment]
Yes.
Thank you very much!
