### ISSUE TITLE
[Feature request] Use maps downloaded by OsmAnd

### ISSUE THREAD

**Issue by kujaw** [mapsme/omim#11782]
Is there a possibility to use already downloaded maps via OsmAnd in MAPS.ME app?
It would save lots of space if one has multiple files downloaded.
If not, I'd like to request this feature and thank for your hard work.

**Comment by burivuh** [comment]
No, it is near impossible. Current data format and our app is a monolithic optimised system Create an adapter for another format is a waste of resources for our team.

**Comment by strebski** [comment]
@kujaw

You can also ask OsmAnd team about using Maps.Me map resources... Answer will be similar, I think.

**Comment by kujaw** [comment]
I get it, just thought that if both use OSM maps it won't be so difficult. Thanks for response.
