### ISSUE TITLE
[Routing] treat chipseal as paved

### ISSUE THREAD

**Issue by mtmail** [mapsme/omim#11841]
In the middle of a city (Christchurch, NZ) I was warned about an unpaved road (https://www.openstreetmap.org/way/230916893/). The `surface=chipseal` isn't documented in the OSM wiki (https://wiki.openstreetmap.org/wiki/Key:surface) but apparently used https://taginfo.openstreetmap.org/tags/surface=chipseal

If you have a list of OSM tags can you add chipseal to paved? It looked and felt like a normal paved road, not different from the roads around it. https://www.google.com/search?tbm=isch&q=chipseal%20road&tbs=imgo:1

(I tried emailing after reading https://github.com/mapsme/omim/issues/1888#issuecomment-495887923 but the email bounced)

**Comment by gmoryes** [comment]
> In the middle of a city (Christchurch, NZ) I was warned about an unpaved road (https://www.openstreetmap.org/way/230916893/). The `surface=chipseal` isn't documented in the OSM wiki (https://wiki.openstreetmap.org/wiki/Key:surface) but apparently used https://taginfo.openstreetmap.org/tags/surface=chipseal
> 
> If you have a list of OSM tags can you add chipseal to paved? It looked and felt like a normal paved road, not different from the roads around it. https://www.google.com/search?tbm=isch&q=chipseal%20road&tbs=imgo:1
> 
> (I tried emailing after reading [#1888 (comment)](https://github.com/mapsme/omim/issues/1888#issuecomment-495887923) but the email bounced)

Hello
Thank you for this information! We will check this surface tag and possibly exclude this one from "unpaved" types of road

**Comment by gmoryes** [comment]
Your issue will be solved in the next release
