### ISSUE TITLE
Map generation of a custom .osm file not working

### ISSUE THREAD

**Issue by dew54** [mapsme/omim#11850]
Hello, i'm trying to convert a special custom .osm file made by myself, it's a little bbox near Matera, in Italy. I've tries to create a .poly from that .osm and loaded in /data/borders/ folder.. also updated the file_generation_order.txt in /tools/python/maps_generator/var/etc.. with no luck.
I've tried so Italy_Basilicata.poly as border file (wich is the region of Matera), it works but maps.me android app shows the entire region without my custom elements.
Is it a way to create a custom map with custom borders? Thank you 
Davide

**Comment by mpimenov** [comment]
What do you mean by "custom elements"? Do you want to see some sort of patched data on your map or maybe all you want is just a small map that omits everything non-important to you?

Assuming it's the latter,
1. What you did seems reasonable but the borders are hardwired in the app. So you will need one more step: rebuild [packed_polygons.bin](https://github.com/mapsme/omim/blob/59e7eaa61338b9fae3ae502c115f768fbf3bdfd9/data/packed_polygons.bin) from your modified *.poly files. Use the [GeneratePackedBorders](https://github.com/mapsme/omim/blob/59e7eaa61338b9fae3ae502c115f768fbf3bdfd9/generator/borders.hpp#L141) function.
2. Another solution is to leave the *.poly and related files intact and to preprocess the OSM data from which your mwm is made, i.e. make the mwm of the whole region from a modified OSM source. One tool that may help is [OsmCut](https://wiki.openstreetmap.org/wiki/Osmcut).

**Comment by dew54** [comment]
Hello mpimenov, thanks for your reply! With custom elements i mean private roads and nodes that i've inserted in the .osm. I really would just convert a rectangular bounding box from .osm to .mwm, is it possible?
Tomorrow i'll try with the first option, thanks

**Comment by dew54** [comment]
So.. i've taken a look.. please, i'm new with c language etc. could you kindly explain how could i use "GeneratePackedBorders" function? Should i recompile the maps_generator? 
I really hope you'll so kind, thanks a lot

**Comment by mpimenov** [comment]
You do have ```generator_tool``` compiled, right?
Pass the [generate_packed_borders](https://github.com/mapsme/omim/blob/59e7eaa61338b9fae3ae502c115f768fbf3bdfd9/generator/generator_tool/generator_tool.cpp#L179) flag to it.

**Comment by dew54** [comment]
Ok, so, in /omim-build-release/ i ran:
`./generation_tool -generate_packed_borders`
No errors are throwed.
Then i went to /omim/tools/python and ran
`python3.7 -m maps_generator --countries="Italy_matera" --skip="coastline"`
But this error still to be thrown:
`ValueError: /Users/davide/omim/tools/python/maps_generator/var/etc/file_generation_order.txt does not have an order for {'Italy_matera'}.
`
even if i putted at the bottom of 'file_generation_order.txt' this line:
`Italy_matera 20.00000` 

What i'm doing wrong?

Again, 
thank you for your availability

**Comment by tatiana-yan** [comment]
file_generation_order.txt is tab separated is it tab or space between `Italy_matera` and `20.00000`?

**Comment by mpimenov** [comment]
Renaming the map file itself is harder, let's not do it for now.

In your original post you said that you work with Italy_Basilicata.poly and what I'm trying to do is to explain how to alter this file and use the altered file through the app.

**Comment by dew54** [comment]
Ok so, now it works, thanks @tatiana-yan for your advice, i placed a space while a tab space was needed. I'm trying now to generate my map but.. it's quiet slow because of the file downloadings such as the subways data and islands.o5m.. i haven't understood why is this necessary but however is there a way to download all just one time and re use for further generations?
Maybe should i open another issue?
Thank you, Davide

**Comment by tatiana-yan** [comment]
islands.o5m looks like you have wrong config at tools/python/maps_generator/var/etc/map_generator.ini

check PLANET_URL parameter, it should be

```PLANET_URL:file://<local path to your data.osm.pbf>```

and as @mpimenov said it's hard to add map with new name to the app. There are lots of places to modify like countries.txt, countries_names.txt etc. Wihtout it something will work but something will not.
Build Italy_Basilicata.mwm with small part of osm cutted by osmcut may be better option.

**Comment by dew54** [comment]
Ok, thanks for your advice, i'm trying this way but now new problems raised:

`raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /Users/davidevidmar/osmctools/osmconvert /Users/davidevidmar/maps_build/planet.osm.pbf --drop-author --drop-version --out-o5m -o=/Users/davidevidmar/maps_build/planet.o5m failed.
`

when i run the command:
`python3.7 -m maps_generator --countries="Italy_Basilicata" --skip="coastline"`

And my map_generator.ini looks like:
`[Main]
MAIN_OUT_PATH: ~/maps_build
DEBUG: 0


[Developer]
BUILD_PATH: ~/omim-build-release
OMIM_PATH: ~/omim


[Generator tool]
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data
# auto detection
# NODE_STORAGE: map


[Osm tools]
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
OSM_TOOLS_PATH: ~/osmctools


[Logging]
# LOG_FILE_PATH: generation.log


[External]
 PLANET_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf
 PLANET_MD5_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf.md5
# PLANET_COASTS_URL:
 SUBWAY_URL:file:///Users/davidevidmar/Desktop/latest.json
# UGC_URL:
# HOTELS_URL:
# PROMO_CATALOG_CITIES_URL:
# POPULARITY_URL:
# FOOD_URL:
# FOOD_TRANSLATIONS_URL:
# POSTCODES_URL:
# SRTM_PATH:

[Stats]
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
`
Maybe something is broken, later i'll try to recompile everything

Thank you,
Davide

**Comment by dew54** [comment]
Ok, thanks for your advice, i'm trying this way but now new problems raised:

raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.") maps_generator.generator.exceptions.BadExitStatusError: The launch of /Users/davidevidmar/osmctools/osmconvert /Users/davidevidmar/maps_build/planet.osm.pbf --drop-author --drop-version --out-o5m -o=/Users/davidevidmar/maps_build/planet.o5m failed.

when i run the command:
python3.7 -m maps_generator --countries="Italy_Basilicata" --skip="coastline"

And my map_generator.ini looks like:
`[Main]
MAIN_OUT_PATH: ~/maps_build
DEBUG: 0

[Developer]
BUILD_PATH: ~/omim-build-release
OMIM_PATH: ~/omim

[Generator tool]
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data

auto detection
NODE_STORAGE: map
[Osm tools]
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
OSM_TOOLS_PATH: ~/osmctools

[Logging]

LOG_FILE_PATH: generation.log
[External]
PLANET_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf
PLANET_MD5_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf.md5

PLANET_COASTS_URL:
SUBWAY_URL:file:///Users/davidevidmar/Desktop/latest.json

UGC_URL:
HOTELS_URL:
PROMO_CATALOG_CITIES_URL:
POPULARITY_URL:
FOOD_URL:
FOOD_TRANSLATIONS_URL:
POSTCODES_URL:
SRTM_PATH:
[Stats]
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
`
Maybe something is broken, later i'll try to recompile everything

Please note that words with capital fonts are commented.
Also i've downloaded latest.json from the subway url and placed the file path in the subway section

Thank you,
Davide

**Comment by dew54** [comment]
Ok, thanks for your advice, i'm trying this way but now new problems raised:

raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.") maps_generator.generator.exceptions.BadExitStatusError: The launch of /Users/davidevidmar/osmctools/osmconvert /Users/davidevidmar/maps_build/planet.osm.pbf --drop-author --drop-version --out-o5m -o=/Users/davidevidmar/maps_build/planet.o5m failed.

when i run the command:
python3.7 -m maps_generator --countries="Italy_Basilicata" --skip="coastline"

And my map_generator.ini looks like:
`[Main]
MAIN_OUT_PATH: ~/maps_build
DEBUG: 0

[Developer]
BUILD_PATH: ~/omim-build-release
OMIM_PATH: ~/omim

[Generator tool]
USER_RESOURCE_PATH: ${Developer:OMIM_PATH}/data

auto detection
NODE_STORAGE: map
[Osm tools]
OSM_TOOLS_SRC_PATH: ${Developer:OMIM_PATH}/tools/osmctools
OSM_TOOLS_PATH: ~/osmctools

[Logging]

LOG_FILE_PATH: generation.log
[External]
PLANET_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf
PLANET_MD5_URL:file:///Users/davide/Desktop/Basilicata.osm.pbf.md5

PLANET_COASTS_URL:
SUBWAY_URL:file:///Users/davide/Desktop/latest.json

UGC_URL:
HOTELS_URL:
PROMO_CATALOG_CITIES_URL:
POPULARITY_URL:
FOOD_URL:
FOOD_TRANSLATIONS_URL:
POSTCODES_URL:
SRTM_PATH:
[Stats]
STATS_TYPES_CONFIG: ${Developer:OMIM_PATH}/tools/python/maps_generator/var/etc/stats_types_config.txt
`
Maybe something is broken, later i'll try to recompile everything

Please note that words with capital fonts are commented.
Also i've downloaded latest.json from the subway url and placed the file path in the subway section

Thank you,
Davide

**Comment by tatiana-yan** [comment]
```
/Users/davidevidmar/osmctools/osmconvert /Users/davidevidmar/maps_build/planet.osm.pbf --drop-author --drop-version --out-o5m -o=/Users/davidevidmar/maps_build/planet.o5m failed
```

osmconvert is 3-party utility we use to convert between different osm formats. What is your file real format?

**Comment by dew54** [comment]
I use a .osm.pbf file, as it's specified in the example page:
https://github.com/mapsme/omim/tree/master/tools/python/maps_generator

**Comment by tatiana-yan** [comment]
can you run 

```
/Users/davidevidmar/osmctools/osmconvert /Users/davidevidmar/maps_build/planet.osm.pbf --drop-author --drop-version --out-o5m -o=/Users/davidevidmar/maps_build/planet.o5m
```

to see more detailed error?

**Comment by dew54** [comment]
Ok so, sorry about that.. it was mt mistake, .osm.pbf file was broken.. I fixed it but now another error occurs:

`raise BadExitStatusError(f"The launch of {' '.join(p.args)} failed.")
maps_generator.generator.exceptions.BadExitStatusError: The launch of /Users/davidevidmar/omim-build-release/generator_tool --data_path=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data --intermediate_data_path=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/davidevidmar/maps_build/planet.o5m --node_storage=map --user_resource_path=/Users/davidevidmar/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true failed.`

And i tried to execute:
`/Users/davidevidmar/omim-build-release/generator_tool --data_path=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data --intermediate_data_path=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data --osm_file_type=o5m --osm_file_name=/Users/davidevidmar/maps_build/planet.o5m --node_storage=map --user_resource_path=/Users/davidevidmar/omim/data --dump_cities_boundaries=true --cities_boundaries_data=/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data/cities_boundaries.bin --generate_features=true --generate_packed_borders=true`

that's my output:

`LOG TID(1) INFO   2.9121e-05 generator/intermediate_data.cpp:190 MapFilePointStorageReader() Nodes reading is started
LOG TID(1) INFO   0.00126737 generator/intermediate_data.cpp:207 MapFilePointStorageReader() Nodes reading is finished
LOG TID(1) INFO   0.00146182 Offsets reading is started for file /Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data/ways.dat.offs
LOG TID(1) INFO   0.00150295 Offsets reading is finished
LOG TID(1) INFO   0.00174859 generator/borders.cpp:227 LoadCountriesList() Loading countries.
LOG TID(1) INFO    0.0104619 generator/borders.cpp:232 LoadCountriesList() Countries loaded: 1
libc++abi.dylib: terminating with uncaught exception of type Writer::OpenException: Writer::OpenException /Users/davidevidmar/omim/coding/internal/file_data.cpp:60, "/Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data/cities_areas.mwm.tmp.3; Write truncate; Permission denied"
Core exception: /Users/davidevidmar/maps_build/2019_10_10__12_36_53/intermediate_data/cities_areas.mwm.tmp.3; Write truncate; Permission denied
 0# generator::ErrorHandler(int) in /Users/davidevidmar/omim-build-release/generator_tool
 1# _sigtramp in /usr/lib/system/libsystem_platform.dylib
Abort trap: 6`

I'm sorry about that but i must find a solution,
hope you can help me again :)

**Comment by tatiana-yan** [comment]
```base/checked_cast.hpp:17 CHECK((result > 0) == (v > 0)) checked_cast failed```

assert here means some wrong data was received. Usually it means some input file is broken. But I do not now which one.
I see that code received from somewhere 18446744073709431434 number but it expected much smaller number. It usually means that some binary format was broken or some data is inconsistent.
