### ISSUE TITLE
Please fix incomplete Polish locale in UI

### ISSUE THREAD

**Issue by strebski** [mapsme/omim#11910]
At latest version (9.4.3-Google) there are some double lang places in Maps.me UI, especially in Settings menu:
1. Sub-title string "General settings" should be "Ustawienia ogólne",
2. String "Auto zoom" should be "Automatyczne powiększanie",
3. Sub-title string "Information" should be "Informacje",
4. Inside "About Maps.me" (via Settings) string "Data version:" should be "Wersja danych:"

Please fix it :-)

**Comment by mpimenov** [comment]
All those are translated via [strings.txt](https://github.com/mapsme/omim/wiki/strings.txt).
Please submit your suggestions in a Pull Request.

**Comment by strebski** [comment]
[strings.txt](https://github.com/mapsme/omim/files/3745236/strings.txt)

Strings.txt is to big for editing via Github, so I've downloaded and edited locally. Included all these 4 mentioned above changes.

**Comment by strebski** [comment]
OK, I've made Pull Request already.
