### ISSUE TITLE
Enable users with OSM account to add notes on map

### ISSUE THREAD

**Issue by BANOnotIT** [mapsme/omim#11951]
I usually use the app to navigate and sometimes I suddenly don’t have much time to open an editor app to change something in OSM. So I make a note and then commit a change from my pc to OSM.
And now I cannot do any notes. All buttons are disabled. I think this is connected to issue #3901   

Personally I think that people with OSM account have some respect to this project and they now what notes are good and what are pointless.

Please. Leave me the ability to add notes so I can edit OSM I’m comfort and with no problems with remembering details of some object

**Comment by DujaOSM** [comment]
#3901 is still open, so it's not that. Devs will know better. (I do recall a recent uproar in the OSM community about abuse by means of anonymous notes, but I think they only ended up disabled on openstreetmap.org).

As a workaround, you can "add a place to the map" from Maps.me and add something other than a note, then edit it at home.

**Comment by BANOnotIT** [comment]
@DujaOSM I found previous developer @Zverik and he explained that buttons are disabled when local map data is outdated for 2 months.
