### ISSUE TITLE
Software renderer not building

### ISSUE THREAD

**Issue by utack** [mapsme/omim#11976]
Hi devs,  

I am trying to build 2a88c6ca5f90a14fdc6fb6ed47ec8dc86548187d on arch linux currently.

In the CMakeLists I enabled mapshot, to generate png images of maps.

Unfortunately the software render fails to build:

/home/jakob/Downloads/omim/software_renderer/cpu_drawer.hpp: In constructor ‘software_renderer::CPUDrawer::PointShape::PointShape(const PointD&, dp::Anchor, software_renderer::CPUDrawer::EShapeType, const software_renderer::DrawRule&, int)’:
/home/jakob/Downloads/omim/base/src_point.hpp:44:21: error: ‘SrcPoint’ is not a member of ‘software_renderer::base’
   44 | #define SRC() base::SrcPoint(__FILE__, __LINE__, __FUNCTION__, "()")

Could you please look into it? I am hoping to generate some maps to print.
Thank you very much

**Comment by gmoryes** [comment]
Could you give please the full log?

**Comment by utack** [comment]
Of course I can provide the full log, thank you for looking into it!

Freshly cloned, at fee8ebf513d9a4da930a2a067a95a9628dcb3f78, then configure.sh without arguments

Changed one line in CMakeLists to build mapshot and hence the software renderer:
option(BUILD_MAPSHOT "Build mapshot tool" ON)

Replaced PROCESSES=* in ./tools/unix/build_omim.sh with PROCESSES=1 to only run 1 build-task and keep the log in order

then started a fresh debug build
./tools/unix/build_omim.sh -cd

The full log of this is attached
[buildlog.txt](https://github.com/mapsme/omim/files/3802271/buildlog.txt)

**Comment by gmoryes** [comment]
> Of course I can provide the full log, thank you for looking into it!
> 
> Freshly cloned, at [fee8ebf](https://github.com/mapsme/omim/commit/fee8ebf513d9a4da930a2a067a95a9628dcb3f78), then configure.sh without arguments
> 
> Changed one line in CMakeLists to build mapshot and hence the software renderer:
> option(BUILD_MAPSHOT "Build mapshot tool" ON)
> 
> Replaced PROCESSES=* in ./tools/unix/build_omim.sh with PROCESSES=1 to only run 1 build-task and keep the log in order
> 
> then started a fresh debug build
> ./tools/unix/build_omim.sh -cd
> 
> The full log of this is attached
> [buildlog.txt](https://github.com/mapsme/omim/files/3802271/buildlog.txt)

@darina has fixed the build, try again with fresh master

**Comment by utack** [comment]
Hi,

thank you for looking into it.

I applied a tiny change to get mapshot to build

`diff --git a/software_renderer/point.h b/software_renderer/point.h
index c2ca849958..2da5b4d2dd 100644
--- a/software_renderer/point.h
+++ b/software_renderer/point.h
@@ -4,6 +4,7 @@
 #include <cmath>
 #include <iomanip>
 #include <limits>
+#include <vector>
 
 namespace ml
 {
`
Unfortunately however it was now breaking at link time
The relevant parts:

> [ 93%] Built target software_renderer
[ 93%] Linking CXX executable ../mapshot_tool
--------------------
/usr/bin/ld: ../libeditor.a(new_feature_categories.cpp.o): in function `osm::NewFeatureCategories::AddLanguage(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/home/jakob/Downloads/omim/editor/new_feature_categories.cpp:54: undefined reference to `indexer::CategoriesIndex::AddCategoryByTypeAndLang(unsigned int, signed char)'
/usr/bin/ld: ../libeditor.a(new_feature_categories.cpp.o): in function `osm::NewFeatureCategories::Search(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/jakob/Downloads/omim/editor/new_feature_categories.cpp:63: undefined reference to `indexer::CategoriesIndex::GetAssociatedTypes(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned int, std::allocator<unsigned int> >&) const'
collect2: error: ld returned 1 exit status
make[2]: *** [mapshot/CMakeFiles/mapshot_tool.dir/build.make:132: mapshot_tool] Error 1
make[1]: *** [CMakeFiles/Makefile2:6467: mapshot/CMakeFiles/mapshot_tool.dir/all] Error 2

**Comment by utack** [comment]
/omim/software_renderer/point.h:235:28: error: ‘vector’ is not a member of ‘std’

This is still happening, it is the very last problem
Adding a simple

`#include <vector>`

Solves it
Could you please consider adding that one line and then closing the issue?
Thank you

**Comment by mpimenov** [comment]
> Could you please consider adding that one line and then closing the issue?

Done. Thanks for the report.
