### ISSUE TITLE
Switch to a higher-quality render at an earlier zoom?

### ISSUE THREAD

**Issue by jeffrey-friedl** [mapsme/omim#1203]
Curvy mountain roads are rendered quite blocky until a certain zoom level is reached, at which point they snap into a much higher quality.  Is it possible to configure so that the blocky version is not quite so blocky, and/or that it snaps into a higher quality mode at an earlier (wider) zoom?

![zoom-comparison](https://cloud.githubusercontent.com/assets/16525084/12078444/ed7fa832-b255-11e5-8725-d01565d08f4b.png)

Thanks.

**Comment by deathbaba** [comment]
Is it iOS or Android? Have you checked it with our latest release of a new graphics library?

**Comment by jeffrey-friedl** [comment]
Sorry for not providing proper information originally. I'm using the maps.me app version 5.2 on an iPhone 6+ (iPhone7,1) running iOS 9.2

**Comment by deathbaba** [comment]
Please wait for the upcoming release, we have upgraded our rendering engine. Probably this issue should be fixed there.

**Comment by jeffrey-friedl** [comment]
Cool, thanks!
