### ISSUE TITLE
Allow 'draw over lock screen' to be disabled

### ISSUE THREAD

**Issue by camelCaseSucks** [mapsme/omim#12060]
If I have the app open when I lock my phone, just turning the screen on allows anyone to see all of my bookmarked places. This is private information that I don't want anyone to be able to access. Please let me turn this feature off.

**Comment by mpimenov** [comment]
What is your phone model and OS version?

**Comment by camelCaseSucks** [comment]
Nokia 6.1, Android 9.0

**Comment by camelCaseSucks** [comment]
This app appears to no longer cover the lock screen.
