### ISSUE TITLE
Offline travel guide always starts when opening the app

### ISSUE THREAD

**Issue by update-freak** [mapsme/omim#12107]
When opening the app Maps (9.1.8-8-Google) (on Samsung Galaxy S7, Android Oreo) the offline travel guide is always marked.
I think this should only be so at the first start of the app and then no longer occur on future launches of the app?

**Comment by tatiana-yan** [comment]
Hello!
Do you use official app from google store or some 3-party fork?
If you use official app please attach screenshots to clarify what does "travel guide always starts" mean.
If you use some 3-party fork please ask the fork author cause it looks like a fork bug.

**Comment by update-freak** [comment]
I use this app from google store (https://play.google.com/store/apps/details?id=com.github.axet.maps&hl=de&showAllReviews=true)
![Screenshot_20191125-133257_Maps](https://user-images.githubusercontent.com/40196995/69541088-a1a2ee80-0f88-11ea-9a0c-58eec9548aee.jpg)

**Comment by tatiana-yan** [comment]
It's not our app, our app ai https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro&hl=de

It's a 3-party fork and it looks like a fork bug. Official app shows this guide once by saving "guide was shown" event to metrics. Looks like fork author decided that metrics is something bad and thats why shows guide at every startup.

**Comment by update-freak** [comment]
ok, thanks!
