### ISSUE TITLE
App crashes on GetCityCatalogueUrl

### ISSUE THREAD

**Issue by kuajia** [mapsme/omim#12140]
iOS application is crashing after attemp downloading an mwm file from custom map server

```
LOG TID(1) DEBUG     8.18239 platform/http_thread_apple.mm:79 -[HttpThreadImpl initWithURL:callback:begRange:endRange:expectedSize:postBody:] http:// . . ./mapserver/ios/190910/Italy_Campania.mwm downloading range [ 0 , 524287 ]
LOG TID(1) DEBUG     8.18268 platform/http_thread_apple.mm:117 -[HttpThreadImpl initWithURL:callback:begRange:endRange:expectedSize:postBody:] ID: 10757603904 Starting data task for http:// . . . /mapserver/ios/190910/Italy_Campania.mwm
ASSERT FAILED
partners_api/promo_api.cpp:151
CHECK(!baseUrl.empty()) 
Assertion failed: (false), function GetCityCatalogueUrl, file /Users/ . . . / . . ./Progetti/omim/partners_api/promo_api.cpp, line 151.
```

**Comment by milchakov** [comment]
Hello. Please checkout new version of code, it is fixed about 2 months ago.

**Comment by kuajia** [comment]
Last time I updated the project I had some problem with the route recalculation, so I had to went back to previous version. 

It is also Hilarious this fix has been requested by me in an old report.

Thx.

**Comment by milchakov** [comment]
You can try to apply commits from this pr to your version of code, https://github.com/mapsme/omim/pull/11862/commits
