### ISSUE TITLE
incremental map updates

### ISSUE THREAD

**Issue by jiuxs33** [mapsme/omim#12342]
Does mapsme have incremental update function?

**Comment by tatiana-yan** [comment]
Yes. By default if your current map is not too old (1 or 2 release older than actual map) map will be updated incrementally: app will download and apply diff.

**Comment by jiuxs33** [comment]
I just want to generate incremental packages. Can I do it?

**Comment by jiuxs33** [comment]
Find the relevant code: mwm_diff. but how to use it?

**Comment by jiuxs33** [comment]
omim/cmakelists.txt
71:`option(PYBINDINGS "Create makefiles for building python bindings" ON)`
Error: `You need to specify PYBINDINGS_VERSION to build PYBINDINGS`

**Comment by jiuxs33** [comment]
@tatiana-yan
