### ISSUE TITLE
Maps.me on F-Droid

### ISSUE THREAD

**Issue by FinixFighter** [mapsme/omim#12395]
Hi! I just wanted to ask if Maps.me will be available on F-Droid in the future

**Comment by contrapunctus-1** [comment]
Please search the issues before you create one. #85 covers the matter in detail.

Axet made a fork of MAPS.ME called Maps, which satisfies the criteria for F-Droid inclusion and is available there -
https://f-droid.org/app/com.github.axet.maps

**Comment by FinixFighter** [comment]
Thanks, sorry for that!
