### ISSUE TITLE
3D buildings does not like Olympic Tower in Munich

### ISSUE THREAD

**Issue by utack** [mapsme/omim#1261]
The Olympic Tower in Munich:
http://www.openstreetmap.org/way/18894695
is entered in OSM with some objects of overlapping height
(center is 0-291m, the outer rings sitting on the top somewhere within in this range)
Wikipedia Image:
![munchen_-_olympiaturm_3](https://cloud.githubusercontent.com/assets/8551234/12158052/c9b41ae0-b4d6-11e5-8e14-cb54a8cbdb7c.JPG)
The renderer does not like it:
![screenshot_2016-01-07-00-33-29](https://cloud.githubusercontent.com/assets/8551234/12158065/ee9f1d8c-b4d6-11e5-8a66-0aac888dd39a.png)

**Comment by Zverik** [comment]
http://demo.f4map.com/#lat=48.1741965&lon=11.5523705&zoom=17
The tower is mapped like a big 291-meter roof. Maps.me does not support roof shapes at the moment, so it doesn't render the tower properly.

**Comment by utack** [comment]
Well, in the hope of helping you:
http://www.openstreetmap.org/?mlat=51.042167&mlon=13.708611&zoom=15#map=17/51.04257/13.70951
and
building=yes and height=* for the main building and the three towers is entered.
![screenshot_2016-01-07-22-00-13](https://cloud.githubusercontent.com/assets/8551234/12182743/6d6c0ff4-b58a-11e5-97ce-0eb71bac47ab.png)

**Comment by utack** [comment]
Nvm,new map data fixes it. Sorry for reporting
