### ISSUE TITLE
Build instructions outdated or incomplete

### ISSUE THREAD

**Issue by squatica** [mapsme/omim#12649]
I wanted to build the map generator tool according to these instructions: https://github.com/mapsme/omim/tree/master/tools/python/maps_generator
The step 1 refers to another set of instructions: https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#maps-generator however running just that command fails with `Could NOT find Boost`, `file STRINGS file "/maps/3party/boost/boost/version.hpp" cannot be read.` (the file is really missing), even though I have installed package libboost-all-dev (not mentioned in the instructions, unclear which version is needed).

I guess I also have to follow the instructions for building the desktop app, under https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#ubuntu-1604 but that results in error in the ./configure.sh step:
```
# ./configure.sh
Building Boost.Build engine with toolset ... tools/build/src/engine/###
### No toolset specified. Please use --toolset option.
###
### Known toolsets are: acc, borland, cc, como, clang, darwin, gcc, gcc-nocygwin, intel-darwin, intel-linux, intel-win32, kcc, kylix, metrowerks, mipspro, msvc, qcc, pathscale, pgi, sun, sunpro, tru64cxx, vacpp, xlcpp, vc7, vc8, vc9, vc10, vc11, vc12, vc14, vc141, vmsdecc
...
./configure.sh: 25: ./configure.sh: ./b2: not found
```
The same error happens even when I try things like `./configure.sh --toolset clang` or `./configure.sh --toolset=clang`
I have b2 executable in /usr/bin/b2

Again, nothing about b2 or toolset is mentioned in the instructions. It just says "You would need Cmake, Boost and Qt 5", which I think I have from running `apt-get install qtbase5-dev cmake clang libc++-dev libboost-iostreams-dev libglu1-mesa-dev libboost-all-dev`.

From some other experiments it seems that libsqlite3-dev is also required during `./tools/unix/build_omim.sh -crs generator_tool` (again not mentioned) but I cannot confirm that right now because of the previous errors.

**Comment by pshem** [comment]
Did you check out the repository with submodules? Boost and some other libraries are provided as git submodules, so a plain `git checkout` won't work. When cloning use `git clone --recurse-submodules`, and to check out submodules to an existing repository, run `git submodule update --init --recursive`
