### ISSUE TITLE
Routing along a road that crosses the border of .mwm files several times

### ISSUE THREAD

**Issue by Rikorose** [mapsme/omim#1265]
When maps.me tries to route along a road (highway) that crosses the border of a .mwm map file more then once, the routing engine does not use that highway a majority of the route. Instead the route uses small roads:

Correct route:
[map.project-osrm.org route](http://map.project-osrm.org/?z=11&center=48.023687%2C10.167503&loc=48.149767%2C10.115061&loc=47.883557%2C10.041236&hl=en&ly=&alt=&df=&srv=)

Maps.me route:
[Maps.me screenshot](https://drive.google.com/file/d/1UzPOB5SIiZX099vsxLE-mA36ozIjntADcA/view?usp=sharing)

This problem also occurs also when routing a longer distance along this road.

**Comment by deathbaba** [comment]
@gardster can you please check it out?

**Comment by gardster** [comment]
We are working on this problem, now. It will be fixed in future releases (with new mwm borders release).
