### ISSUE TITLE
rendering map is So slow in IOS.

### ISSUE THREAD

**Issue by rorents12** [mapsme/omim#13000]
On the market version Maps-Me application, it is fast to rendering the map.

but after cloning this git repository, and building ios Application, it is quite slow to rendering the map.

why does it have difference between market version and git repository?

**Comment by VMironiuk** [comment]
@rorents12 It depends on many factors: a device , build configurations etc.

**Comment by rorents12** [comment]
@VMironiuk Thanks for your answer!

So, isn't there any code difference between market version and ios branch?

**Comment by tatiana-yan** [comment]
The only code difference is private.h which contains our api keys for booking/pushes/other partners, routing coeffs for ETA calculation, etc. but not rendering params (see https://github.com/mapsme/omim/blob/master/private_default.h).

Maybe you build debug version which is much slower than release or compile project without optimisation?

**Comment by rorents12** [comment]
@tatiana-yan  Thanks for your answer!

I solved this problem with your answer. Just change build option to release from debug, problem solved. Thanks a lot!
