### ISSUE TITLE
Customizing MWM file. How to remove all pois?

### ISSUE THREAD

**Issue by rorents12** [mapsme/omim#13060]
Hi, I'm customizing MWM file. (file name is South Korea_North.)

I'm using generator_tool, and in 'Stage Features', there is method named

      ProcessorOsmElementsFromO5M::TryRead.

In this method, the tool generate element for mwm file I guess.

I injected custom element to this method, and succeed to add custom poi to mwm file. But the problem is, I can't remove pois already exist in mwm file.

I found that the mwm element has type. There are three type,

    Node, Way, Relation.

And they have some tag in them. But I can't find the rule for the tag of them. For example, some object is exist as node, but some exist ad Way, or Relation. 

Can i get some rule of this situation? Or is there any method to remove all pois? (I want to remove all road names, housenumbers too.)

**Comment by tatiana-yan** [comment]
https://wiki.openstreetmap.org/wiki/Map_Features

See "Element" column for geometry(node/way/relation) of the most common object types.
You can also see taginfo for types you are interested in. For example for restaurant:
https://taginfo.openstreetmap.org/tags/amenity=restaurant
you can see that there are 1 069 364 restaurants, 861 946 of them are mapped as nodes, 206 204 as ways, 1 214 as relations.

**Comment by tatiana-yan** [comment]
If you want to drop some objects or tags from input data you can also filter input file: https://wiki.openstreetmap.org/wiki/Osmfilter

**Comment by rorents12** [comment]
@tatiana-yan Thank you!

Your answer was a big help to me. Thanks!
