### ISSUE TITLE
Last Version Branch

### ISSUE THREAD

**Issue by RahmanFard** [mapsme/omim#1306]
Would you please tell me, Where is the last version(4.5.1) branch?

**Comment by deathbaba** [comment]
@yunikkk which branch was used for release?

**Comment by RahmanFard** [comment]
some of branches names as release same as "android-release-52".
Ok
Haw can i find source of the last confident version of mapsme?
As i know, you release 5.4.1 version.

**Comment by deathbaba** [comment]
You can try master branch, we usually keep it up to date.

**Comment by RahmanFard** [comment]
thanks.

**Comment by yunikkk** [comment]
Release was made from master branch. Commit is tagged with android-release-55 tag.

Commit hash is e1f6e5272a58275d7e3fced735147c0c87ceb642.

**Comment by yunikkk** [comment]
Stil it wasn't released on 100% of users, plan to do it tomorrow)
