### ISSUE TITLE
where is the code that parse poi data?

### ISSUE THREAD

**Issue by rorents12** [mapsme/omim#13098]
Hi, I'm trying to find the part of parsing poi(overlay) data in code.

The purpose is, to customize the poi(overlay) as my own logical information.

To achieve my purpose, I have some ways.

    1. inject poi data to mwm file, and customize search logic.
        In this way, I have to know how can I get the poi data from mwm file.

    2. remove all poi data from mwm file, and add the poi data in runtime.
        In this way, I will manage my own poi data in runtime. But to rendering
        the poi(overlay), I have to know where is the parsing part of poi data.

Both ways, I have to know where is the part to manage poi data. Is there any code to get all of poi data?

Or, can I use kml file for this purpose? If it is, how can I import the kml file?

**Comment by tatiana-yan** [comment]
you can add custom pois with https://github.com/mapsme/omim/blob/master/data/mixed_nodes.txt (see file history) -- pois will look like native map objects
and you can add tags to existing osm objets with https://github.com/mapsme/omim/blob/master/data/mixed_tags.txt

or you can import kml (just open it with maps.me) -- pois will look like bookmarks

**Comment by rorents12** [comment]
Thanks for your answer!

but I want to know how to parse the poi data, like name, type, location, ... etc in runtime.

Is there any method that get all poi information from mwm file?

**Comment by tatiana-yan** [comment]
You can see generator/osm2type.* and generator/osm2meta.* for generator runtime name/type/etc parsing code.

>and i can't understand what "import kml (just open it with maps.me)" means. Does it mean there is a function for opening kml in the applicaiton?

I use Android. To open kml with maps.me I just send it to phone (email/telegram/etc), than click to attachment and select maps.me to open. It's default os mechanism. We use default system mechanisms for Android and for iOS.

Dialog looks like this:
![Screenshot_20200519_113137_com huawei android internal app](https://user-images.githubusercontent.com/9213190/82303987-624bdc80-99c4-11ea-9190-1dcdf3c247f8.jpg)

**Comment by rorents12** [comment]
@tatiana-yan 
Thanks!
