### ISSUE TITLE
HTML descriptions in bookmarks are broken (iOS)

### ISSUE THREAD

**Issue by kennell** [mapsme/omim#13115]
In my KML files, i have bookmarks that include some HTML in the `<description>` tag.

Example:
```XML
<description>
<![CDATA[
<a href="https://www.example.com">Example</a>
]]>
</description>
```
 
With maps.me 9.6.1.0 (iOS), that link was rendered and was clickable and would open up in the web browser. With maps.me 10.0.3.0 (iOS), the links is still highlighted in blue, but it cannot be clicked anymore. Moreover, it is no longer possible to mark and copy any text from the description.

This may or may not be related to issue https://github.com/mapsme/omim/issues/12973 (altough that person is using Android, so i can't verify myself)

**Comment by firechhe** [comment]
Yes, I have made the same experience. I can't understand why mapsme has deactivated the HTML code for bookmark description.

It would be great to have this feature back with the next update.

**Comment by dzharkov** [comment]
Voting for the issue!
Placing links in placemarks description is very convenient when you creating your map of a city with external links.
The feature works well on Android, though

**Comment by kennell** [comment]
@dzharkov @firechhe For me it seems to be working again with the latest update

**Comment by dzharkov** [comment]
Yes, actually it does work for me now

**Comment by kennell** [comment]
Closing since it seems it was fixed
