### ISSUE TITLE
Maps not displayed anymore after I changed the storage location

### ISSUE THREAD

**Issue by Imarok** [mapsme/omim#13369]
Since I changed the map storage location in the settings in the menu "Save maps to" from `/storage/emulated/0` to the sdcard displaying maps is broken:
If I zoom in it just shows everything blank instead of the map. The world map is still displayed correctly when I zoom out.
I tried setting the storage location back to /storage/emulated/0, reinstalling the app and redownloading the map, but nothing helped.
I use Version 9.1.8-8.

**Comment by kristianlm** [comment]
I'm seeing the same behaviour here, also on (F-Droid's) 9.1.8-8. I don't believe I ever changed the storage location, though. And I had maps which were never updated and they still showed up.

Basically, nothing works now, except when I zoom far out.

Is it possible that the updated per-region map files use a format no longer supported by 9.1.8-8? Maps.Me og Google Play seems to be at version 10, perhaps a major update with breaking changes?

**Comment by burivuh** [comment]
Hi!

We do not support F-Droid's version.
