### ISSUE TITLE
Bookmark scrolling on iOS is broken

### ISSUE THREAD

**Issue by kennell** [mapsme/omim#13383]
In maps.me version `10.1.2.0` for iOS (tested on iPhone), only 5 lines of the bookmark description (`<description>`-tag in the KML file) are displayed. There is no option to expand the text, even if it is much longer. If one edits the bookmark text, it shows that all information is there, but after saving changes, again only 5 lines are displayed.

**Comment by burivuh** [comment]
Hi!

Actually this bug was resolved in the latest available 10.1.4 version.
Can you check it?

**Comment by kennell** [comment]
Can confirm, thanks
