### ISSUE TITLE
3D mode causing visual glitches

### ISSUE THREAD

**Issue by lbnpmxbe** [mapsme/omim#1343]
3D mode is unusable on 5.4.1 (SGS III running Cyanogenmod 12.1). I think the same as [this comment](https://github.com/mapsme/omim/issues/1238#issuecomment-169419543) which suggests it is occurring on more than one device.

**Comment by deathbaba** [comment]
Can you please provide more details and probably screenshots/video?

CC @rokuz

**Comment by lbnpmxbe** [comment]
As soon as I reach a zoom level which shows the 3D models, the image becomes corrupted. [Example location](http://osm.org/go/Zct2rVE1)

![screenshot_2016-01-12-17-01-01](https://cloud.githubusercontent.com/assets/16667350/12278488/5deb88de-b94f-11e5-8c19-49c4cd20dbb3.png)

![screenshot_2016-01-12-17-01-12](https://cloud.githubusercontent.com/assets/16667350/12278487/5deb6d72-b94f-11e5-97d5-bc5d881ca4ac.png)

The workaround is to disable 3D buildings in the settings.

**Comment by RicoElectrico** [comment]
@lbnpmxbe Nope. It didn't work at all, even when there were no 3D buildings on the screen, so there are glitches also when you zoom out to the world view.

**Comment by deathbaba** [comment]
Do you have any specific settings for OpenGL/GPU?

**Comment by rokuz** [comment]
@lbnpmxbe try to build application from master or download this version from my dropbox (https://www.dropbox.com/s/7sh750vmveqtpft/android-web-universal-release-5.5-160111.apk?dl=0) We've fixed this bug a couple days ago.

**Comment by lbnpmxbe** [comment]
@rokuz 
I'd rather wait until it is released in an [official](https://play.google.com/store/apps/details?id=com.mapswithme.maps.pro) [channel](https://maps.me/apk/), but thank you for the offer.

**Comment by lbnpmxbe** [comment]
Bug still present in 5.5 from Google Play.
