### ISSUE TITLE
[easy pick] main cities names are not displayed

### ISSUE THREAD

**Issue by brunetton** [mapsme/omim#13554]
Hi

I noticed that since the last update (that added the soooo wanted contour lines feature 🎉) the names of the "big" cities are not displayed anymore in big zoom levels. To show big cities names we've to zoom out, sometimes super far. 
This is quite weird, as big cities are great landmarks when looking to a map.

This problem seems a regression for me, as I didn't noticed this with previous versions. 

I speak of maps.me with many pant people around me, many of them have installed the app recently and many of them reported me this problem. I suppose this isn't hard to fix.

Here's some illustrated screenshots to illustrate this. 

This screenshots shows map around [Mons](https://www.openstreetmap.org/relation/1949374#map=10/50.4293/4.0050). Many little towns names are displayed, but the main one (Mons) is not:

![Screenshot_20200817_002845_com mapswithme maps pro](https://user-images.githubusercontent.com/86322/90345883-c95d4980-e024-11ea-8946-55675712cf18.jpg)

Zooming out (a lot!) still don't shows Mons name (at the bottom), and we can see the same problem with [Gand](https://www.openstreetmap.org/relation/897671) (at the top of the screen) 

![Screenshot_20200817_002907_com mapswithme maps pro](https://user-images.githubusercontent.com/86322/90345890-d712cf00-e024-11ea-8e1c-41c49b85f8f4.jpg)

Thanks

**Comment by danielmizrachi** [comment]
Emphatic +1, however I've noticed this issue for longer than just since the last update, and it's always been a pain point. A fix would be fantastic!

**Comment by thany** [comment]
Same goes for "primary" train stations.

**Comment by ForkWithMe** [comment]
Guys, we welcome constructive criticism, but haters are not welcomed here. In an ideal world all issues can be fixed at once, but we live in a real world. 

Please keep in mind that we have a commercial app. I guess not all of you folks have an idea how development of commercial apps work. We have thousands of "easy-to-fix" bugs, but we have other tasks and priorities as well. You can start fixing all the bugs individually, but soon you will run out of resources, since minor issues require money to fix, but they do not help to make money. And no one will work for free – our code is open and yet no one rush to help and fix bugs (cudos to those who actually helped to fix minor issues). Our resources have limit and we have to prioritise tasks and do the most critical issues first. 

Also, I like to mention that devs are not paid for that, yet many of them take the time to help other users who post issues and use our code in their projects for free.

**Comment by brunetton** [comment]
Hi @ForkWithMe 

I'm very surprised to read this ! 

First of all, I'm REALLY SORRY if my issue report can be read as hate 😢 I'm really in LOVE with Maps With Me, using it very often, recommending it to many many people.
I thought that taking some time to report some users feedback could be useful for dev team.

I'm also a free software dev, taking on my free time to make some open source projects to leave, and managing open source projects with contributors community for my job. So I know how commercial projects dev works, issues prioritization. But I'm also super sensitive to end user's experience.

Sorry if I didn't added enought "THanks for this wonderful work ! You app is a live saver for many of my friends, and my parents when they go to montain ! Especially since the super cool level curves function ! 😍" But I'm often super afraid of doing this "too hard".

> Guys, we welcome constructive criticism, but haters are not welcomed here. In a perfect world all issues can be fixed at once, but we live in a real world.
> 
> Please keep in mind that we have a commercial app. I guess not all of you folks have an idea how development of commercial apps work. We have thousands of "easy-to-fix" bugs, but we have other tasks and priorities as well. You can start fixing all the bugs individually, but soon you will run out of resources, since minor issues require money to fix, but they do not help to make money. And no one will work for free – our code is open and yet no one rush to help and fix bugs (cudos to those who actually helped to fix minor issues). Our resources have limit and we have to prioritize tasks and do the most critical issues first.
> 
> Also, I like to mention that devs are not paid for that, yet many of them take the time to help other users who post issues and use our code in their projects for free.

**Comment by brunetton** [comment]
Ow OK, answering to myself: I suppose you were not talking about my report, but a comment from this user that was not really constructive.

My bad, and sorry for the noise in that case 

![image](https://user-images.githubusercontent.com/86322/94315286-8460f700-ff82-11ea-95d3-a5eb1fde8d3c.png)

**Comment by thany** [comment]
> 
> 
> Guys, we welcome constructive criticism, but haters are not welcomed here. In a perfect world all issues can be fixed at once, but we live in a real world.
> 
> Please keep in mind that we have a commercial app. I guess not all of you folks have an idea how development of commercial apps work. We have thousands of "easy-to-fix" bugs, but we have other tasks and priorities as well. You can start fixing all the bugs individually, but soon you will run out of resources, since minor issues require money to fix, but they do not help to make money. And no one will work for free – our code is open and yet no one rush to help and fix bugs (cudos to those who actually helped to fix minor issues). Our resources have limit and we have to prioritise tasks and do the most critical issues first.
> 
> Also, I like to mention that devs are not paid for that, yet many of them take the time to help other users who post issues and use our code in their projects for free.

Don't delete my comment next time. Shutting someone up like that is a real arsehole move.

**Comment by ForkWithMe** [comment]
I will delete any comment that has no relation to a topic or expresses thoughts in a mean hateful manner. Haters are not welcomed here. 

Regarding this issue, we actually have it in our backlog. So, we hope to do something about it in the future. No time frame though as it all depends on available resources and other issues with a higher priority.

**Comment by brunetton** [comment]
Is your backlog public ? I didn't found it. 

I'm not sure this is a good idea to close an issue that represent an issue that is not resolved; if a contributor comes here and want to take some time to fix it, he'll see a closed issue so will think that the issue has already been fixed by someone, in a commit that will be merged to master soon, so "just wait and see". But the reality is that the issue has been moved to the team's internal backlog, but it'll maybe not be treated until a log time !

**Comment by brunetton** [comment]
## 🎉 Workaround found 🎉

For other users that came into the same issue, it's good to know that it have been fixed in **[Organic Maps](https://organicmaps.app/)** fork 🎉

![IMG_20210819_002906](https://user-images.githubusercontent.com/86322/129980492-eb0db6de-f200-4a40-b638-38ed4c803894.jpg)

**Comment by thany** [comment]
And also, why are the roads broken up? 🤨
