### ISSUE TITLE
[Question] Android build

### ISSUE THREAD

**Issue by 0wzZZzz6** [mapsme/omim#1356]
Error:(19, 0) Could not read script '/home/jan/Desktop/omim-master/android/secure.properties' as it does not exist.
<a href="openFile:/home/jan/Desktop/omim-master/android/build.gradle">Open File</a>

im trying to compile for the first time from master branch. how to resolve this kind of issue?

**Comment by deathbaba** [comment]
Please check out our documentation. Looks like you forgot to run configure script in the repo root.
