### ISSUE TITLE
Is it possible to add/show custom tile-layer over the map?

### ISSUE THREAD

**Issue by petyunchik** [mapsme/omim#136]
With OSM web-engine (leaflet) you can display any custom tile-layer on your map using url of the following format : 'http://{s}.tile.osm.org/{z}/{x}/{y}.png'
So, is there a way to do the same thing using maps.me engine?
TIA.

**Comment by Zverik** [comment]
Sorry, but no. MAPS.ME does not support raster tile layers, nor anything from the web.

**Comment by jancborchardt** [comment]
@Zverik is this planned in any way for the future, to support layers of any kind? Would be quite cool to have topographical maps, cycle maps, satellite maps etc.

**Comment by Zverik** [comment]
It isn't in the plan for the nearest half a year, but we may consider it for later. Cannot say anything more, sorry.

Or maybe somebody goes and pulls a request to do that :)

**Comment by jancborchardt** [comment]
Sure, I’m fine if you just focus to make the core map experience great. :)
