### ISSUE TITLE
Does Maps.Me consider "Bike Lanes" field when routing?

### ISSUE THREAD

**Issue by FinixFighter** [mapsme/omim#13671]
Hi! I just wanted to ask if Maps.Me does consider the "Bike Lanes" roads attribute when creating a route for bikes, or does it only consider the cycleways?
 It would be a big difference because some bike lane are just a painted line on the street; this means that they are mapped as an attribute of that road and not as a separated cycleway; so a lot of bike lanes would be missed if this field is not considered.

In the below image there's an example of a road with bike lanes included.
![Screenshot 2020-09-04 09:02:50](https://user-images.githubusercontent.com/19877271/92209579-88bb5800-ee8d-11ea-8753-cd5c2d4c2255.png)

**Comment by tatiana-yan** [comment]
Hello!
What exact tag do you mean? We consider 
cycleway right/left/opposite/opposite_lane and also consider local rules for highway access restrictions https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions

**Comment by FinixFighter** [comment]
> What exact tag do you mean? 
Ok, so you also consider "cycleway lane" right? From Wiki https://wiki.openstreetmap.org/wiki/Key:cycleway 
"cycleway=lane is used to tag two-way streets where there are cycle lanes on both sides of the road, or one-way streets where there is a lane operating in the direction of main traffic flow."

**Comment by FinixFighter** [comment]
> Hello!
> What exact tag do you mean? We consider
> cycleway right/left/opposite/opposite_lane and also consider local highway access restrictions https://wiki.openstreetmap.org/wiki/OSM_tags_for_routing/Access-Restrictions

**Comment by FinixFighter** [comment]
Sorry I closed this for error..

**Comment by tatiana-yan** [comment]
Now we set bicycle=yes for cycleway=lane but do not ignore oneway tag for bicycles. We will fix it, thank you!

**Comment by FinixFighter** [comment]
I'm glad to help! :)

**Comment by tatiana-yan** [comment]
Hello!
I looked at the code and at cycleway description (https://wiki.openstreetmap.org/wiki/Key:cycleway) again and I think that everything is already working correctly
Can you give examples of maps.me incorrect behaviour? I'll try to understand the reasons.

**Comment by FinixFighter** [comment]
Can't reproduce any error at the moment (maybe cause of the updates). So if you confirm that the app considers the tag "cycleway lane" too (other than cycleway right/left/opposite/opposite_lane) then we can close this. :)

**Comment by tatiana-yan** [comment]
Ok.
Anyway, thank you for report.
