### ISSUE TITLE
Please render the "lighthouse" polygon in addition to the "lighthouse" node

### ISSUE THREAD

**Issue by ThibaultMndr** [mapsme/omim#13812]
Maps.me currently only show the man_made="lighthouse" node, but does not display the man_made="lighthouse" building. 
Sometimes in OSM the lighthouse is represented more precisely with its polygon form, in this case it is not displayed at all on maps.me.

For example, look at the "phare des Baleines" on the French Ile de Ré, this main point of interest is missing on the application

**Comment by tatiana-yan** [comment]
Hello!
Can you provide any example?

It looks like everything is correct for `building = yes + man_made = lighthouse`:
https://www.openstreetmap.org/way/736657785
<img width="739" alt="Снимок экрана 2020-10-14 в 18 22 54" src="https://user-images.githubusercontent.com/9213190/96010558-97147080-0e4a-11eb-9a80-4eaa0906009b.png">

**Comment by ThibaultMndr** [comment]
The lighthouse "phare des baleines" is normally under the blue circle

https://www.openstreetmap.org/way/611318589

Perhaps because the attribute is building:part=yes instead of building=yes ?


![IMG_0043](https://user-images.githubusercontent.com/15212870/96029185-971c6c80-0e5a-11eb-9f7b-4a56c69b9b77.PNG)

**Comment by tatiana-yan** [comment]
Lighthouse object exists in map but its icon is displaced by other icons. For example, you can search 'lighthouse': 
![Screenshot_20201015_103236_com mapswithme maps pro](https://user-images.githubusercontent.com/9213190/96091378-2fa20380-0ed2-11eb-8bf5-6420ea7ad369.jpg)

Viewpoint icon and lighthouse icon are at the same place and app can not display both icons.

**Comment by ThibaultMndr** [comment]
Ahhhh ok ! The survey point was duplicated three times (stacked), and one of its occurrence had the attribute "viewpoint". I removed duplicates and added a true viewpoint mark slightly misaligned, so I hope it won't overlap
