### ISSUE TITLE
MAPS.ME API

### ISSUE THREAD

**Issue by 0wzZZzz6** [mapsme/omim#1386]
passing a single point does not have a title in the toolbar.

**Comment by deathbaba** [comment]
Is it iOS or Android? Which OS version are you playing with?

**Comment by 0wzZZzz6** [comment]
Android Sir.

**Comment by deathbaba** [comment]
I just checked with our guides from http://guidewithme.com/ and I see toolbar on my Android device.
Are you using Google Play store MAPS.ME version?

**Comment by 0wzZZzz6** [comment]
I mean when passing a single point as expected the name of the place should be in the toolbar.
example MapsWithMeApi.showPointOnMap(this, 8.159801, 125.123242, "sample name");

sample name should be in the toolbar, but it does not show anything.

**Comment by deathbaba** [comment]
It’s not in toolbar any more, please check Place Page part in the bottom - all information + back button should be there.

**Comment by 0wzZZzz6** [comment]
ahh  I see. thanks sir. I thought that it would be the same when passing multiple points
