### ISSUE TITLE
App is super slow and not usable after big update on iOS

### ISSUE THREAD

**Issue by komape** [mapsme/omim#14072]
Just updated to version 11.0.0. Since then the app is very slow. After launch it takes a couple of secods (~20 secods) before I can tap on any button or drag the map. Seems like the app is not responding to any user interaction in this time. 

Once the app starts reacting to user interactions it happens over and over again that the app is not responding to interactions. Sometimes it's crashing completely.

maps.me version: 11.0.0
iOS version: 14.3
iPhone model: iPhone SE 2nd & iPhone 12

**Comment by KAMiKAZOW** [comment]
As you saw yourself in #14073, the updated version from the app store is unrelated to his project. This bug report does not apply to the version in question and therefore should be closed.

**Comment by StewAlexander-com** [comment]
Dataset move to MapBox away from OpenStreetMaps in Maps.Me 2.0 is an utter joke,  so much data lost, so much slower 

The issues seem are due this stupidity

**Comment by komape** [comment]
@StewAlexander-com bu how does it come then that on Android the app it still the same? they take the same cut on payments as Apple does

**Comment by StewAlexander-com** [comment]
They did sell it off
