### ISSUE TITLE
Please update your app Review

### ISSUE THREAD

**Issue by StewAlexander-com** [mapsme/omim#14077]
… Please ignore previous comment 

But updating your app review may be worthwhile

**Comment by habi** [comment]
I don't it is necessary to dox persons here, even if you're angry.
I think the app is a joke now, too, but this is unnecessary.

**Comment by StewAlexander-com** [comment]
Good point

**Comment by StewAlexander-com** [comment]
Unfortunately cannot close open issues I create on GitHub for iOS
