### ISSUE TITLE
Maps.me sale to a payment processor removed OpenStreetMap 

### ISSUE THREAD

**Issue by StewAlexander-com** [mapsme/omim#14076]
Sale to http://parity.com moved app away from a working navigational tool to a payment processing application with little to do with the previous functionality

**Comment by StewAlexander-com** [comment]
Appears they sold the app out ugh

**Comment by resynth1943** [comment]
Will the app stay open-source?

**Comment by StewAlexander-com** [comment]
Unsure

**Comment by StewAlexander-com** [comment]
They however are responsive on Twitter

**Comment by StewAlexander-com** [comment]
Well they added back OpenStreetMaps... unknown if they are still doing anything with GitHub

**Comment by resynth1943** [comment]
Do they have an email I can contact, by any chance?

**Comment by Seandebasti** [comment]
> Do they have an email I can contact, by any chance?

you can check the people in the whitepaper https://de.mapsme.parity.digital/token/MAPS.pdf
[MAPS Whitepaper.pdf](https://github.com/mapsme/omim/files/5893910/MAPS.1.pdf)

**Comment by Seandebasti** [comment]
> Well they added back OpenStreetMaps... unknown if they are still doing anything with GitHub

Is there still any updates? I just found some mentions about this question in telegram group and channel https://telegra.ph/What-happened-to-the-old-MAPSME-12-20

**Comment by StewAlexander-com** [comment]
Maps.Me has updated their app a few times, at least for iOS here in the USA... 

But please see issue #14157, I'm fairly certain this is repo is defunct

**Comment by StewAlexander-com** [comment]
Closing as no longer maintained
