### ISSUE TITLE
App crashes after big update on iOS

### ISSUE THREAD

**Issue by komape** [mapsme/omim#14071]
Just updated to version 11.0.0. After launching the app a popup appears which asks to download the map for my current location. It has two buttons: 'Download' and 'Download later'. Both show now reaction on tap and the popup cannot be dismissed. After a couple of seconds the app crashes completely. App cannot be usd wnymore at all ☹️

![image](https://user-images.githubusercontent.com/25869589/102692608-b3e76e80-4214-11eb-9b44-cff25ae0eff9.png)

iOS Version: 14.3
iPhone model: iPhone SE 2nd

**Comment by KAMiKAZOW** [comment]
As you saw yourself in #14073, the updated version from the app store is unrelated to his project. This bug report does not apply to the version in question and therefore should be closed.

**Comment by StewAlexander-com** [comment]
The iOS app no longer is Maps.Me

It's now a Payment processing app disguised as a navigational app 

Why the issue, if I can be of help bringing back / reverse engineering the old Maps.Me please let me know
