### ISSUE TITLE
Release armv8 version

### ISSUE THREAD

**Issue by utack** [mapsme/omim#1410]
armv8 is now in all high end phones and starting to reach more and more mid and low end devices.
Maybe you could release a extra version for it, if it helps performance.

**Comment by deathbaba** [comment]
Have you already checked/profiled that code performance is better?

**Comment by utack** [comment]
Have to admit I am neither capable of compiling or profiling apps on Android, but I hope compilers can be trusted to generate a bit faster version with armv8?

**Comment by deathbaba** [comment]
Simple “let’s add one more platform” approach will slow down android project compilation time by 1/3. And will increase universal APK size by 4-8 MB.
There should be a good reason to do it.

**Comment by deathbaba** [comment]
But of course you can try do do it yourself, share your results, and submit a patch!

Files to check out are: android/jni/*.mk, tools/mkspecs/android-c++/* and tools/autobuild/android.sh

**Comment by utack** [comment]
Makes sense, I just wanted to hear your thoughts about it, maybe you can put it on a future todo list when there is time for these smaller things.
If i have one od these times I will try to compile it and report about it

**Comment by naoliv** [comment]
> And will increase universal APK size by 4-8 MB.

Isn't it possible to distribute APKs based on the target arch?

**Comment by deathbaba** [comment]
Only for Google Play.

How many devices are running this arch now?

**Comment by utack** [comment]
New phones are fast enough..so actually more effort than is worth i guess
