### ISSUE TITLE
Is Maps.Me still an OpenSource package?

### ISSUE THREAD

**Issue by StewAlexander-com** [mapsme/omim#14157]
I know Maps.Me was recently purchased by an international money exchange company based in Korea...

So, is this still being actively tracked by said company, or is this repo now defunct?

**Comment by dbf256** [comment]
New versions of mapsme are not build from this repo anymore, so I think that it is not tracked.

**Comment by j5k** [comment]
See the Organic Maps project. A privacy focused fork.

**Comment by StewAlexander-com** [comment]
For those interested in a nice open source navigation tool, see here:

https://organicmaps.app/

**Comment by StewAlexander-com** [comment]
MapsMe seems to be closed source now, closing
