### ISSUE TITLE
Search intent on iOS app shows broken UI

### ISSUE THREAD

**Issue by memoriasIT** [mapsme/omim#14193]
Good day, I am trying to open the following intent on iOS:
'mapsme:///search?query=$query&map'

But the UI seems to get broken right after it. The search element also seems outdated, maybe it's a part that was forgotten in 
refactoring. Here is a video about it:
https://www.youtube.com/shorts/a3en7dlThEI?feature=share

**Comment by TheAdventurer64** [comment]
Hey there, this repository is currently inactive. If you would like to contribute to the open source fork of this project,(For context, MAPS.ME [was made closed sourced a while ago](https://telegra.ph/What-happened-to-the-old-MAPSME-12-20)), please see [Organic Maps](https://github.com/OrganicMaps/OrganicMaps).

**Comment by memoriasIT** [comment]
Oh that's really a shame, even if I contributed to the project the bug would still be present in the store app so it wouldn't fix my problem. Nice that at least this project continued as open source!
