### ISSUE TITLE
amenity=nightclub not represented as an icon in Maps.me

### ISSUE THREAD

**Issue by racoq** [mapsme/omim#142]
Hello

One of the latest updates to the default  Mapnik style of OSM was to popular request to add an icon to the POI representing night clubs (amenity=nightclub)

As far as i know, previous versions of Maps.me already supported this and represented amenity=nightclub with the same icon as amenity=bar which might not be ideal (night clubs and bars are not the same in real life) but for me it was totally acceptable. However, in the latest updates of Maps.me all the POI tagged as amenity=nightclub are iconless. 

Please add the same icon of amenity=bar to all the POIs tagged with amenity=nightclub or add a new and distinctive icon to it, if possible in the next update ;)

**Comment by utack** [comment]
Well it does have a drink icon now:
![symbols2](https://cloud.githubusercontent.com/assets/8551234/12222022/72efe2da-b7af-11e5-9d98-2c0fba1a4704.png)

**Comment by deathbaba** [comment]
Can we close this issue now?

**Comment by racoq** [comment]
Yes, this issue was corrected in one of the updates as @utack
