### ISSUE TITLE
Some maps not showing any detail when zooming in on iPhone

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#1472]
Hi,

I have just downloaded/installed the latest version 5.4 from the app store, I have downloaded 2 maps UK_England & UK_Wales with and without routing but neither show any detail when I zoom in, here is a screen shot of the initial map before zooming in showing some detail (note I have also imported a KML route):-
![img_2566](https://cloud.githubusercontent.com/assets/15140454/12414254/36197f68-be8c-11e5-89e8-eb796159dbb4.png)

However when I zoom in I get:-
![img_2564](https://cloud.githubusercontent.com/assets/15140454/12414301/9d76c8d2-be8c-11e5-9a58-ee2c3200b58a.png)

I have downloaded a map from France_Nord-Pas-de-Calais and UK_Northern Ireland and they both work OK with full zoom, so are the two maps that fail out of date with this latest app release ?. I have tried to delete the 2 maps via the menu option but nothing happens ?.
I do not get any errors whilst downloading the maps.

iPhone 5c, OS version is 7.0

Many Thanks.

**Comment by ForkWithMe** [comment]
Hi! We have no issues with the maps. How did you download the maps: directly via the app or via computer? When you press Delete map, nothing is happens, right? Did you tried to close MAPS.ME and restart iPhone?

**Comment by stevegdavis** [comment]
Hi,
I have just upgraded my phone to OS 9 and re-installed the app and maps and all works OK, can zoom just fine.
Thanks.
