### ISSUE TITLE
which way did omim use for http connection for Android platform

### ISSUE THREAD

**Issue by BruceVan1987** [mapsme/omim#1519]
Hello,

I noticed in /omim/platform/  there are different files for http_request of different platform,
 like:
http_request.cpp 	
http_request.hpp 	

for iOS , there are:
	http_thread_apple.h 	
	http_thread_apple.mm 	

that make me confused because I didn't see any for Android platform. Could you give me a hint about how did omim handle http request for ndk (Android) ?

**Comment by deathbaba** [comment]
Please check out omim/android/jni/com/mapswithme/platform/HttpThread.cpp

**Comment by BruceVan1987** [comment]
thx :+1:
