### ISSUE TITLE
Map opened from shared pin link should be centered on pin

### ISSUE THREAD

**Issue by claudiush** [mapsme/omim#1575]
**How to reproduce:**
- Receive a shared pin on email and click the _"Click this link ... to see the place on the map"_ HTTP link. Example: http://ge0.me/44yHBwHipU/Reval (This should open a pin centered on the Estonian capital)
- Confirm to open the link in the MAPS.ME app

**Result**
Pin is opened and selected but the map still shows the location it was last left in :cry: 

**Expected Result**
Follow a link to a shared pin the map in the app should be centered on it :round_pushpin: 

Reproduced in version 5.4 for iOS

**Comment by deathbaba** [comment]
Hi, this is a known bug and it is already fixed in the master branch. Please wait for app update.
CC @AlexanderMatveenko

**Comment by utack** [comment]
I guess this can be closed?

**Comment by claudiush** [comment]
Verified to be OK in 7.0.5-Google
