### ISSUE TITLE
3D View - Building Levels for Height

### ISSUE THREAD

**Issue by abellao** [mapsme/omim#1576]
Currently, the 3D buildings use the ```height``` value for the rendering.

Oftentimes, finding the real height of a building is harder than finding the number of levels.

Could we use the ```building:levels ``` value, along with ```height```, for rendering the 3D buildings?

Thanks

**Comment by deathbaba** [comment]
It is already used. Multiplied by 3 to get meters.

**Comment by abellao** [comment]
You are correct, I can't believe I didn't notice.

Thanks for the great work!
