### ISSUE TITLE
Maps not downloading

### ISSUE THREAD

**Issue by andreytecho** [mapsme/omim#1588]
Last Android build couldn't download maps.
Project without any changes (git clone; ./configure, set_up_android.py; ./gradlew clean assembleWebRelease).
Checked on x86 (Genymotion, Linux Mint 17.2) and device (Sony Xperia Acro S, Android 5.1.1).
Logcat:
"01-25 09:20:49.185 31547-31640/com.mapswithme.maps.pro D/DownloadChunkTask: Invalid url: 
01-25 09:20:49.189 31547-31547/com.mapswithme.maps.pro W/MapsWithMe_JNI: platform/http_request.cpp:104 OnFinish()  HttpRequest error: -2
01-25 09:20:49.189 31547-31547/com.mapswithme.maps.pro E/MapsWithMe_JNI: platform/servers_list.cpp:30 ParseServerList()  Can't parse server list json: 1 '[' or '{' expected near end of file 
01-25 09:20:49.189 31547-31547/com.mapswithme.maps.pro W/MapsWithMe_JNI: platform/servers_list.cpp:44 GetServerListFromRequest()  Can't get servers list from request, using default servers: [0: ]"

**Comment by deathbaba** [comment]
It’s correct: we don’t publicly share our servers with maps. You should use your own servers or download maps manually. Please check documentation.

**Comment by andreytecho** [comment]
Sorry for my inattention.
