### ISSUE TITLE
Compilation failed on ubuntu 15.10 with clang 3.5

### ISSUE THREAD

**Issue by pastukhov** [mapsme/omim#172]
When i'm following https://github.com/mapsme/omim/blob/master/docs/INSTALL.md i'm getting:
http://pastebin.com/XWyhh8SH

**Comment by syershov** [comment]
Do you have installed libc++ ? Not libstdc++.

**Comment by deathbaba** [comment]
Please try
```
qmake omim.pro -spec linux-clang-libc++ CONFIG+=debug
```
