### ISSUE TITLE
Support "wifi" keys

### ISSUE THREAD

**Issue by utack** [mapsme/omim#1740]
Even if not defined in OSM wiki, the key "wifi=*" is very widely used, on over 10.000 objects:
[https://taginfo.openstreetmap.org/keys/wifi](https://taginfo.openstreetmap.org/keys/wifi)
The app does not seem to show places with wifi=yes, when searching for "WiFi" category at the moment.

**Comment by deathbaba** [comment]
Why not to replace not defined wifi=* with well defined tag? It will work everywhere automagically.

**Comment by utack** [comment]
I was planning on discussing this on the OSM mailing list.
But if 10.000 points are in the database currently, it is likely a continuous flow of new "wifi=*" places will be added in the future

**Comment by deathbaba** [comment]
If we start support non official tags, they become even more used everywhere :) What is wrong with bulk replace once for every few months?

**Comment by utack** [comment]
The OSM community is very allergic to bulk replacements, because they sometimes unexpectedly break stuff
But as I said, I will ask on the mailing list if this is ok to do.

**Comment by utack** [comment]
Sorry to ask about this again  
The number if wifi tags is still enourmous, automated edits are risky  
For the usability of the application, couldn't you consider parsing wifi=yes and wifi=free maybe?

**Comment by deathbaba** [comment]
Have you asked in a mailing list? It is the right way to go with bulk conversion (at least for most popular values).
CC @Zverik

**Comment by utack** [comment]
Not yet  
tbh I am a bit scared about automated edits of this scale, you'd need some reaaaly good logic to convert all the keys without errors

**Comment by deathbaba** [comment]
You can start by converting not all but clearly good cases.

**Comment by utack** [comment]
Ok i took your advice, request about it is in the OSM talk list  
Maybe this can be done, 10.000 objects is a lot, but if a good automated edit gets 3/4 it is doable

**Comment by Zverik** [comment]
Will be fixed in the next release. See #5157.

**Comment by utack** [comment]
Thanks. The discussion on the mailing list is also going on, eventually all wifi keys will be converted, but not that quickly
