### ISSUE TITLE
remove dots from buildings without house number in feature styler

### ISSUE THREAD

**Issue by dsmelov** [mapsme/omim#181]
Possible fix:

      // Mark houses without names/numbers so user can select them by single tap.
      if (houseNumber.empty() && m_primaryText.empty())
        houseNumber = " ";

User still be able to select such buildings (tested).

**Comment by deathbaba** [comment]
Thanks for suggestion!

If you remove dots, another problem arises: how to select non-square or very big house? Where should user touch to select it?
And the importance of building selection will increase when we finish our map/address editor.

**Comment by ilatypov** [comment]
Not sure if my issue relates to this, but searching for "4 Hughson Street South" in the Ontario map shows 2 locations in Hamilton. I guess it' because one of the buildings has a number (5) from the crossing street.

**Comment by rokuz** [comment]
Implemented
