### ISSUE TITLE
Feature request: Add Google Places integration 

### ISSUE THREAD

**Issue by nikolowry** [mapsme/omim#187]
It would be awesome if there was an optional setting to enable Google Places integration.  

The current search is severely lacking in relevant meta information (NYC) and incorpating Google's API would fill the void for any lacking contextual information.

If this is feasible, I'd suggest defaulting it to disabled and running any API requests through an  anonymizing proxy. 

---

Sorry if this is not the proper place for feature  requests - feel free to link me there and close this  issue

**Comment by abellaofernandez** [comment]
Although that would be nice feature, using the Google Places API requires an API Key and has a limited free quota per account.

The limit for free usage is 150,000 requests per 24 hour period.

**Comment by nikolowry** [comment]
Is there anyway to generate those keys on a per user basis randomly?

Or maybe enabling the feature requires the user to use Google's oauth2 - therefore eliminating any "questionable" workarounds?

**Comment by abellaofernandez** [comment]
Since keys are attached to Google accounts, each user would need to provide their own.
OAuth is an option, albeit hard to setup for normal users that do not have a Google account.

Another option is for Mail.Ru Group (MAPS.ME parent company) to foot the bill for an API Key.

**Comment by deathbaba** [comment]
No, we can not mix Google Play services with our maps. It's forbidden by Google's agreement.

**Comment by deathbaba** [comment]
Best long-term solution is to make OSM data rich and detailed. And we're already working on it.
