### ISSUE TITLE
Navigation with Android Text-to-Speech (TTS)

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#1882]
Android does natively support TTS, so I'd like to suggest to use this TTS provider for the navigation.
This would also make it possible to say the street names or similar things instead of the usual "general" text.

**Comment by deathbaba** [comment]
We are already using it.

**Comment by rugk** [comment]
Okay, did not noticed this... :smile: 

In this case take this as a suggestion to make the sound output more flexible, e.g. include the street names in the sound output.

**Comment by deathbaba** [comment]
It’s in our plans, thanks.

**Comment by rugk** [comment]
So can you please reopen this issue until it is implemented? So we can track the status of this and no new issues with the same request are opened accidentially.

**Comment by deathbaba** [comment]
Unfortunately, we don't sync all our todos with issues on github now.

**Comment by fosskers** [comment]
I really miss not hearing the street names called out as I drive. Example:

> Maps.me: In 500 metres, turn right.
> Me: Onto...?

It's important for syncing with the internal map in my head, too.
