### ISSUE TITLE
[Bug] Map disappear after calculating route

### ISSUE THREAD

**Issue by ignaciolep** [mapsme/omim#1886]
The map area goes blank (black) after calculating route

**Comment by ignaciolep** [comment]
![tmp_10235-capture _2016-02-10-23-11-28768533730](https://cloud.githubusercontent.com/assets/13091755/12968213/9097623e-d04d-11e5-95f8-29c1e81896a5.png)

**Comment by deathbaba** [comment]
Which device and android version do you have?

**Comment by ignaciolep** [comment]
LG G4 (H815)
Android 6.0

**Comment by deathbaba** [comment]
@rokuz @darina can you please check it out?

**Comment by rokuz** [comment]
We'll plan the investigation.

**Comment by ignaciolep** [comment]
Same issue with Maps.Me 5.6.4-Google

**Comment by rokuz** [comment]
Fixed
