### ISSUE TITLE
Extra step needed to go to real settings

### ISSUE THREAD

**Issue by jancborchardt** [mapsme/omim#189]
To go to the settings, one first has to open the bottom menu and go to »Settings« and then in that view go to »Settings« again. This is quite confusing and introduces another view. Especially for the only 5 opions this does not seem necessary.

Instead the settings should directly be shown in the first settings screen, with the rest (Help, File a bug, About, etc) below it.

**Comment by trashkalmar** [comment]
Reworked settings were merged into master and will appear in the next release.

**Comment by jancborchardt** [comment]
Great stuff, thank you!
