### ISSUE TITLE
Tap-and-move gesture to zoom

### ISSUE THREAD

**Issue by jancborchardt** [mapsme/omim#190]
Google Maps has a great gesture for zooming with one hand. Tap, and then tap-move down to zoom in, and tap-move up to zoom out. This is very good for one-hand usage.

Would be cool if Maps.me had that as well since it’s a way faster solution than the +/- zoom buttons on the screen for people who know how to do it, especially because it works anywhere you touch.

**Comment by therearesomewhocallmetim** [comment]
Hi, Jan-Christoph,

This feature is currently available on iOS (tap on either + or - and move your finger up or down). We will add it in Android some time later.

Best regards,
Timofey

**Comment by jancborchardt** [comment]
Sweet, thanks!

**Comment by rokuz** [comment]
Implemented two taps + move

**Comment by jancborchardt** [comment]
@rokuz wow, this is so awesome! :) Opened a slight enhancement issue at https://github.com/mapsme/omim/issues/3700
