### ISSUE TITLE
[Feature request] Disable inertial scrolling in settings

### ISSUE THREAD

**Issue by redmanmale** [mapsme/omim#1903]
I suggest to add preference in settings to use or not to use inertial scrolling.
Can it be done?

**Comment by deathbaba** [comment]
Can you please give more details, what is wrong with current implementation?

**Comment by redmanmale** [comment]
It's complicated to explain, but I'll try.
It's about accuracy. If I move map from center to one of the screen edges and don't release finger from screen map often slips back instantly. And I have to move several times if I want to look at some area precisely.

If you don't get it I'll try to make a short video or gif animation of the process.

**Comment by deathbaba** [comment]
It would be awesome to see the issue on a video, thanks!

**Comment by redmanmale** [comment]
Sorry for bothering, it's likely hardware problem with my touch screen since I couldn't reproduce it anywhere else.
