### ISSUE TITLE
Build maps error

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#1942]
error occured while run “CONFIG=gtool omim/tools/unix/build_omim.sh -cro”

![image](https://cloud.githubusercontent.com/assets/11851006/13107092/f29d70e6-d5a6-11e5-983e-0fe2a0200783.png)

OS:Ubuntu 14.04

**Comment by deathbaba** [comment]
Which version of clang are you using? Does it match one mentioned in our documentation?

**Comment by xingdavis** [comment]
@deathbaba Clang version is 3.5, Replaced version 3.6 can be passed.
