### ISSUE TITLE
PBF to MWM error

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#1960]
Having built a generator tool,When I want to convert PBF to MWM
"omim/tools/unix/generate_mwm.sh source.pbf"
there is an exception.
![image](https://cloud.githubusercontent.com/assets/11851006/13168467/ed4df3d2-d717-11e5-9cb3-0f2f9fbc4087.png)

**Comment by deathbaba** [comment]
Can you please try to revert this commit and try again? https://github.com/stangls/omim/commit/5c3bae20e2eaf32655ee8ddbb27822e8b268cbb5
