### ISSUE TITLE
Strange map display issue

### ISSUE THREAD

**Issue by jeffrey-friedl** [mapsme/omim#1987]
At location
   41.078313, -81.500011
is an intersection. The main street running east-west ("East Market Street") is essentially straight, and it appears this way properly on Open Street Map
   http://www.openstreetmap.org/search?query=41.078313%2C-81.500011#map=19/41.07833/-81.49975

However, when viewed in the iOS maps.me app, the main road appears to jump, as shown in the attached iPhone screenshot.

iPhone 6+ running iOS 9.2.1, maps.me app version 5.5, and the most recent map (with driving directions).

![file feb 21 1 14 31 pm](https://cloud.githubusercontent.com/assets/16525084/13204395/177e966c-d89d-11e5-84fa-9c03465105f1.png)

**Comment by deathbaba** [comment]
This node was edited right after we generated maps data for current market release http://www.openstreetmap.org/node/230039427

**Comment by jeffrey-friedl** [comment]
Oh, wow, sorry for not noticing. Good to hear it's not a bug.
