### ISSUE TITLE
iOS Runtime error

### ISSUE THREAD

**Issue by rahul606** [mapsme/omim#1990]
After setting up the project as per the stated steps for iOS in XCODE 7 I am facing this error on runtime 

**Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: ''applicationId' should not be nil.'**

**Comment by deathbaba** [comment]
Can you please try to apply a patch from #1991 and try again?

**Comment by rahul606** [comment]
@deathbaba thx man for the quick fix. It perfectly works.
