### ISSUE TITLE
3D Building Color

### ISSUE THREAD

**Issue by abellao** [mapsme/omim#2030]
Is it possible to have the 3D buildings render the `building:colour` and `roof:colour` properties?

Here is an example of how it can look:
[OSM Buildings](http://osmbuildings.org/?lat=52.52025&lon=13.41089&zoom=16.6&rotation=0&tilt=30)

It is a great aid in navigating cities with many buildings.

**Comment by deathbaba** [comment]
How do color help you to navigate? Every osm mapper puts it's own "best" color for buildings, and map become a rainbow.
