### ISSUE TITLE
[Q] Always got the warning with: MapResource() Glyphs packer could not pack a glyph

### ISSUE THREAD

**Issue by SandyChanF** [mapsme/omim#2083]
Always got the warning:

LOG TID(2) WARNING   92.0196 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 28879
LOG TID(2) WARNING   92.0473 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 30430
LOG TID(2) WARNING   92.0526 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 29128
LOG TID(2) WARNING   92.0558 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 30430
LOG TID(2) WARNING   92.0748 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 29128
LOG TID(2) WARNING   92.1117 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 22993
LOG TID(2) WARNING   92.1166 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 33686
LOG TID(2) WARNING   92.1673 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 22993
LOG TID(2) WARNING   92.1821 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 22993
LOG TID(2) WARNING   92.1888 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 28879
LOG TID(2) WARNING   92.1978 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 34388
LOG TID(2) WARNING   92.2045 drape/font_texture.cpp:187 MapResource() Glyphs packer could not pack a glyph 32650

**Comment by deathbaba** [comment]
Can you please share a log of fonts initialization before this warning?

CC @rokuz

**Comment by rokuz** [comment]
Hi! Do you use build the app by yourself? Do you have any modifications in the code?
This warning may happen if you use special fonts which cannot be processed by FreeType (or our app) properly. Could you share full log?

**Comment by rokuz** [comment]
Bug fixed in master
