### ISSUE TITLE
Specify both endpoints when calculating route

### ISSUE THREAD

**Issue by citizenmatt** [mapsme/omim#233]
Unless I'm missing something, when calculating a route, it's always from the current location to a selected endpoint. Sometimes it's useful to calculate a route without actually being in that location (to see how long the journey would take, etc). Can we specify the start as well as the endpoint?

**Comment by deathbaba** [comment]
Thanks, we're already working on it :)

**Comment by utack** [comment]
Agree, this is very useful

**Comment by trashkalmar** [comment]
Implemented in version 5.2
