### ISSUE TITLE
Generate routing for single country

### ISSUE THREAD

**Issue by Totor2015** [mapsme/omim#2361]
Hi,
I would like to generate an updated map for the Philippines only, and managed to do so.
Unfortunately no routing map is created. 
It looks like this is only available when generating the whole planet.
I would like to avoid downloading 30Gb to just update one country.
Is there a way to generate a map with  routing for just one country (geofabrik download) ?

Regards,

Totor

**Comment by deathbaba** [comment]
CC @gardster

**Comment by gardster** [comment]
Hi. You need to run the generate_mwm.sh script with the third parameter - path to osrm .lua routing profile (profile.lua inside 3party/osrm/osrm-backend/)

**Comment by Totor2015** [comment]
Hi, 
Thanks,
In fact MAPS.md inside the docs folder explains it clearly...
