### ISSUE TITLE
Update maps at a regular time between releases?

### ISSUE THREAD

**Issue by Codain** [mapsme/omim#2461]
OSM data are moving at a high pace and MWM files are updated at a Maps.me release pace. As a frequent flyer and OSM contribuer I can feel this delay.

I read that a new release (and so maps) is coming soon. But between the releases, can you imagine a monthly based update of the maps? The script associated to the latest release may be scheduled to be automatically called or it can be a manual launch. Looking at other apps that promise updates (but with huge delay between) it would be a great asset for this one to rely on fresh data.

I know the script can be launched on my side but it requests time and skills I don't have.

Thank you!

**Comment by deathbaba** [comment]
We can, and it's in our plans. Usually we release updates at least monthly, but now due to some management issues these updates were delayed until new upcoming release.

CC @burivuh
