### ISSUE TITLE
Missing road numbers

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#253]
I have noticed that since updating to the latest Android app version and maps versions that some of the minor road numbers are now missing. I have taken 2 screen shots of the same area on a map (England) that clearly show the missing road number (B4070), the 1st screenshot is taken from a Sony Experia running  version 4.4.2-Google that clearly shows the road number 
![screenshot_2015-10-15-11-48-07](https://cloud.githubusercontent.com/assets/15140454/10512033/62778f5c-7335-11e5-8b81-6e2e2ca303d4.png)

and the 2nd screenshot taken from an HTC 1 running version  5.1.4-Google but the road number B4070 is missing. 
![screenshot_2015-10-15-11-46-03](https://cloud.githubusercontent.com/assets/15140454/10512046/7a76fb88-7335-11e5-83d4-bdd85a6ac181.png)

I have noticed this on other maps eg. France where some of the minor D road numbers are also missing in version 5.1.4 but are visible in 4.2.2

This shows that the road numbers have been "deprecated" since 4.2.2, why is this ?.
Also typing ?oldstyle makes no difference, the minor road colours change OK but the road numbers still missing.

**Comment by stevegdavis** [comment]
Fixed in 5.1.7 just released. I think the problem was (partly ?) in file:-
omim-master\data\styles\legacy\include\base_roads.mapcss

**Comment by deathbaba** [comment]
Yes, it was style migration error. Should we close the issue?

**Comment by stevegdavis** [comment]
Yes please
