### ISSUE TITLE
Update APK and maps hosted on website more frequently

### ISSUE THREAD

**Issue by twzkxkan** [mapsme/omim#264]
[APK](https://maps.me/apk/) and [maps](http://direct.mapswithme.com/direct/latest/) are not updated as frequently as other sources, could this be improved?

**Comment by deathbaba** [comment]
@AlexanderMatveenko can we handle it?

**Comment by Zverik** [comment]
We have unofficial [daily builds](http://osmz.ru/mwm/) and [daily maps](http://eu1.mapswithme.com/direct/daily/) (which can disappear at any moment, but for now they are active).

For official builds, this hardly can be improved, because everyone here can build an apk with a single command, and for now updating maps more often is not needed.

**Comment by deathbaba** [comment]
@Zverik we have an official link on our site's download page to apk builds. And it's important to upload them there.

**Comment by twzkxkan** [comment]
Yes, this is the official link right? https://maps.me/apk/

Will you continue to support it by publishing stable builds? The most recent build you offer is 5.0.3 and incompatible with recent map files.

**Comment by twzkxkan** [comment]
Thanks for the update! As an OSM contributor, it's awesome to see you make our data look so good. You've inspired me to do a survey today!

**Comment by Mesgary** [comment]
How can I use your daily map on iPhone?

**Comment by deathbaba** [comment]
Put it into app’s folder using iTunes. You can find more details in our faq: http://maps <http://maps/>.me/help

**Comment by vhcnxfmi** [comment]
Dec 16 Maps (151215) seem to be incompatible with android-web-universal-release-5.2.1-151207.apk. Is this correct? If so, in the future will you make sure you only offer compatible maps and software?

Thank you!

**Comment by deathbaba** [comment]
Old maps should be compatible. What exactly does not work in your case?

**Comment by Zverik** [comment]
Official maps `151215` are not compatible with any version built before today, since there were changes in file structure.

**Comment by deathbaba** [comment]
Right, we support only older maps, not newer ones :)

**Comment by wwcjsqex** [comment]
Yes, the new maps cause the app to crash constantly. Could you release a compatible APK? Or move incompatible maps to a test folder so it is not confusing?

**Comment by deathbaba** [comment]
You can build compatible apk from the master branch. Official release is coming soon.

**Comment by wwcjsqex** [comment]
Ok, thank you. I only use official web release.

**Comment by Zverik** [comment]
Only fresh maps compatible with official releases are [these](http://direct.mapswithme.com/regular/daily/).
