### ISSUE TITLE
The main thread will be  blocked when I execute the startActivity method from MwmActivity

### ISSUE THREAD

**Issue by zxjvszjl** [mapsme/omim#2848]
Hello,
   When I jump from the MwmActivity to other Activity (startActivity)，the main thread will be  blocked , some time need wait 10 second or more . There is a reason for this situation .When the native method (MapFragment.nativeDestroyEngine()) is executed in MapFragment.surfaceDestroyed().

**Comment by deathbaba** [comment]
CC @rokuz @darina

**Comment by trashkalmar** [comment]
This is specific to debug build. Can you reproduce freezing in release builds? If so, what is your device and Android version?

**Comment by zxjvszjl** [comment]
This problem also exists in the release builds. Thousands of mid-and low-end devices have this problem.

**Comment by trashkalmar** [comment]
Please, give some examples with device vendor + model + OS version.

**Comment by zxjvszjl** [comment]
Mi4 OS version 4.4.4 , Mi4C OS version 5.1.1, Meizu MX4  OS version5.0.1 , a series of  Lenovo devices and Coolpad devices

**Comment by trashkalmar** [comment]
Thanks, we will investigate this.

**Comment by zxjvszjl** [comment]
You're welcome. Look forward to your solution

**Comment by rokuz** [comment]
Unfortunately destroySurface must be synchronous, otherwise the app crashes. On budget devices and in debug such behavior can be got
