### ISSUE TITLE
Small addition to car profile for better routing

### ISSUE THREAD

**Issue by utack** [mapsme/omim#2857]
Hi,

could you please consider adding this OSRM fix to your car profile.
[https://github.com/Project-OSRM/osrm-backend/pull/2239](https://github.com/Project-OSRM/osrm-backend/pull/2239)
It is a one line fix that is compatible with OSRM 4.6 and and improves routing in Germany significantly.

Thanks for consideration

**Comment by deathbaba** [comment]
@gardster can you please check it out?

**Comment by gardster** [comment]
Hi! @utack, thank you for your notice. We will use this fix. https://github.com/mapsme/omim/pull/2867 But changes will be only in future mwm files.

**Comment by utack** [comment]
Great news, thank you for including it.
Will the daily mwm files include this at some point or do you manually have to switch something on the server that generates them?

**Comment by gardster** [comment]
We need to update code manually on the daily build server. I think it will not take long time. But first of all we need to merge this code to the master branch.

**Comment by utack** [comment]
I think this is solved.
Please let me know when the mwm files are new and I will do some testing of how it works out, but so far the same addition in OSRM 5.0 is very promising and resulted in the expected routes and driving times.

**Comment by utack** [comment]
I have built a .mwm file with the included fix now
Could you please tell me how to test it? When putting it in the correct folder it is displayed just fine, but the bubble to download maps is in the way, and when planning a route it says it is missing maps and fails.

**Comment by gardster** [comment]
You need to name mwm same to original file name of this mwm. Original names with mwm borders you can find in data/borders folder. And you must remove folder with temporary indexes (same with mwm name) before starting app.

**Comment by utack** [comment]
It seems to be missing the routing information I just found out.
I used the "generate_mwm.sh" script from tools/unix.

**Comment by gardster** [comment]
Yes. profile.lua or car.lua.

**Comment by utack** [comment]
Well nvm, stuff crashes

> asdf is not a profile, using standard car.lua
[info] Reading options from: /tmp/tmp.0bzh5Z71uy/extractor.ini
[info] Input file: tmp.pbf
[info] Profile: car.lua
[info] Threads: 8
[info] Using script /home/jakob/Downloads/omim/3party/osrm/osrm-backend/profiles/car.lua
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by osmconvert 0.8.4
[info] timestamp: 2016-04-17T19:45:02Z
PANIC: unprotected error in call to Lua API (attempt to index a number value)
./generate_mwm.sh: line 154: 18408 Aborted                 (core dumped) "$OSRM_BUILD_PATH/osrm-extract" --config "$EXTRACT_CFG" --profile "$PROFILE" "$PBF"

I will just wait for your official maps with this fix

**Comment by utack** [comment]
Just tested it, and it seems to be working nicely
Thanks again for adding this!
(In some cases it does not seem to give the same results as the current OSRM 5.0 version with the fix, but I will test that properly when OSRM 5 has an interactive map to test.)
Old way, through the city:
![screenshot_20160428-223154](https://cloud.githubusercontent.com/assets/8551234/14900592/926f7a0c-0d91-11e6-941d-3b8fd52fcdb4.png)

New:
![screenshot_20160428-222950](https://cloud.githubusercontent.com/assets/8551234/14900556/621a04e4-0d91-11e6-909a-a0e68f6a566e.png)

**Comment by utack** [comment]
Sorry, one more question.
I seem to be too stupid to rtfm on generating the maps.
I copied the poly files you delivered to a folder "sax" and try to generate the two split maps the state is made of.
Neither
> BORDER=./sax/Germany_Saxony_Dresden.poly ../omim/tools/unix/generate_mwm.sh sachsen-latest.osm.pbf  asdf
  
Nor
> BORDERS_PATH=./sax/ ../omim/tools/unix/generate_mwm.sh sachsen-latest.osm.pbf asdf

  
works for me.
Could you please tell me how to correctly get a split map? Thanks

**Comment by utack** [comment]
@gardster maybe you could take a quick look at why my approach above fails please
If there are no obvious mistakes in my attempt I will just have to wait for your official map update instead

**Comment by gardster** [comment]
@utack If you want to have correct cross border points, you need to generate proper packed_polygons.bin file before you run mom generation. You must call generator_tool with flag --generate_packed_borders

**Comment by utack** [comment]
Thanks for the hint.
I will try that, meanwhile I am using the latest maps you built with the fix
