### ISSUE TITLE
Add undo changes option or confirmation screen

### ISSUE THREAD

**Issue by mhyqwvcu** [mapsme/omim#2885]
Edits made are immediately final after pressing the check mark. You can only delete all pending changes before upload, not individually. Think about adding a confirmation screen after pressing the check mark with a summary of the changes too.

**Comment by deathbaba** [comment]
The idea was to allow easy and quick editing of everything around. Confirmation makes it harder.
We are thinking about Reset Changes button for edited places.

**Comment by mhyqwvcu** [comment]
>Reset Changes button
That's a good idea.
