### ISSUE TITLE
Huge and nasty memory leak found in SetMapStyle()

### ISSUE THREAD

**Issue by peterrudenko** [mapsme/omim#2890]
Steps to Reproduce:
1. Install the latest build from AppStore (by 13 Apr).
2. Launch XCode Instruments -> Activity Monitor.
3. Launch Maps.Me, go to Settings -> Night Mode.
4. Switch night mode on and off, repeat, and so on.
5. Watch your RAM being consumed while you're switching the modes.

Actual Results:
Memory leaks as fuck (~5-10 MB on every change).

Expected Results:
No leaks.

The latest commit from master still has the issue (moreover, I'm getting some obscure crash in Classificator exactly when changing style).
Any thoughts on how to fix this are highly appreciated.

**Comment by deathbaba** [comment]
CC @vng

**Comment by vng** [comment]
1. To check this issue on master, use the branch from this PR #2854. It's not merged yet.
2. Actually, I didn't notice any abnormal memory usage increase when you change mode manually and return on the map. Memory fluctuations are the same when we do scale on the map view.

**Comment by peterrudenko** [comment]
Well that's weird.
I am still able to reproduce what I've described above.
As I keep switching the styles, app memory usage grows up to ~670MB on my iPhone and eventually the app crashes.

**Comment by deathbaba** [comment]
So even #2854 does not fix the problem? We need more details on this.

**Comment by peterrudenko** [comment]
It doesn't (just tested it and ended up with the same "terminated due to memory issue").
The project I'm working on relies on your library as of January'16, so the bug is not new.
I uploaded the Allocations and Leaks Profilers traces (both from start to crash), hopefully they help: https://drive.google.com/folderview?id=0ByCooVN53hS_aVBSY3g5QUtMbW8

**Comment by deathbaba** [comment]
@vng @igrechuhin @VladiMihaylenko @syershov we need to check it out.

**Comment by vng** [comment]
Device model, iOS version?

**Comment by peterrudenko** [comment]
iPhone 6, iOS 9.3.1
iPhone 5, iOS 9.2.1
iPhone 5, iOS 8.4
iPhone 4s, iOS 8.0.2

**Comment by vng** [comment]
Well, I can reproduce it! @igrechuhin @VladiMihaylenko
Guys, try to go to the Settings page and do continuous switching between on/off Night mode without returning back to the map. Seems like interface reloading procedure leaves references to the previous objects. The "Real memory" usage is growing up to 200Mb and then it can be crash or GC grabs the "unused" memory and it folds back to 100Mb.

**Comment by peterrudenko** [comment]
Any updates on this guys?
I've tried Maps.Me build at home on iPad4 with iOS 9.3, and strangely "real memory" usage did never grow above ~200MB there - but I was still getting the crashes after switching styles a lot. Unluckily, the project I'm working on relies heavily upon style switching feature, so this is a kinda blocker bug for us.

**Comment by peterrudenko** [comment]
ping

**Comment by ygorshenin** [comment]
@vng, do we have kernel unit-tests for style switching? If so, I can try to analyze our code with leak sanitizer.

**Comment by ygorshenin** [comment]
But I can analyze only kernel.

**Comment by vng** [comment]
@ygorshenin Well, you can try to make such test. Just create Framework instance with classificator and drape initialization and call Framework::SetMapStyle.

**Comment by rokuz** [comment]
Thanks for reporting. You can try to apply this PR https://github.com/mapsme/omim/pull/2945 or wait for its merging.
