### ISSUE TITLE
Leading and trailing spaces in tags should be trimmed when editing

### ISSUE THREAD

**Issue by seav** [mapsme/omim#2902]
Please see this changeset: http://www.openstreetmap.org/changeset/38381191

The editor changed the name tag of one object from `name="Robinsons Magnolia"` to `name=" Robinsons Magnolia"` (a space was added at the front of the value). While this is OK from the OSM API point of view, this is different from how most editors I've used handle this. They trim the leading and trailing whitespace and if there are no difference, the object is not updated.

**Comment by deathbaba** [comment]
Thanks, we’ll add some basic trimming as a part of input validation.

CC @burivuh @Zverik @mgsergio

**Comment by Zverik** [comment]
FIxed in #3671.
