### ISSUE TITLE
OSRM-build on Arch Linux fails

### ISSUE THREAD

**Issue by utack** [mapsme/omim#2905]
Trying to build the osrm-backend on Arch Linux
It fails: [https://paste.ubuntu.com/15906808/](https://paste.ubuntu.com/15906808/)
Maybe you could have a look and know why, that would be great.
Configuration looked like this:
https://paste.ubuntu.com/15906829/
Or should this be asked in the OSRM bug tracker?
Thanks

**Comment by deathbaba** [comment]
Is your system a 64 bit one? Looks like the issue is in the line
> osrm/osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf_parser.hpp:160

You probably can cast osmium::Location constructor parameters to either double or int64_t. May be better would be to check the same line of code in original OSRM code, they can already fix it.

**Comment by utack** [comment]
Thanks for looking at it
OSRM did not fix that, but I casted manually now, good enough as workaround for a test setup
