### ISSUE TITLE
Changeset discussions on map edits are invisible to user

### ISSUE THREAD

**Issue by Piskvor** [mapsme/omim#2927]
With the launch of map editor inside the maps.me app, many more people have started editing OpenStreetMap; that's a great thing, as it means more eyes and thus more data.

In some cases, however, the data is *problematic* - e.g. people adding descriptions like "this is my house" into house numbers. In OSM, it is possible to start a Changeset Discussion for each batch of edits ( http://wiki.openstreetmap.org/wiki/Changeset#Changeset_Discussions ), which is also used for contacting the mapper to clarify what the edit meant.

The maps.me app doesn't seem to notify the user that a discussion is started for their edit (and thus that something might be wrong with it); thus it looks as if the original user doesn't care about the discussion, even if that's not necessarily true.

Perhaps the app might poll the user's (recent) changesets to see if a discussion exists, and notify the user (and perhaps show a link to the OSM changeset/discussion on the web)? ttp://wiki.openstreetmap.org/wiki/API_v0.6#Read:_GET_.2Fapi.2F0.6.2Fchangeset.2F.23id.3Finclude_discussion.3Dtrue

**Comment by deathbaba** [comment]
Are there any email notifications when someone leave a comment for a changeset?

**Comment by Piskvor** [comment]
If a message is sent, that would be quite sufficient IMHO.
Tried adding a comment on my recent changeset, got nothing so far. http://www.openstreetmap.org/changeset/38722468

Either a) none are sent for own-comment, or b) they're not sent right away, or c) the message was somehow lost; e-mail happens :( 
Worst case, d) none are sent at all (which would be strange)

Will wait a bit and see if I get a notification eventually. @deathbaba, could you please leave a comment e.g. here http://www.openstreetmap.org/changeset/37161054 (my older changeset w/o a discussion)?

**Comment by deathbaba** [comment]
Done.

If emails are not sent, this should be fixed. It’s the most effective way to reach users (and not only those who uses MAPS.ME).

**Comment by Piskvor** [comment]
Ah, wonderful. Got an e-mail now, that solves it then. Thanks a lot!
