### ISSUE TITLE
Невозможно выключить геолокацию

### ISSUE THREAD

**Issue by FelisPimeja** [mapsme/omim#2957]
В бете под андроид невозможно отключить определение местоположение. Предположительно появилось после изменений от 15 апреля.

**Comment by Zverik** [comment]
Сейчас проверил на последней бетке от сегодня — отключается. Как это выглядит?

**Comment by trashkalmar** [comment]
В мастере этот режим уже отключён.

**Comment by burivuh** [comment]
Это запланированное поведение.

Мы отключаем явное состояние No position, при этом в режиме карты перестаем
опрашивать локацию со скоростью бешеной собаки.

Пока сделана первая часть

2016-04-22 9:38 GMT+03:00 Felis Pimeja <notifications@github.com>:

**Comment by FelisPimeja** [comment]
Ok
