### ISSUE TITLE
Render error in New York City

### ISSUE THREAD

**Issue by utack** [mapsme/omim#2967]
The south of New York is not rendered correctly:
![screenshot_20160423-034010](https://cloud.githubusercontent.com/assets/8551234/14758581/4196dc64-0905-11e6-8d52-e269f4b76c18.png)
(Water street indeed, literally)
Tested on two devices with Adreno GPU and version 6.0.7-Google, as well as "release map" and daily map.
When updating to the latest nightly (23.04) the bug is gone, so it should be easy to narrow down why this is happening
If you tell me where to find old daily builds I can also narrow it down to a 1-day window and report back

**Comment by deathbaba** [comment]
Is it an osm data error which was fixed by someone?

**Comment by utack** [comment]
6.0.7-Google (where the problem occured) and the latest beta (where the problem did not occur) used the exact same mwm file, so it is definitely not in the map data.
Logcat does not show anything interesting

**Comment by deathbaba** [comment]
CC @rokuz @dvolvenkova

**Comment by utack** [comment]
I just built fdb70b9330d4bad53cda9d8072f18696b72cdde6 from April 14th and the bug is also gone in this version.  
Will have time to test other versions tomorrow and narrow it down
