### ISSUE TITLE
Potential energy saving idea

### ISSUE THREAD

**Issue by utack** [mapsme/omim#3090]
Just an idea how some energy could be saved. Not sure if it is any good.
When the map is locked to the GPS position, like in navigation mode, generally you will not move faster than any car and location updates will come in at a rate lower than 10/s
In that mode you could probably change the refresh rate of the map to 30fps, and reduce energy used for rendering, while it still looks smooth enough. You can easily set it back to maximum refresh rate the phone can render in "browsing mode", when you scroll the map manually

**Comment by rokuz** [comment]
Thank you. Implemented in January :)
