### ISSUE TITLE
How often are map update ?

### ISSUE THREAD

**Issue by larfadin** [mapsme/omim#3092]
Hi,

I know this is not really an issue but I can't find any answer in the app or website.
How often are map update and how do we update them?
Because it's became hard to add POI when the map is "old"

**Comment by MariasStory** [comment]
see this one: https://github.com/mapsme/omim/issues/3113

**Comment by deathbaba** [comment]
We update them soon, and try to stick to a 2 weeks update cycle.

**Comment by MariasStory** [comment]
This is what I would like to see :-)

**Comment by larfadin** [comment]
@deathbaba nice, even if it's 1 month it's good
