### ISSUE TITLE
application is not using latest data from http://direct.mapswithme.com/direct/

### ISSUE THREAD

**Issue by Blackbird27** [mapsme/omim#3113]
I am using latest application version on Android which is 6.0.7-Google, and application is using maps from http://direct.mapswithme.com/direct/ but it not using latest rendered which is 160426 and dated 28-Apr-2016, but uses as it should folder "latest" but this folder has data from 25-Mar-2016. Most likely its the issue with map data repository not with the application.

**Comment by deathbaba** [comment]
“latest" link always points to the latest publicly released version, so it’s ok.

**Comment by Blackbird27** [comment]
So those folders meant for the nightly builds of application and testing purposes?

**Comment by deathbaba** [comment]
Yes, for intermediate development builds.
