### ISSUE TITLE
pt_BR i18n

### ISSUE THREAD

**Issue by nighto** [mapsme/omim#3160]
Hi folks, I'd like to start to translate the app into Brazilian Portuguese (`pt_BR`). It is slightly different then Portugal portuguese (`pt_PT`), specially in transportation (many terms are different, such as "train", "bus" etc).

Is it enough to add the strings to [strings.txt](https://github.com/mapsme/omim/blob/master/strings.txt), [categories.txt](https://github.com/mapsme/omim/blob/master/data/categories.txt) and [sound.csv](https://github.com/mapsme/omim/blob/master/sound/tts/sound.csv), or should I change other files?

Also, should I rename the current `pt` strings for `pt_PT`, or leave them as `pt` and simply add new `pt_BR` entries?

Thanks.

**Comment by nighto** [comment]
Just noticed that there is a `zh-Hans` on strings.txt. Guess I'll write it as `pt-BR` then.

**Comment by Zverik** [comment]
There are also `countries-names.txt` and `cuisines.txt`.
The working branch for now is `release-61`, there are some translations that didn't go into the `master` branch yet. I guess you should wait until release, so everything is merged back.
You are right wrt `pt-BR`, the original language should remain `pt`.

**Comment by nighto** [comment]
Ok, thanks. I'll work on the files as they are on master, then when they are merged I'll update the translation.

**Comment by Zverik** [comment]
We've just merged the release branch into master, so it's safe to work now.
