### ISSUE TITLE
Possibility to add OSM notes

### ISSUE THREAD

**Issue by andree182** [mapsme/omim#3183]
The OSM editing is already great addition, however sometimes map issues are not solvable quickly on the spot. It would be great if OSM notes could be added right from the app similarly as new objects. On the other hand, this could lead to big amount of such notes, so perhaps it could be hidden under some kind of "advanced user mode"?

**Comment by Zverik** [comment]
OSM notes will be added in the next release, you can use them now in a [beta build](http://osmz.ru/mwm/mwm_release.apk).
