### ISSUE TITLE
Search result is not selected on the map

### ISSUE THREAD

**Issue by PaulAnnekov** [mapsme/omim#3251]
1. Open Search.
2. Enter some address.
3. Click on any result.
4. Map will open and centered on this result, but you won't see blue circle in the center of the building/POI.

Sometimes it's very hard to understand where is this node :). Check the video: https://youtu.be/2yPCLWTbYBI

**Comment by utack** [comment]
That is a regression, worked before

**Comment by PaulAnnekov** [comment]
sure, that's why this issue is here :)

**Comment by utack** [comment]
This seems fixed in 6.1.x on two Android devices I tested
Maybe you can close the issue if it works for you too again?

**Comment by PaulAnnekov** [comment]
@utack yep, seems to be fixed. Looks like devs have stopped tracking issues :(. Will close it by myself.
