### ISSUE TITLE
It is not possible to add POI in navigation mode

### ISSUE THREAD

**Issue by dbf256** [mapsme/omim#3365]
Could be useful for pedestrian routing.

**Comment by brunetton** [comment]
Indeed

**Comment by rokuz** [comment]
Hi, thanks for reporting. We've got 3D navigation with perspective projection. In this case adding something is not simple and convenient. We will think how to improve it.

**Comment by dbf256** [comment]
ok, got it. Yes, there is no sense to add it to perspective view, when you have a long pedestrian route for several km it could be useful to add some POIs.
