### ISSUE TITLE
Generator tool

### ISSUE THREAD

**Issue by stalehard** [mapsme/omim#3375]
Hello, I see you changed method to store navigation file and now it integrated with mwm. 
Did method for generating not change?

i have this error by generating .mwm file 
`
omim/tools/unix/generate_mwm.sh: line 109:   410 Segmentation fault      (core dumped) $GENERATOR_TOOL $INTDIR_FLAG --osm_file_type=o5m --osm_file_name="$SOURCE_FILE" --data_path="$TARGET" --user_resource_path="$DATA_PATH" $GENERATE_EVERYTHING --output="$BASE_NAME"
`

**Comment by Zverik** [comment]
Could you please test it with the latest version from either `master`, `release-616` or `release-62` branch? If it still fails, send me (iz@maps.me) the input file, since I could not reproduce the error.

**Comment by stalehard** [comment]
Ok, I sent a email with detailed info

**Comment by stalehard** [comment]
Problem was in WorldCoast.geom file stored in same directory that omim-*
