### ISSUE TITLE
CLA 404

### ISSUE THREAD

**Issue by kw217** [mapsme/omim#338]
https://github.com/mapsme/omim/blob/master/docs/CLA.md points to http://maps.me/cla but that URL redirects me to http://maps.me/en/cla which just says "Not Found The requested URL /cla.php was not found on this server.".

Please can you fix so I can sign the CLA?

Thanks.

**Comment by Zverik** [comment]
We have restored [the CLA](http://maps.me/cla/), the link should have a trailing slash. Sorry for this outage.

**Comment by kw217** [comment]
Thanks.
