### ISSUE TITLE
Intermediate points in trace

### ISSUE THREAD

**Issue by asiaGermi** [mapsme/omim#3481]
can I insert more than two points in the trace? for example an intermediate point between the start and finish.

**Comment by rokuz** [comment]
Hi, now you can't. We will do it in future.

**Comment by kozuch** [comment]
Looks like this issue is about adding additional waypoints/stops to a route when using directions. I really miss this feature too. Are there any current plans on implementing this?

**Comment by rokuz** [comment]
Wait for press release :)

**Comment by kozuch** [comment]
@rokuz When will the press release appear?

**Comment by rokuz** [comment]
@kozuch Soon. Exact date can't be divulged now.

**Comment by rokuz** [comment]
We've added an intermediate point in 7.4 version.

**Comment by kozuch** [comment]
@rokuz I just tested the feature - nice but it looks like there is a possibility to add ONE intermediate point to the route. I could not find a menu for an additional int. points (meaning multiple int. points in general). Would you please confirm it really is only ONE point?

I would like to being able to add multiple intermediate points to the route. I think this issue should be about multiple points. Can you reopen this issue then or should I create a new one?

**Comment by rokuz** [comment]
We are working on this feature. Wait for multiple points in one of next releases.
