### ISSUE TITLE
Better tracking accuricy while in forest

### ISSUE THREAD

**Issue by axet** [mapsme/omim#3493]
Hello!

I'm using map.me on Android to track my distance travels. It works fine in the city, but fails in the forest. Seems like your algorithm is:

every 30/60 seconds enable geo location for 2 seconds to get location what ever it will be.

This algorithm works fine when you in the city, because it is very easy to determinate your location using GSM / Wifi / Bluetooth spots to determinate location (which is done by OS). But dosn't work in the forest. To determine my location I have to keep Map.ME open with screen on keeping my phone in hands for a minute or five minutes depend on location before I can get accurate location.

Can you improve tracking algorithm to following:

every 30/60 seconds enable geo location until you get required accuracy (Option in settings 10m/50m/100m/1km) with maximum of 5 mins to get location.

PS: forget to mention, when I'm in forest maps.me vanish all tracks, like never go in to forest. seems like it taking wrong location every time (low accuracy and do not place mark path on map at all)

**Comment by rokuz** [comment]
Hi! Thanks for reporting. We are looking for a compromise between accuracy and battery consumption. Such manipulation with location services can lead to excessive battery consumption. Anyway we understand your problem and do our best to resolve it.
