### ISSUE TITLE
Allow custom data directory on sdcard for bookmarks

### ISSUE THREAD

**Issue by patcon** [mapsme/omim#355]
Allowing bookmark data to be saved to arbitrary locations would allow users to backup and sync bookmarks between devices without requiring the developers to bundle support for each possible sync tool.

For example, syncthing and seafile both allow for syncing any directories on the sdcard

**Comment by deathbaba** [comment]
Storing bookmarks on SD card is a very bad idea. We have already tried it once, and got a lot of complaints about missing bookmarks due to bad SD cards. Amazingly, hundreds and thousands of issues, including slow app start or search, crashes, missing maps and bookmarks are caused by cheap and non-working SD card.

To backup bookmarks they should be synced with a cloud.

**Comment by patcon** [comment]
Sorry, aren't they stored in `/mnt/sdcard/MapsWithMe` right now?

> To backup bookmarks they should be synced with a cloud.

And again, I'm confused, as that's why I'm making the suggestion, I say "sync app", but that could be cloud (like dropbox) or p2p (like btsync or syncthing). By making the config directory configurable, that means that the app maintainers don't need to integrate every sync provider.

**Comment by deathbaba** [comment]
/mnt/sdcard/MapsWithME is actually a folder on internal device’s memory. And you can easily configure dropbox or other apps to point to it now.

When I mention automatic backup, I meant Google Play’s cloud mechanism, where app can automatically store it’s settings and restore them after reinstall on another device, without any Dropbox-like 3party services.

**Comment by patcon** [comment]
I appreciate the explanation!

On further consideration, would you be willing to accept a PR that separated the map cache and bookmarks settings into separate directories, so syncing bookmarks via 3rd-party services was more straightforward? (I'm interested in using maps.me as part of a nogapps rom, so the google backup option isn't ideal :)

**Comment by deathbaba** [comment]
If you have an external SD and move maps there, bookmarks remain in internal memory.

If you really want to separate, you can modify code (look for MapsWithMe keyword in Java part and around) and build your own version. Internally, there are settingsDir and writableDir.

**Comment by patcon** [comment]
So... that's a "no" to creating a subdir?

**Comment by deathbaba** [comment]
I still do not see it as a real reason to put this change into the production code. Other users did not request it.

**Comment by patcon** [comment]
with all respect, that seems like a rather rigid stance on maintainer duties

it's perhaps one of the smallest possible changes, and has narrow limits of harm, and it helps a [class of] user without adding any significant complexity to the code or UI. But it's your project, so whatever, I suppose -- it just strikes me as a bit unfriendly to participation from the view of someone engaging for the first time

Anyhow, it's a great app regardless, do thanks for what you do

**Comment by deathbaba** [comment]
Patrick, this change is not a small one, if you want to change UI of the app for millions of users. Especially, if they don’t need it (our support tracks hundreds of requests every day, and this one isn't on their radar).
A good example of ‘changes freedom' is OsmAnd, but it’s UI, unfortunately, is too complex for non-geeks. And we don’t want MAPS.ME to become as complex to use as OsmAnd.

If you really need this change, you can easily fork source code and add a patch.

**Comment by patcon** [comment]
> if you want to change UI of the app for millions of users

Sorry, maybe I was unclear, and so I apologize. My revised ask was whether I could submit a PR for a subdir for the bookmarks, like so:

```
MapsWithMe
├── 151009
│   ├── Canada_Ontario.mwm.routing
│   ├── USA_California.mwm
│   └── USA_California.mwm.routing
├── bookmarks
│   └── My Places.kml
└── settings.ini
```

That would allow simple syncing of that dir for advanced users, without syncing the map files :)

**Comment by deathbaba** [comment]
...and it will break existing settings for every old user?

Such PR is a bad idea.

**Comment by patcon** [comment]
I wasn't suggesting a simple find-replace in the codebase, so yes, I would need to write some glue to move the files on update.

I'm not disillusioned enough to say that nogapps users are highly represented in your userbase. But there are lots of people interested in slowly chipping away at the centralization problem in their own ways (GMaps, Google Play Services, etc), and it's clear that my particular concerns are not yours. Sorry for taking up so much of your time, and thanks again for the app

Speaking of auto-backup: #401

**Comment by deathbaba** [comment]
In recent versions we have changed the way maps are stored. Now they use subfolders, may be this can make bookmarks backup easier?

We also thinking about own backup/sync server for users share same bookmarks on any platform.

And the issue you originally raised was about some 3party utilities which can handle only directories in a recursive manner, not individual files from these directories. Does it make sense to ask developers of those backup utilities to add support for specific files/extensions?

**Comment by patcon** [comment]
> Does it make sense to ask developers of those backup utilities to add support for specific files/extensions?

Heh thanks for the thought cycles on the issue. You are right that the sync provider I'm using (Syncthing) has an advanced feature similar to `.gitignore`, but it has no UI on Android, so that needs to be written. And the protocol is still being worked out, so it needs to be set manually on any node that it syncs to. It's basically so painful that I can't imagine it being useful until quite some work. Sorry, TMI :)

It's just a much harder problem on that end, and other sync/cloud tools don't often seem to prioritize ignore lists, since their main use-case is syncing user-managed folders, not application config directories :)

**Comment by deathbaba** [comment]
The only work-around I see now is to use a device with an SD-card, move maps there, and sync bookmarks left in internal memory...
