### ISSUE TITLE
import android studio and build

### ISSUE THREAD

**Issue by shazde2025** [mapsme/omim#3591]
hi 
i am developer and i want import this project in android studio 
i do'nt know anything about this operation
please help me what i do very simple
tank you everyone

**Comment by rokuz** [comment]
1. Execute tools/android/set_up_anddroid.py. You will be asked to add SDK and NDK paths, do it.
2. Import project to android studio from Gradle. This is a standard operation which is easy to google (e.g. http://stackoverflow.com/questions/25537126/android-studio-import-project-from-gradle).

**Comment by fukemy** [comment]
i love u rokuz
