### ISSUE TITLE
problem in specify sdk and ndk path

### ISSUE THREAD

**Issue by shazde2025** [mapsme/omim#3604]
i try specify sdk and ndk path but i hame same problem

Path to Android SDK, "s" to search []:**## C:\Users\Asus\AppData\Local\Android\sdk**
**Could not find C:\Users\Asus\AppData\Local\Android\sdk\platform-tools\adb, not an Android SDK path.

Traceback (most recent call last):
  File "D:\Android\mapsme\omim-master\omim-master\tools\android\set_up_android.py", line 101, in <module>
    sdkDir = query_path('Android SDK', options.sdk, sdkDir, ['platform-tools', 'adb'])
  File "D:\Android\mapsme\omim-master\omim-master\tools\android\set_up_android.py", line 60, in query_path
    sys.exit(1)
SystemExit: 1**

**Comment by trashkalmar** [comment]
You have to add to `PATH` environment variable path to tools and platform-tools dirs of your Android SDK installation.
Note, that we do NOT support building android app under Windows platform.

**Comment by Zverik** [comment]
Right, we don't support Windows builds officially, so most (or all) of our tools require Linux or FreeBSD or Mac OS X.
But you can do `./set_up_android.py --sdk C:\Users\Asus\AppData\Local\Android\sdk --ndk C:\Whatever\Path\To\NDK`
