### ISSUE TITLE
Bicycle mode routing makes an odd decision

### ISSUE THREAD

**Issue by utack** [mapsme/omim#3678]
Currently the beta calculates a long route with many (absurd) turns when starting roughly [here](https://www.openstreetmap.org/node/3272433826) and going [here](https://www.openstreetmap.org/node/3397947279)
https://jmuehldorfer.de/owncloud/apps/gpxpod/publink?filepath=/Dateien/GPSTracks/current.gpx&user=jmuehldorfer
The obvious answer is just to follow the street, which is correctly tagged with "cycleway:right=lane"
https://jmuehldorfer.de/owncloud/apps/gpxpod/publink?filepath=/Dateien/GPSTracks/expexted.gpx&user=jmuehldorfer

**Comment by Zverik** [comment]
Merged, building the data for the next release with it.

**Comment by utack** [comment]
Thank for the quick fix  
That should improve the routing quite a bit, over 75.000 instances of cycleway:right and left

**Comment by utack** [comment]
Confirmed in the new verison: bike routes are vastly imrpoved :+1:
