### ISSUE TITLE
It's not clear to users that "Additional Info / Detailed comment" adds an OSM note

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mapsme/omim#3712]
MAPS.ME users mostly use this for storing personal notes.  The text "below the line" does say "your suggested changes will be sent to OSM" but the line separates the two in the UI so the one doesn't see connected to the other.

A number of people in #osm have said recently "so _that's_ where the notes are coming from!".  It's really not obvious.  OSM's "add note" contains the text "(Please don't enter personal information or information from copyrighted maps or directory listings.)".  MAPS.ME has no similar caveat.

**Comment by Zverik** [comment]
I agree that it isn't obvious what the field means, or where the data goes. We have discussed this some days ago, and will update both the messages and the workflow. Including a mention for personal information.

**Comment by SomeoneElseOSM** [comment]
Hi Zverik - any news on this?  We're still seeing lots of very confused tourists using MAPS.ME adding lots of duplicates and various languages.

**Comment by Zverik** [comment]
It should be fixed in the new iOS release, and the Android one should follow in a week.
