### ISSUE TITLE
Android build fails: LOCAL_SRC_FILES points to a missing file

### ISSUE THREAD

**Issue by eigenein** [mapsme/omim#3716]
Hi,

I'm trying to build the app for Android on OS X 10.10.5. I followed `INSTALL.md` and did both `./configure.sh` and `./tools/android/set_up_android.py`.

Here is `local.properties`:

```
pperestoroni@ml905637:~/GitHub/omim/android (master=)$ cat local.properties
# Autogenerated file
# Do not add it to version control
sdk.dir=/Users/pperestoroni/Library/Android/sdk
ndk.dir=/Users/pperestoroni/Library/Android/android-ndk-r10e
```

Then `QMAKE=/Users/pperestoroni/Qt/5.7/android_armv7/bin/qmake ./gradlew clean assembleWebRelease` gives me the error:

```
Android NDK: ERROR:jni/Android.mk:map: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that jni/../../../omim-android-production-armeabi-v7a-hard/out/production/libmap.a exists  or that its path is correct
/Users/pperestoroni/Library/Android/android-ndk-r10e/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop.
:ndkBuildRelease FAILED
```

Directory `jni/../../../omim-android-production-armeabi-v7a-hard` is existing but empty.

What am I doing wrong? The whole build log is attached: [build.log.txt](https://github.com/mapsme/omim/files/345291/build.log.txt).

**Comment by rwoloszyn** [comment]
I am not sure but it sounds that the project structures have subrepositories. Maybe this is the issue 
that you did not checked them out ?

**Comment by eigenein** [comment]
@rwoloszyn: Ah, forgot to say that I did `git submodule update --init --recursive` as well.

**Comment by CodeFarmerZYW** [comment]
I also encountered the same problem,Do you have to solve it

**Comment by eigenein** [comment]
Not solved.

BTW, `Android.mk` mentions some

> static libraries which are built using our own scripts in tools/android

I can see neither these static libraries nor any scripts to build them. Weird.

**Comment by CodeFarmerZYW** [comment]
Hi,When I run ./tools/android/set_up_android.py , It's -bash: ./tools/android/set_up_android.py: /usr/bin/python:  No such file or directory ,Do you know what to do?

**Comment by yunikkk** [comment]
Hello guys.
Turned that one of our scripts (../tools/autobuild/detect_qmake.sh) was working wrongly with custom QMAKE path set. So native static libraries weren't actually built and that's why you got the error.
https://github.com/mapsme/omim/pull/3737 will fix it.

**Comment by eigenein** [comment]
Hi @yunikkk! Great, thank you!

**Comment by eigenein** [comment]
Confirm – it builds successfully with #3737.

**Comment by yunikkk** [comment]
#3737 was merged, closing that.

**Comment by guoxiaojun001** [comment]
Error while executing process E:\develop\sdk\ndk_r14b_r16b\android_ndk_r16b\ndk-build.cmd with arguments
 {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=F:\Telegram\TMessagesProj\jni\Android.mk NDK_APPLICATION_MK=F:\Telegram\TMessagesProj\jni\Application.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=0 APP_PLATFORM=android-16 NDK_OUT=F:/Telegram/TMessagesProj/build/intermediates/ndkBuild/armv7/release/obj NDK_LIBS_OUT=F:\Telegram\TMessagesProj\build\intermediates\ndkBuild\armv7\release\lib NDK_APPLICATION_MK:=jni/Application.mk APP_PLATFORM:=android-16 -j8 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}


Android NDK: ERROR:F:\Telegram\TMessagesProj\jni\Android.mk:avutil: LOCAL_SRC_FILES points to a missing file    


Android NDK: Check that /ffmpeg/armv7-a/libavutil.a exists  or that its path is correct

**Comment by alexzatsepin** [comment]
Hey @guoxiaojun001 ,

Please follow this guide https://github.com/mapsme/omim/wiki/%5BAndroid%5D-How-to-build-project and let me know if you have any questions after reading.
