### ISSUE TITLE
Error:(424, 0) Cannot invoke method getAbsolutePath() on null object Open File

### ISSUE THREAD

**Issue by CodeFarmerZYW** [mapsme/omim#3722]
Android Stuiod  ：Error:(424, 0) Cannot invoke method getAbsolutePath() on null object
Open File
build.gradle
task patchNdkR10E(type: Exec, description: 'Patches NDK r10e for bug described here https://code.google.com/p/android/issues/detail?id=179410') {
  def cxxabiPath = "${android.getNdkDirectory().getAbsolutePath()}/sources/cxx-stl/gabi++/src/cxxabi.cc"
  commandLine 'bash', '-c', "patch -p1 ${cxxabiPath} < ../tools/android/cxxabi.cc_patch"
}

What am I to do? 
And when I run  ./set_up_android.py , -bash: ./set_up_android.py: /usr/bin/python: No such file or directory.

**Comment by Zverik** [comment]
You have to set up paths to Android SDK and NDK. For Windows, see #3604.
