### ISSUE TITLE
[Android] :omim-master/drape/shader_def.cpp failure to find

### ISSUE THREAD

**Issue by CodeFarmerZYW** [mapsme/omim#3732]
When I use cygwin, omim-master/drape/shader_def.cpp failure to find

**Comment by rokuz** [comment]
You must execute qmake on the drape.omim, the file will be generated

**Comment by CodeFarmerZYW** [comment]
@rokuz  first,thanks,but how to execute qmake on the drape.omim? I not find the drape.omim

**Comment by rokuz** [comment]
Sorry, I mean drape.dro. From Qt Creator you can do right click on drape subproject and select run qmake. You can also do it from command line. Please check options of command line utility qmake

**Comment by CodeFarmerZYW** [comment]
@rokuz Thank you very much!
