### ISSUE TITLE
How to Update countries.txt when updating map (.mwm)

### ISSUE THREAD

**Issue by gisaia** [mapsme/omim#3743]
Hello, 

I am trying to download a map from my sever, I added its URL to private.h in JSON format and it works.
The problem I faced is about countries.txt. Each time I add a new map to my server, to be able to download it with my android app on my phone, I am obliged to modify /data/countries.txt manually with the right size of my .mwm and the right version.
Is there any way to download the updated contries.txt from the server , or another solution to avoid the manual modification of this file ?

Thank you for your help !

**Comment by Zverik** [comment]
Alas, no. We are planning to decouple maps from app versions, downloading `countries.txt` from a server, for for now you will have to rebuild the application.

Alternatively, you can edit class `FileHttpRequest` in `platform/http_request.cpp`, removing size check. Also you will have to alter `chunks_download_strategy.cpp`. If the resulting mwm will have some extra garbage at the end, that's okay, the app will still read it.
