### ISSUE TITLE
Disable some push notifications

### ISSUE THREAD

**Issue by naoliv** [mapsme/omim#3746]
Today, for the first time, I saw a notification from maps.me saying something like "What are you planning for this weekend" (really don't know exactly the phrase), but I have `Show offers` disabled in preferences.

Is it possible to disable such push notifications, please?

maps.me version is 6.2.2-Google

**Comment by Zverik** [comment]
"Show offers" disables a special menu item, but not notifications. To do that, open Setting app, then "Applications → MAPS.ME → [ ] Show notifications".

**Comment by naoliv** [comment]
But shouldn't this be controlled inside maps.me?
For example, I would like to see when I have map updates but I don't want to see something asking "What are you planning for this weekend".

Blocking every notification is not the intended action.

**Comment by Zverik** [comment]
I assume 2-3 generic push notifications a year is not a good reason to clutter the settings interface. You can make a personal apk with select notifications removed, look for `PushWoosh` references.

**Comment by cdriveraus** [comment]
There seem to be more of these notifications happening, a way to disable would be nice...
