### ISSUE TITLE
Can't change the closing time except in advanced mode

### ISSUE THREAD

**Issue by Kjarrval** [mapsme/omim#3769]
When editing POIs by adding opening hours, the default (after turning off "All day") is 10:00-22:00. I can change the opening time to the appropriate time with no problems. When I change the closing time to another hour than 22:00, it does not update.

However, as a workaround, editing the opening time via the UI and then manually changing the closing time in advanced mode does work.

**Comment by Zverik** [comment]
Thanks for this report, it is fixed in #3757 and will be released in a week or so.
