### ISSUE TITLE
android debug c++ file

### ISSUE THREAD

**Issue by AriesJiang** [mapsme/omim#3782]
I'm curious about your android/c++ programming environment. How do you debug c++ code, when it crash. I use android studio, but can not debug c++ and JNI code.

**Comment by yunikkk** [comment]
Hello.
We still don't use new experimental Gradle plugin that supports debugging directly from the android studio. You can use gdb and manually attach it to running app, though it requires some efforts - you can easily find some tutorials and guides, eg https://developer.android.com/ndk/guides/ndk-gdb.html. 
Alternatively, you can debug it with the help of logging. Most convenient way for the majority of cases.
