### ISSUE TITLE
Routing Bicyle on "highway=path"

### ISSUE THREAD

**Issue by DenisCarriere** [mapsme/omim#3787]
I've noticed on the **beta routing bicycle** that you cannot navigate over `highway=path` + `bicycle=yes`.

The tag `bicycle=yes` should allow the routing engine to work for all highway types.

**Comment by bykoianko** [comment]
> The tag bicycle=yes should allow the routing engine to work for all highway types.

Thank you Denis.
It's implemented already. You'll see it in the next major version.

**Comment by Zverik** [comment]
You can.
http://www.openstreetmap.org/way/38754931
![screenshot_2016-07-18-13-55-46](https://cloud.githubusercontent.com/assets/766031/16912849/cbd9b80c-4cf7-11e6-9b50-65e5898563ca.png)

**Comment by DenisCarriere** [comment]
Awesome stuff! I'll make sure to update the app. :)
