### ISSUE TITLE
How do I install android sdk version 22?

### ISSUE THREAD

**Issue by krisk0** [mapsme/omim#3789]
I am trying to build Android version under Gentoo Linux.

I tried omim-android-release-603 and latest omim (stamped 14 july 21:20, sha1=85302cc).

Both want android sdk version 22. INSTALL.md suggests that I use sdk-update-manager.

However sdk-update-manager only offers version 23 and 24. I found android-22_r02.zip which probably contains sdk version 22.

So how do I install android-22_r02.zip?

**Comment by utack** [comment]
When you download Android studio, at some point after the initial setup it offers to open a "Standalone SDK manager". This is where you find a complete list of everything

**Comment by trashkalmar** [comment]
Question is not related to maps.me app.
