### ISSUE TITLE
compilation failure: illegal max(float,double) in drape_frontend/text_layout.cpp

### ISSUE THREAD

**Issue by krisk0** [mapsme/omim#3807]
I managed to natively build **MAPS.ME** executable on a Gentoo/x86_64 desktop.

I had to solve some problems one of which is described below.

In line 563 of **drape_frontend/text_layout.cpp** expression `max(floor(pathLength / minPeriodSize), 1.0)` is evaluated. This expression takes max(float,double) which is not supported by C++11 dialect. The line does not compile with clang 3.8.0-r3.

I fixed the issue by converting 1.0 to float:
```
sed -re 's:1\.0[)]:1.0f):' -i drape_frontend/text_layout.cpp
```
I suggest that MAPS.ME team fix **text_layout.cpp**.

**Comment by ygorshenin** [comment]
Agree, had the same problem when tried to build our project with clang3.9.2.

15 июля 2016 г. 21:58 пользователь "Денис Крыськов" <
notifications@github.com> написал:

**Comment by rokuz** [comment]
Hi, thank you for reporting. You can fix it by yourself, just cast return-type of floor to double. PR is appreciated.
