### ISSUE TITLE
Incorrect documentation: wrong maps location for desktop version

### ISSUE THREAD

**Issue by krisk0** [mapsme/omim#3809]
Before diving into **MAPS.ME** sources I thought that it should be useful as offline map browser.

There are many problems preventing desktop version of **MAPS.ME** from being useful in that sense.

One of the problems is incorrect documentaion. **docs/INSTALL.md** says that desktop version should take maps from `~/Library/Application Support/MapsWithMe`. My experiments show that it does not. 

I used **strace** utility.  **strace** logs show that **MAPS.ME** does not attempt to access the directory. Instead **MAPS.ME** takes maps from  `$HOME/.local/share/MapsWithMe`.

At this point I stop my experiments with desktop version of **MAPS.ME** and do not plan any new bug-reporting activity.

**Comment by Zverik** [comment]
Well of course the path is different on Linux. Everyone here uses macs, so we wrote a path to macs' shared folder. Also, you don't have to use strace, all path are printed in a console when the program starts.

Sorry you had to stop so early.
