### ISSUE TITLE
Change the suggested list of countries maps to download

### ISSUE THREAD

**Issue by gisaia** [mapsme/omim#3969]
Hi everyone, 
I am using the app in a specific limited area, and I want to limit the list of the countries maps that are suggested to download in the app. 
I attach a photo to show the list I am talking about .
Any idea about how can i do this ? 
Thank you very much guys ! 
![countries_list](https://cloud.githubusercontent.com/assets/20204404/17440543/54bec886-5b2d-11e6-9831-03cbd7893768.png)

**Comment by iphonic** [comment]
Hi any way to do this, I tried to modify the countries.txt but it doesn't work properly, is there any specific structure to follow to remove an entry for country?

Thanks.

**Comment by tatiana-yan** [comment]
World.mwm comes with app. If you want to see some smaller area you need to generate own small World.mwm (e.g. for single city). See https://github.com/mapsme/omim/blob/master/docs/MAPS.md 

There is no simple way to remove a single country cause we have no option "no country at this part of world".

**Comment by iphonic** [comment]
@tatiana-yan That is understandable, but we have a list of countries defined in the source code, I am referring to that may be modifying that will reduce the list of countries, check some of the defined data in the file..

**countries_meta.txt**

>

>  {
> "Abkhazia": {
>  "languages": ["ab", "ru"]
> },
> "Afghanistan": {
>  "languages": ["ps"]
> },
> "Albania": {
>  "languages": ["sq"]
> },
> "Algeria": {
>  "languages": ["ar"]
> },
> "Andorra": {
>  "languages": ["ca"]
> },

and file **countries.txt**

> {
>  "id": "Countries", 
>  "v": 190314, 
>  "g": [
>   {
>    "id": "Abkhazia", 
>    "s": 6222053, 
>    "sha1_base64": "LgD3tOwGbuMG3ojCfVr92vwQoyM=", 
>    "old": [
>     "Georgia"
>    ], 
>    "affiliations": [
>     "\u0410\u0431\u0445\u0430\u0437\u0438\u044f - \u0410\u04a7\u0441\u043d\u044b", 
>     "\u10d0\u10e4\u10ee\u10d0\u10d6\u10d4\u10d7\u10d8\u10e1 \u10d0\u10d5\u10e2\u10dd\u10dc\u10dd\u10db\u10d8\u10e3\u10e0\u10d8 \u10e0\u10d4\u10e1\u10de\u10e3\u10d1\u10da\u10d8\u10d9\u10d0 - \u0410\u04a7\u0441\u043d\u044b \u0410\u0432\u0442\u043e\u043d\u043e\u043c\u0442\u04d9 \u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430", 
>     "\u10e1\u10d0\u10e5\u10d0\u10e0\u10d7\u10d5\u10d4\u10da\u10dd"
>    ]
>   }, 
>   {
>    "id": "Afghanistan", 
>    "s": 25506898, 
>    "sha1_base64": "IqTJXAVCNZ9RQzDzY+E+1TeciVQ=", 
>    "old": [
>     "Afghanistan"
>    ], 
>    "affiliations": [
>     "Badakhshan", 
>     "Badghis", 
>     "Balkh", 
>     "Baghlan", 
>     "Bamyan", 
>     "Daykundi", 
>     "Farah", 
>     "Faryab", 
>     "Ghazni", 
>     "Helmand", 
>     "Herat", 
>     "Jowzjan", 
>     "Kabul", 
>     "Kandahar", 
>     "Logar", 
>     "Kapisa", 
>     "Khost", 
>     "Kunar", 
>     "Kunduz", 
>     "Laghman", 
>     "Nimruz", 
>     "Nuristan", 
>     "Nangarhar", 
>     "Or\u016bzg\u0101n", 
>     "Paktia", 
>     "Paktika", 
>     "Panjshir", 
>     "Parwan", 
>     "Samangan", 
>     "Sar-e Pol", 
>     "Takhar", 
>     "Wardak", 
>     "Zabul", 
>     "\u0648\u0644\u0627\u06cc\u062a \u063a\u0648\u0631", 
>     "\u0627\u0641\u063a\u0627\u0646\u0633\u062a\u0627\u0646"
>    ]
>   },

I have tried to remove entries manually but it crashes the app..

Thanks.

**Comment by tatiana-yan** [comment]
You can not just modify the file cause any part of World.mwm must correspond some country. So if you need map just for some small area (only one country or single city) you need to generate another World.mwm . Here you can find an example how to do it for Caribbean Islands: https://github.com/mapsme/omim/blob/master/docs/MAPS.md
You can change it a bit to create maps for any region you want.
