### ISSUE TITLE
Make sure auto-backup doesn't sync large map files

### ISSUE THREAD

**Issue by patcon** [mapsme/omim#401]
As someone who spent time in bandwidth-restricted countries, I noticed you guys might be syncing map files, which presumably change pretty often with updates. Might be worth taking a more fine-grained approach to what gets included/excluded from the backup.

https://developer.android.com/training/backup/autosyncapi.html#include-exclude

**Comment by deathbaba** [comment]
Thanks for mentioning it. We already exclude map files on iOS, should do it on Android too.
@yunikkk @trashkalmar Will you check it out?

**Comment by yunikkk** [comment]
Currently we don't use neither autobackup API introduced in android 6.0 nor BackupAgent, so map files aren't backuped.
