### ISSUE TITLE
What is the difference between Beta and release Beta on http://osmz.ru/mwm/ ?

### ISSUE THREAD

**Issue by rancidfrog** [mapsme/omim#4069]
What are the differences between the two _Nightly builds_  ?

- **Beta: mwm.apk** 
- **release Beta: mwm_release.apk**

**Comment by Zverik** [comment]
Beta and Debug are built from the `master` branch. Release Beta is built from the current `release` branch, which is `release-63` for now.

**Comment by rancidfrog** [comment]
Thank you
