### ISSUE TITLE
Compile error: use of undeclared identifier 'strcmp'

### ISSUE THREAD

**Issue by ackalker** [mapsme/omim#4107]
Building from Git master on Arch Linux x86_64, clang 3.8.1, after a quick workaround for #4106, I'm getting the following error:

```
clang++ -c -pipe -fdata-sections -ffunction-sections -march=x86-64 -mtune=generic 
-pipe -fstack-protector-strong -O3 -ffast-math -g -fPIC -std=gnu++11 -Wall -W -Wno
-sign-compare -Wno-strict-aliasing -Wno-unused-parameter -Wno-unused-local-typedef
 -Wno-sign-conversion -Werror=return-type -D_REENTRANT -DRELEASE -D_RELEASE -DNDEBUG -DQT_NO_DEBUG -I. -I.. -I../3party/boost -I../3party/glm -I../3party/protobuf/src -I../3party/expat/lib -I../3party/freetype/include -I/usr/lib/qt/mkspecs/linux-clang -o ../out/release/tmp/drape_frontend/follow_animation.o animation/follow_animation.cpp
In file included from animation/follow_animation.cpp:4:
./animation_system.hpp:47:39: error: use of undeclared identifier 'strcmp'
            (customType == nullptr || strcmp(anim->GetCustomType().c_str()...
                                      ^
1 error generated.
```

From looking at the `#include`s, I take it that none of them has the required line:
```c++
#include <cstring>
```

Perhaps it is better to replace C string comparison using `strcmp` with a C++ `std::string` comparison using `==`? This would eliminate the need to include `<cstring>`, but I haven't tested it yet. Could there be problems with character encodings? Please advise.

**Comment by ygorshenin** [comment]
Inclusion of
```c++
#include "std/cstring.hpp"
```
should help.

**Comment by ygorshenin** [comment]
I've just created https://github.com/mapsme/omim/pull/4116. Please, try to re-build the project after merge.

**Comment by ygorshenin** [comment]
https://github.com/mapsme/omim/pull/4121 has been merged. Please, try to re-build the project.

**Comment by ackalker** [comment]
@ygorshenin Yes, that fixed the build. Thanks :-)
