### ISSUE TITLE
Not allowed to select a favorite place or coordinate on the from field on Navigation

### ISSUE THREAD

**Issue by jadolg** [mapsme/omim#4122]
On the Android App I'm not able to select a favorite place or a specific coordinate on the from field on navigation. I wanted to use this when calculating a route and it lets me input a POI but not a favorite or a coordinate.

**Comment by homersimpsons** [comment]
As workaround you can select destination and then go to signets (favorites) select the one you want and choose 'start from'

**Comment by jadolg** [comment]
what if I want to navigate from one favorite to another?

**Comment by homersimpsons** [comment]
You repeat the same and choose 'go too' (or whatever is the translation)

**Comment by jadolg** [comment]
Thanks for your answer. It solved my doubt. Anyway I think favorite places should be searchable. I would love to see it as a feature.
Thanks again for your help

**Comment by homersimpsons** [comment]
Yes me too
