### ISSUE TITLE
interwiki.sql.gz missing from data dumps

### ISSUE THREAD

**Issue by eplt** [mapsme/omim#4135]
hi there. just been trying to use the builder.
the following file doesn't seem to be in the dump in the past 12 months. is it essential for the process? and how to work around it?

https://dumps.wikimedia.org/enwikivoyage/latest/enwikivoyage-latest-interwiki.sql.gz

**Comment by eplt** [comment]
just been digging around a bit more, is it the same as enwikivoyage-latest-iwlinks.sql.gz? if so, what else do i need to update in the code to get it parsed properly?

**Comment by kokoye2007** [comment]
still not fix or no change ?
