### ISSUE TITLE
"Send statistics" reactivated after upgrade

### ISSUE THREAD

**Issue by twzkxkan** [mapsme/omim#419]
Updated app from android-web-universal-release-5.0.3-150909 to android-web-universal-release-5.1.4-151016 and user tracking was re-enabled without my consent. Please respect user setting changes.

**Comment by deathbaba** [comment]
That's strange. How did you make an upgrade? Was old version uninstalled first or new one was installed over an old one?

**Comment by twzkxkan** [comment]
It was installed over the old one.

**Comment by trashkalmar** [comment]
@twzkxkan Thank you for report, it is known problem. We'll resolve this ASAP.
