### ISSUE TITLE
Crashes when started in flight mode

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#4204]
The app always crashes when I start it when flight mode is enabled. I've submitted several crash reports.

CM 13 (Android 6)

**Comment by thany** [comment]
Not seeing this problem in version 6.0.7 (which doesn't have those nasty bugs #4334 and #4333)

**Comment by rugk** [comment]
Well... I'd rather prefer to have this issue fixed in a new version. :smiley:

**Comment by thany** [comment]
Agreed of course. But I guess what I'm saying is, it's a bug that's been introduced recently. In, say, the past couple of months since my bugs were introduced as well, after which I felt the only way around was to downgrade.

**Comment by rugk** [comment]
Yes, all right. The bug is just not so serious for me to downgrade, as I do not use Maps.me so frequently in flight mode.
However it is annoying each time, I'll do.

@deathbaba Do you have any plan for fixing this?

**Comment by deathbaba** [comment]
CC @burivuh

**Comment by Alexuser1** [comment]
@rugk What device model do you have?

**Comment by rugk** [comment]
jfltexx

**Comment by rugk** [comment]
I cannot reproduce this issue with the latest version of maps me. It seems to be fixed.

**Comment by rugk** [comment]
I cannot reproduce this issue in the latest update.
