### ISSUE TITLE
map is stuck when double taping on multitask button on android Nougat

### ISSUE THREAD

**Issue by larfadin** [mapsme/omim#4252]
I'm using a nexus 5X with android Nougat.

One of the new functionality of the system is double taping on the multitask button to get back to the last app use.
With maps.me the map get stuck and it's impossible to move the map. I have to kill the application.

When just taping on the multitask bittpn and then select the maps.me app it works.

**Comment by mrgluek** [comment]
Can confirm that!

Nexus 5X with latest Android 7 (NRD90R).
Maps.me from Play Market, version 6.3.7-Google

**Comment by larfadin** [comment]
it is now fixed in the android version delivered today
