### ISSUE TITLE
incremental map updates

### ISSUE THREAD

**Issue by Lemming0815** [mapsme/omim#4289]
Hi,
would it be in scope of the app to make map updates incremental? Or is this not supported by osm in general?
Meaning, If only little changed in a map tile, why do I have to download the entire recompiled tile and not only the information that has changed and have maps.me recompile the maps file itself?
some maps tend to be very big (>100mb) and also, if you have a lot of regions installed, updating them regularly means downloading many gigabytes of data with only a few megabytes worth of changes!

It would be awesome if the user could download only what has changed (especially when on route with a mobile plan) and save a lot of data traffic.
1. Is this in scope of maps.me?
2. Is this technically possible with osm content servers?

**Comment by homersimpsons** [comment]
I don't think it's possible because of Contraction hierarchy system. 
You, maybe, can take a look on what Osmand do with OSMlive.

**Comment by burivuh** [comment]
1) Yes, it is, but it is a long-term feature planning.
2) Yes, it is, maybe they won't be honestly incremental, but a target of much smaller updates than a full map file is technically possible. We've already done some experiments on the subject

**Comment by Lemming0815** [comment]
Anything I can help with?

**Comment by Locke** [comment]
I think this issue can be closed now since it's supported by now.

**Comment by jiuxs33** [comment]
Hi！
What are the steps？

**Comment by mpimenov** [comment]
> I think this issue can be closed now since it's supported by now.

Right.
