### ISSUE TITLE
Bookmark descriptions are singleline

### ISSUE THREAD

**Issue by thany** [mapsme/omim#4333]
Bookmark descriptions used to be friendly multiline fields. In the last update, they've become singleline. I sincerely hope this is an accidental unwanted change, because it basically destroys my experience with the app. It truly does.

I'm relying heavily on descriptions for my travels, to store extensive descriptions of places, along with opening times, admission fees, and other such information. Those things **need** the ability to enter newlines or it *will not be readable at all*.

So please, put this field back to being a multiline field.

**Comment by thany** [comment]
Can't say for sure, but in [this commit](https://github.com/mapsme/omim/commit/cbbcc5c2b3339c25f17ac5b344719488976bf5e2) a number of attributes appear to have been deleted from the bookmarks notes field, one or more of which may cause it to behave as a multiline field. So it isn't anymore.

**Comment by burivuh** [comment]
Fixed in 6.4.3

**Comment by thany** [comment]
The fix (for me at least) is pointless as long as you don't fix that other huge gaping problem, #4334

**Comment by thany** [comment]
Like I said... Any fix is pointless before #4334
