### ISSUE TITLE
Open coordinaters from another app doesn't work

### ISSUE THREAD

**Issue by redmanmale** [mapsme/omim#4344]
I don't know whether it's bug of MapsMe or not but if select location from Swarm app and open it with MapsMe, marker will be on your current position, not on selected location.
In other maps apps that works just fine.

Steps to reproduce:
![step_1-](https://cloud.githubusercontent.com/assets/6782721/18715270/5ccbb76e-8021-11e6-962d-51adc7d5e79b.jpg) ![step_2-](https://cloud.githubusercontent.com/assets/6782721/18715269/5cc2cee2-8021-11e6-9aad-dd00578297f6.jpg)

MapsMe v.6.3.7-Google, Swarm v. 2016.09.15.

**Comment by burivuh** [comment]
We've fixed several bugs with an application API in the upcoming release. Please, check this out using a 6.4 version next week

**Comment by redmanmale** [comment]
I checked out new version (6.4.3) and this bug is fixed.
