### ISSUE TITLE
about test Maps on an real device （ios）

### ISSUE THREAD

**Issue by cocoonbud** [mapsme/omim#436]
Hi, I am an IOS junior developer. Now the Maps project after configuration has been run on the Xcode Simulator. However I changed the Bundle Identifier and set up the code signing,  it cannot be run on a real device. Is there anything i should pay attention to?

**Comment by deathbaba** [comment]
Hi, to be able to help, we need to understand which exactly error do you get.

**Comment by simon247** [comment]
Hi deathbaba , i got this error :

No architectures to compile for (ARCHS=armv7 arm64, VALID_ARCHS=).

when install into the iPhone.

**Comment by deathbaba** [comment]
Which iPhone do you have? Is it an old one on armv6?

**Comment by simon247** [comment]
iPhone6  IOS9.1

**Comment by deathbaba** [comment]
Please check project’s settings for Valid Architectures. Each configuration, except Simulator, should include 3 archs: armv7, armv7s and amd64.
By some reason armv7s is missing in your project, and it does not work with iPhone6 (as it is running armv7s).

**Comment by simon247** [comment]
![image](https://cloud.githubusercontent.com/assets/3993689/10931006/8b3a7778-82fe-11e5-83d8-cd3dfd02a23b.png)

**Comment by deathbaba** [comment]
Very strange. Issue is definitely somewhere in project’s settings related to SDKs and architectures. You can try to change Build Active arch only to NO, and google for error you see.

**Comment by simon247** [comment]
Thank you @deathbaba.

**Comment by deathbaba** [comment]
Any luck?

**Comment by simon247** [comment]
Yes, need to create the Kits for IOS device on the Qt.

**Comment by deathbaba** [comment]
We do not support builds for iOS and Android from Qt. You should use XCode and gradle/Android Studio to build for mobile OSes. QT builds are desktop-only.

**Comment by simon247** [comment]
@deathbaba I mean need to add the IOS Device Kit Before build it with XCode.
