### ISSUE TITLE
Cannot find peak

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [mapsme/omim#4372]
I tried to find https://www.openstreetmap.org/node/1560025662 "Morro da conceição" but maps.me returned nothing.

**Comment by Zverik** [comment]
Worked for me in the latest android 6.4 release:

![screenshot_2016-10-03-18-48-00](https://cloud.githubusercontent.com/assets/766031/19043730/75c6a992-89a2-11e6-8a0f-0c564b7f5bed.png)
