### ISSUE TITLE
language edit is not in my native language anymore

### ISSUE THREAD

**Issue by larfadin** [mapsme/omim#4401]
I'm using a nexus 5X with android Nougat and the today android version of maps.me.
I have this issue since a month.
My phone is in french and the app was in france, so when editing the map I was able to search with the french name.

But since a month the app is in english and not in my native language anymore so it's a lot more difficult to search for a POI in english.

**Comment by burivuh** [comment]
Hi!
1) Please specify how is map editing related to your searches?
2) Is all the GUI in English for you now?

**Comment by larfadin** [comment]
All the GUI is in french except the edit GUI.
Sorry I didn't understand your first question

**Comment by larfadin** [comment]
It's working again with the last update
