### ISSUE TITLE
Maps from regular/daily/ seems to be incomplete

### ISSUE THREAD

**Issue by jalvesaq** [mapsme/omim#4423]
Some maps from http://direct.mapswithme.com/regular/daily/ are much smaller than the ones from http://direct.mapswithme.com/direct/latest/

For example, Brazil_Northeast Region_West.mwm  has 65796965 bytes in the `latest` directory and only 17336960 bytes in the `daily` directory.

**Comment by Zverik** [comment]
Found the source of the bug and restarted the daily planet. In 25 hours you'll see proper mwms. Sorry for that.

**Comment by jalvesaq** [comment]
Thanks! It's fine now.
