### ISSUE TITLE
Empty changesets

### ISSUE THREAD

**Issue by tyrasd** [mapsme/omim#4426]
Here's an example of an empty changeset created by maps.me: https://www.openstreetmap.org/changeset/42578474

**Comment by Zverik** [comment]
Alas, we cannot do anything about that. An empty changeset means a user has lost their internet connection, or the app was terminated by Android OS, while uploading changes. We don't create changesets if there are no changes. I assume this is a rare occasion, usually the app manages to upload some changes before being terminated.

**Comment by tyrasd** [comment]
Oh yes, that makes sense! (one can see in the [changeset xml](https://www.openstreetmap.org/api/0.6/changeset/42578474) that it was open for a full hour.)

**Comment by it4workflow** [comment]
> I assume this is a rare occasion,

[23 empty changsets](http://api.openstreetmap.org/api/0.6/changesets?display_name=Mohamed%20Chiekh%20Mohamed) in a couple of minutes ... ?!
