### ISSUE TITLE
Zoom buttons disappear

### ISSUE THREAD

**Issue by redmanmale** [mapsme/omim#4434]
Before I start celebrating fix of #4344, another bug jumped out.
After opening any point via MapsMe zoom buttons disappear:
![no_controls](https://cloud.githubusercontent.com/assets/6782721/19048934/06177ed2-89b1-11e6-9eeb-e3e49cda3168.jpg)

And the only way to get them back is to tap any other point, leaving the point you looking for.

MapsMe v.6.4.3-Google.

**Comment by burivuh** [comment]
We're checking this bug, thx

**Comment by redmanmale** [comment]
Bug's still here (v.6.4.4-Google). Any chance of fix?

**Comment by redmanmale** [comment]
They disappear from each even tap on non-POI place on the map.

**Comment by redmanmale** [comment]
It's been over a month. Any progress at this one?

**Comment by redmanmale** [comment]
v.6.5.2-Google. Nothing has changed.

**Comment by redmanmale** [comment]
v.7.0.5-Google. ...

**Comment by redmanmale** [comment]
Still not fixed in v.7.1.3-Google.
It's very annoying bug.

**Comment by redmanmale** [comment]
It seems to be fixed in v.7.1.4-Google.
