### ISSUE TITLE
Why has all bloat been added to app?

### ISSUE THREAD

**Issue by rancidfrog** [mapsme/omim#4435]
To name a few,
```
compile 'com.facebook.android:facebook-android-sdk:4.8.0'
  compile 'com.pushwoosh:pushwoosh:4.6.3'
compile 'com.my.tracker:mytracker-sdk:1.3.2'
```
and soon ADs #4396 ?

**Comment by burivuh** [comment]
I'm sorry, but this is not a technical issue.
Please use any of the stripped forks/mods available.

**Comment by Zverik** [comment]
Because we are a commercial company, and instead of paying money you agree to be a part of our statistics. Ads can (and should) be disabled via the settings menu.
