### ISSUE TITLE
Disable reminder to rate app in web release

### ISSUE THREAD

**Issue by twzkxkan** [mapsme/omim#444]
Users who download your [web release](https://maps.me/apk/) likely don't have access to the Play Store, so the occasional reminders to rate the app aren't useful.

**Comment by deathbaba** [comment]
But you never know, right? It is not a blocker for the app itself. May be simply change link to something else?

**Comment by twzkxkan** [comment]
>May be simply change link to something else?

As long as there is some way to make the pop ups stop. I would give you stars if I could, but for now this is the only way I know.
:star::star::star::star::star:

Is there a way to tell if a user doesn't have the Play Store installed? I realize users like me are 0.0001% of  total so maybe it is not worth your time.

**Comment by deathbaba** [comment]
Yeah, it is a good idea to check if GP is installed. @yunikkk what do you think?

**Comment by trashkalmar** [comment]
I'm agree too. I think we should check GP availablilty regardless of build type (web or google).

**Comment by yunikkk** [comment]
GP might be not installed, while user still can open the url in web browser and like the app.
