### ISSUE TITLE
run build_omim.sh error

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#451]
An error occured while run omim/tools/unix/build_omim.sh
/opt/rh/devtoolset-2/enable: line 2: MANPATH: unbound variable
How to solve it?
OS is centos, Clang, Qt 5 has been installed

**Comment by xingdavis** [comment]
![image](https://cloud.githubusercontent.com/assets/11851006/10967231/fd8c1f48-83f3-11e5-8d36-0e4408c1f91d.png)

**Comment by Zverik** [comment]
Ah, that's what that `MANPATH=` was for :)
For now, you can add `export MANPATH=` to `build_omim.sh` anywhere near BOOST_PATH, before devtoolset invocation. I'll make a pull request to fix this in some hours.

**Comment by xingdavis** [comment]
thanks Zverik !

**Comment by xingdavis** [comment]
Hello Zverik,this time I get the fix code to run again, and there's another problem.


/opt/rh/devtoolset-2/enable: line 16: rpmlibdir32: unbound variable

**Comment by xingdavis** [comment]
![j ega yqqv l 1vqzbcnf6](https://cloud.githubusercontent.com/assets/11851006/10989025/244124f6-847d-11e5-8de5-adf39051de8d.png)

**Comment by Zverik** [comment]
Interesting, I've got this variable set.
Do the same: add an `export rpmlibdir32=` line.

**Comment by xingdavis** [comment]
Is this setting?
export rmplibdir32=/usr/lib

Then it seems to be missing some files.

![qq 20151109122036](https://cloud.githubusercontent.com/assets/11851006/11025895/93f22dd4-86dc-11e5-86a3-82f252db76a9.png)

**Comment by deathbaba** [comment]
Do you have libstdc++ or libc++ installed?

**Comment by xingdavis** [comment]
Hello, I have checked, it should be installed.
![qq 20151110100543](https://cloud.githubusercontent.com/assets/11851006/11052453/fedab984-8792-11e5-8935-d16fcb8516cd.png)

**Comment by deathbaba** [comment]
clang++ is not itself a libstdc++, algorithm header is a part of standard C++ library, and on most systems it should be installed separately.
