### ISSUE TITLE
(IOS issue) private.h #define DEFAULT_URLS_JSON  crash

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#459]
For IOS Issue:
When I set DEFAULT_URLS_JSON with "http://direct.mapswithme.com/direct/latest/" in the private.h file, the App crash

![image](https://cloud.githubusercontent.com/assets/3993689/10992137/17938610-849e-11e5-9867-ba7b23f21729.png)

**Comment by deathbaba** [comment]
In general, you should not do this. Do not use our direct server in your builds, as it is used by our users, please generate your own maps and put them into your own server.

**Comment by simon247** [comment]
but it should not be crashed even if used "http://direct.mapswithme.com/direct/latest/" for the DEFAULT_URLS_JSON

**Comment by deathbaba** [comment]
We do not validate json in runtime - there is no any reason for it, as it is built-in by developer. Check the real reason of crash and fix it, if it is invalid json file format.
