### ISSUE TITLE
[Android] Search from external app

### ISSUE THREAD

**Issue by David-Guillot** [mapsme/omim#470]
Hi,

When I'm Contacts or Calendar, I have the possibility to click on an address to search it in a map application. With MAPS.ME configured as my default map application, it just opens the app, says "Dropped pin" and places me in the Atlantic Ocean.

Did I mis-configured something? Or is it just not supported for now?

I'm on Android 5.0.2 (Cyanogenmod 12), with MAPS.ME 5.1.4 webrelease.

Thanks!

**Comment by deathbaba** [comment]
It’s a known bug. We do not support “searching” by address from contacts yet, but probably do it in the future.

**Comment by David-Guillot** [comment]
Ok thanks for your quick answer ; do you prefer i close the ticket as it's a known issue, or I leave it open as a reminder to support this feature?

**Comment by deathbaba** [comment]
I suppose we can leave it open and may be rename to “Known issue/Feature Request”, so others can vote it up amongst other features.
