### ISSUE TITLE
[Feature request] Search by GPS coordinates

### ISSUE THREAD

**Issue by Peter2121** [mapsme/omim#471]
It would be nice to be able to search places using their GPS coordinates (like in iGO).
Some applications (and web sites) are already using GPS coordinates to indicate the position of places (for example, Booking.com). As a start point - the implementation like in HERE could be used (just scan coordinates from the search string, put in a pre-defined format). A separate tab with a possibility to change default coordinates format would be better though.

**Comment by deathbaba** [comment]
1. Clicking on coordinates now changes their format.
2. You can copy coordinates into a search box and we’ll find them on the map.

**Comment by Peter2121** [comment]
OK, so the start point (like in HERE) is already realized (it's just the default format which is not the same).
But it would be nice to see a separate search page for such request (two input fields for LAT and LON and a button to change formats at the same page).
Note that sometimes one uses a format of coordinates that you don't support yet: DD°MM.mmm'

**Comment by deathbaba** [comment]
We are  strictly against separate complex UI just for coordinates. But you can add support for new coordinates format easily into an existing search, and into current UI.
Search support is here: https://github.com/mapsme/omim/blob/master/search/latlon_match.cpp <https://github.com/mapsme/omim/blob/master/search/latlon_match.cpp>
Formatting is here: https://github.com/mapsme/omim/blob/master/platform/measurement_utils.cpp <https://github.com/mapsme/omim/blob/master/platform/measurement_utils.cpp>
After it’s done, add new additional format into UI is an easy task.
