### ISSUE TITLE
Allow one to use 24h format for arrival time

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#4755]
The arrival time shown in routing move currently uses am/pm. It should however best honor to the system settings and use 24h format without am/pm.

**Comment by Zverik** [comment]
Are you sure your system is set up to show 24h time? Try installing the latest version and please check again.
![screenshot_2016-11-21-11-11-47](https://cloud.githubusercontent.com/assets/766031/20475199/e807f292-afe3-11e6-8896-fa5e45d83835.png)

**Comment by akudzo** [comment]
I used to have the same problem. Android was set to 24h clock. Setting it to am/pm and back to 24h solved the problem for me. 
Unfortunately, I can't reproduce the error anymore.

**Comment by rugk** [comment]
Yes my system is set to 24h. I might try @akudzo's workaround if needed.

**Comment by legovini** [comment]
Here it's showing the arrival time in 24h format, but I remember seeing in 12h am/pm (which I hate). I didn't change the Android setting, still it seems to be fixed now.

**Comment by rugk** [comment]
Okay, so I am closing it.
