### ISSUE TITLE
Non existing address is searchable

### ISSUE THREAD

**Issue by Jurkis** [mapsme/omim#483]
Search for two addresses:
1. Klaipėda Baltikalnio 10.
2. Klaipėda Bangų 10 
After search the same building no. 10 is assigned to those different addresses (see attach.). But there is no such building Baltikalnio 10 on openstreeetmaps.org at all.
![baltikalnio_10](https://cloud.githubusercontent.com/assets/8310079/11056625/7bf2a10e-878c-11e5-8536-e2b5d0e12041.png)
![bangu_10](https://cloud.githubusercontent.com/assets/8310079/11056630/7fb5ea9e-878c-11e5-8d61-148c9123b3d9.png)

maps.me version 5.1.8.

**Comment by deathbaba** [comment]
Thanks for reporting this bug! When we finish geocoder in our new search engine, it should work correctly.

**Comment by Jurkis** [comment]
I've tested, works fine. Thank you.
