### ISSUE TITLE
Improvement: Manually daily map updates

### ISSUE THREAD

**Issue by OSMmapper** [mapsme/omim#4843]
Is it possible to include a way to update the map manually with the daily exports (http://direct.mapswithme.com/regular/daily/) and not only with app updates?

Its very inconvenient to update it always via usb.

**Comment by thany** [comment]
I think the main reason is because your suggestion would impose a LOT of traffic on the mapse.me servers.

Another reason is probably that maps simply don't have enough significant updates on a daily basis, to make daily updates a worthy effort. Not counting exceptions, of course.

**Comment by burivuh** [comment]
There are some plans (2017) to implement:

1) Application independent map update system
2) Diff-based weekly/daily updates

In its current state daily updates from the /direct aren't that helpful for the most users. So we will not implement what you ask in this form.
