### ISSUE TITLE
MAPS.ME appears to be monitoring my location even when I'm not using it

### ISSUE THREAD

**Issue by SomeoneElseOSM** [mapsme/omim#4866]
The phone is a Blackberry DTEK50, model STH100-2, Android version 6.0.1.  MAPs.ME version is 6.5.4-Google, Data version 161123.

According to the security software on the phone (confusingly also called "DTEK") MAPS.ME accessed my location at 7:23 this morning.  I wasn't using it at the time, and it wasn't running (neither in the list of running services nor cached processes), though Google Play Services was.

Obviously there are a couple of possibilities here, including misreporting and Google Play Services continuing to track location as requested but MAPS.ME no longer being around, but could someone confirm what is the expected behaviour here?  From a user point of view is there a way to prevent MAPS.ME requesting location information when it is not in use?  

I'm aware of reports such as http://www.theregister.co.uk/2016/09/12/turn_off_location_services_go_ahead_says_google_well_still_track_you/ so Google Play Services is a different issue.  Could anyone from MAPS.ME confirm that the Google Play version of MAPS.ME does use Google Play Services rather than native Android GPS / cell site location, and if so why?

**Comment by burivuh** [comment]
I can confirm that our app is monitoring GPS in the background. It is done rarely and used for creating a notification about possible map download if a user has changed his previous city/town location.

For now we have no setting to disable this behavior.

**Comment by SomeoneElseOSM** [comment]
Thanks for that - re the Google Play Services vs native GPS / cell site location question, is that something that differs between distributions (e.g. to the Google Play Store vs Amazon's store, where most devices won't support Google Play Services), or is the Google Play Store version the only up-to-date Android version now?

**Comment by burivuh** [comment]
As far as I can remember this behavior is enabled on all our distributions.
And yes, the most up-to-date version is guaranteed only for Google Play.

**Comment by SomeoneElseOSM** [comment]
Great - thanks.
