### ISSUE TITLE
Windows version, OSX version

### ISSUE THREAD

**Issue by thany** [mapsme/omim#4884]
Can we please have a Windows version, and for those, an OSX version?

I can't find Mapse.me in the Windows Store, nor can I find a downloadable program. As for OSX, there is an AppStore version, but I suspect it's the iOS version. I haven't checked.

It shouldn't be too awfully hard to recompile for these platforms, should it? The bulk of the app can stay identical anyway. It's just some GUI guff around it.

**Comment by burivuh** [comment]
Hi!

Actually it is VERY expensive to develop and support Win version. Even OSX will cost us a lot.

Our position (for now) - it is not worth an effort.

Though, any outside developer can try to do that.

**Comment by thany** [comment]
Why is it expensive? Last time I checked, it didn't cost me anything.

**Comment by burivuh** [comment]
We have other evaluations. Though, feel free to implement and support any of these platforms by yourself.

**Comment by thany** [comment]
You still haven't told me how it's so expensive. I thought the Store was free to publish programs on? At least if the program itself is free as well?

**Comment by thany** [comment]
Complete radio silence. That's how you usually play.
