### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by nighto** [mapsme/omim#493]
Hello, how can I help to translate Maps.me to other languages? I'm interested in translating it to brazilian portuguese. Thanks.

**Comment by deathbaba** [comment]
Hi, we have several translation files:
* App interface: https://github.com/mapsme/omim/blob/master/strings.txt
* Display name for each map type (first value) and search synonyms (number means how many letters to type before hint appears) https://github.com/mapsme/omim/blob/master/data/categories.txt 
* Directions https://github.com/mapsme/omim/blob/master/sound/tts/sound.csv

You can create change request with pt-BR translations (we probably need some minor code changes to correctly support it, but it is feasible).

**Comment by ovidiub13** [comment]
Have you considered using transifex, or pootle for translations?

Most open source projects use these, or other Web tools for better interaction with the community.

**Comment by deathbaba** [comment]
We have analyzed these platforms. They looks useful, but the most pain is migration and setup of a whole environment, build automatization and testing included.
As we have some specific formats now (check data/categories.txt - search synonyms) code also should be rewritten.

Another issue is that every OS has it’s own localization mechanism, and our C++ core code should access it too. And it makes translations usage even more complex.

If you see how we can effectively migrate MAPS.ME to any good localization platform, you’re always welcome to help.

**Comment by iriman** [comment]
Hi, could you provide strings.txt as a spread sheet file? It's really a pain for translators to maintain it. There are some tools (for example [see this](https://github.com/steven-martins/Ini2Csv)) to convert this txt to csv and then importing to a spread sheet (I think google sheets will do import/exporting best in regard to unicode compatibility).

It will benefit translators by options like filtering, searching, etc to provide a more consistent work. 

Thanks
