### ISSUE TITLE
Map flickers after zooming

### ISSUE THREAD

**Issue by BHSPitMonkey** [mapsme/omim#494]
(Version 5.1.8-Google on Android 6.0)

Whenever the map is zoomed in or out, the canvas tends to flicker a bright color before redrawing the map. This could be probably be improved by maintaining the previous bitmap texture and drawing over it.

**Comment by deathbaba** [comment]
Our new rendering engine (see drape-2.0 branch) should behave differently. You can check experimental build here: https://www.dropbox.com/s/16jy1adtjxf08kh/android-google-universal-release-5.1.5-151106_drape.apk?dl=1 <https://www.dropbox.com/s/16jy1adtjxf08kh/android-google-universal-release-5.1.5-151106_drape.apk?dl=1>
