### ISSUE TITLE
Could not find qmake configuration file

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#4969]
I build maps follow the compilation instructions,
"CONFIG=gtool omim/tools/unix/build_omim.sh -cro"
has been interruptedget at:
Could not find qmake configuration file CONFIG+=release osrm.
Error processing project file: /data/map_build/code_161205/omim/omim.pro

envinoments:
QMake version 3.0
Using Qt version 5.7.0 in /opt/qt57/lib
gcc version 4.9.4
Ubuntu clang version 3.6.0-2ubuntu1~trusty1

**Comment by Zverik** [comment]
Fixed in `release-70` branch, soon to be merged into `master`.
