### ISSUE TITLE
Basic run fails

### ISSUE THREAD

**Issue by iphonic** [mapsme/omim#5064]
Hi, We were trying to use the source code for iOS, we successfully build it and ran it. We later found that we need to do extra URL assignment in **private.h** so we added following

```
#define METASERVER_URL "http://direct.mapswithme.com/direct/"
#define DEFAULT_URLS_JSON "http://direct.mapswithme.com/direct/latest/countries.txt"
```

After adding **DEFAULT_URLS_JSON** to **countries.txt** which is actually a json we got all the list of Maps successfully and all search worked great. 

Then when we tried to Download a Map we encountered the following error,

`platform/servers_list.cpp:30 ParseServerList() Can't parse server list json: 1 '[' or '{' expected near 'http' http://direct.mapswithme.com/direct/latest/countries.txt`

The source code was working fine till I tapped on **Download Map**, and too we want to make the source code work before we setup our servers, so we are using **http://direct.mapswithme.com/direct/ to METASERVER_URL** which is not looking promising, can you please guide us to get it working with the default things available?

Thanks, and Great work.

**Comment by Zverik** [comment]
Hi,

The second define should be a JSON string, like this: `"[\"http://...\"]"`.
And the servers at mapswithme.com are for the official applications builds, that's why we tend to hide the list. If you intend on making a public, downloadable by anyone build, we'd be thankful if you hosted the map files on your server.

**Comment by iphonic** [comment]
@Zverik Thanks it works. Please include this in your HELP doc for others.

**Comment by mmohiahmed** [comment]
Thanks guys! Issue resolved
