### ISSUE TITLE
WiFi category broken depending on language/translation

### ISSUE THREAD

**Issue by jancborchardt** [mapsme/omim#5070]
When searching via category, there’s an issue with the translations:
- The actual working search string is `wifi` or `WiFi` or `WLAN` it seems.
- But the label of the category, which is translated, is used as the search string.

This results in the category working for [German](https://github.com/mapsme/omim/blob/master/iphone/Maps/LocalizedStrings/de.lproj/Localizable.strings#L659) and [French](https://github.com/mapsme/omim/blob/master/iphone/Maps/LocalizedStrings/fr.lproj/Localizable.strings#L659), but **not** for languages where it is translated slightly differently like [English `Wi-Fi`](https://github.com/mapsme/omim/blob/master/iphone/Maps/LocalizedStrings/en.lproj/Localizable.strings#L659), [Swedish too](https://github.com/mapsme/omim/blob/master/iphone/Maps/LocalizedStrings/sv.lproj/Localizable.strings#L659), [Korean `WiFi 인터넷`](https://github.com/mapsme/omim/blob/master/iphone/Maps/LocalizedStrings/ko.lproj/Localizable.strings#L659) and many more …

This issue occurs on both Android and iOS.

I wasn’t sure if it should be fixed in the individual translation files, or something like `en:WiFi|Wi-FI` could be added to the [data/categories.txt](https://github.com/mapsme/omim/blob/master/data/categories.txt#L5567).
If you give me the pointer I would be happy to submit a pull request.

I guess the fix in the translation files will work, however that would be dirty since then the label is not properly translated. Search string and label should hence be separated.

**Comment by mpimenov** [comment]
Thanks for noticing that.

You got it right for the most part: omim/data/categories.txt stores the strings that are used in search and editor and omim/strings.txt stores translations that are used in the UI. The individual translation files are generated automatically.

Regardless of what is shown in the UI, "Wi-Fi" is a valid synonym to be used in search, so I added it in #5077.

**Comment by jancborchardt** [comment]
Thanks @mpimenov! :)
