### ISSUE TITLE
New support for OpenTable makes it impossible to edit business details

### ISSUE THREAD

**Issue by derickr** [mapsme/omim#5082]
Hi!

yesterday I wanted to add postcode, cuisine and opening hours to a restaurant, but maps.me wouldn't let me because the restaurant was on OpenTable and its GUI popped up. It wouldn't even allow me to *see* this information either. 

Luckily, everything was already mapped: http://www.openstreetmap.org/way/182651296

cheers,
Derick

**Comment by Zverik** [comment]
Sorry for that, I'm fixing it in #5145.
