### ISSUE TITLE
Crash when scrolling to the bottom of the country list

### ISSUE THREAD

**Issue by utack** [mapsme/omim#5093]
When scrolling all the way down to "Österreich" in the county list, the app crashes  
Tested with 6.5.2 on Android 7.1 and another device with 7.0.5 on Android 6
Maybe specific to German locale?

**Comment by alexzatsepin** [comment]
@utack Hey! Thanks a lot for reporting the problem. Can you provide a crash dump or a snippet of logs?

**Comment by utack** [comment]
@alexzatsepin 
sorry for the long response time

> 12-29 18:09:22.932 11867 11867 E DownloaderAdapter: Index 224 is out of bounds, mItem.size = 224, current thread = Thread[main,5,main] mNearMeCount = 0, ads count = 1, showAds = true, mAdsLoaded = true, mAdsLoading = false mSearchResultsMode = false, mSearchQuery = null mHeaders.size = 25 mHeaders = {85=A, 86=B, 87=C, 88=D, 89=E, 90=F, 91=G, 92=H, 93=I, 94=J, 95=K, 96=L, 97=M, 98=N, 99=O, 100=P, 102=R, 103=S, 104=T, 105=U, 106=V, 107=W, 110=Z, 216=Ä, 234=Ö}
12-29 18:09:22.933 11867 11867 I DownloaderAdapter: last county item in position = 223 = { id: "Austria", directParentId: "Countries", topmostParentId: "null", category: "2", name: "Österreich", directParentName: "Countries", topmostParentName: "null", present: false, status: 6, errorCode: 0, headerId: 234, size: 0, enqueuedSize: 0, totalSize: 446381860, childCount: 0, totalChildCount: 11, progress: 0% }
12-29 18:09:22.934 11867 11867 D AndroidRuntime: Shutting down VM  
  
More from logcat:
[countrylistcrash.txt](https://github.com/mapsme/omim/files/677554/countrylistcrash.txt)

Thanks for looking into it

**Comment by alexzatsepin** [comment]
@utack no worry about response time. Thanks for logs. I have additional questions:

1. Does this crash reproduce always or randomly?
2. Can you provide me steps to reproduce, as detailed as you can?

Thanks for your help

**Comment by utack** [comment]
Can't reproduce it any more, hope it is fixed
