### ISSUE TITLE
Route calculation in 7.0.5 has major issues

### ISSUE THREAD

**Issue by utack** [mapsme/omim#5094]
When calculating routes in 7.0.5 with 161214 maps, things go poorly

- The progress circle is resetting a lot, and it is slow

- It results in a route that seems to ignore highway speed limits (one 500km route went from 4:05h to ~9:30h travel time estimate, another time it avoids the highway and goes through the inner city)

- often it gives an error saying it can not find a route
**Edit**: this point is fixed

This also happens offline (as seen in logcat), so it has nothing to do with traffic data
Logcat:
[routelogcat.txt](https://github.com/mapsme/omim/files/672385/routelogcat.txt)

Let me know if you need any more details please, logcat or anything else
Thanks for having a look at the problem

**Comment by Alexuser1** [comment]
Hello @utack!
Can you please to provide sample route coordinates (start and finish points) for second error?

**Comment by utack** [comment]
@Alexuser1 check the logcat
I routed from 
https://www.openstreetmap.org/way/130469169
to
https://www.openstreetmap.org/node/3561623062

But if you like, I can find examples that are on the scale of just one map, about 20km apart

**Comment by akudzo** [comment]
Another example, from 11.568268, 104.922429 to 13.345259, 103.85418. Multiple resets in routing, and the calculated route is wrong. No traffic data available in this region. 
Another example, multiple resets during routing and it seems like it's avoiding the major highways for some reason. From 11.568268, 104.922429 to 10.622038, 103.522315

**Comment by Norbert80** [comment]
I see the resetting progress circle too since OSRM has been replaced.

**Comment by vvug** [comment]
Me too... What was OSRM replaced with? I can't find any precise information about this.

**Comment by dr4Ke** [comment]
Wrong calculations for me too with 7.0.5-Google with longer routes. Bad with: 48.7852, 2.0645 to 48.7790, 2.1679

![bad](https://cloud.githubusercontent.com/assets/128122/22205630/fa3e40f4-e177-11e6-99a3-04144c6bc522.png)

Detail:
![bad detail](https://cloud.githubusercontent.com/assets/128122/22206063/ec687a4c-e179-11e6-8d5b-3b69499c430f.png)


Using a shorter route, the calculation is good: from 48.7937, 2.1253 to 48.7790, 2.1679
![good](https://cloud.githubusercontent.com/assets/128122/22205641/086db3ee-e178-11e6-949a-5d24a50eb548.png)

Detail:
![good_detail](https://cloud.githubusercontent.com/assets/128122/22206072/f1febdae-e179-11e6-96ef-77457d16c863.png)

**Comment by utack** [comment]
7.1.1 does fix the troube where it could not find routes

However it is still quite slow to calculate, and the routing times are still off by a factor of almost 2 on highways here

**Comment by Codain** [comment]
Same issue with duration which have nearly doubled. See https://github.com/mapsme/omim/issues/5164#issuecomment-275623343

**Comment by stephan75** [comment]
On may Motorola Moto G peregrine I have app version 7.1.4-Google,

and for two or three month I have wrong time display about remaining to target (EAT):

The app shows a realistic time when starting a navigation, e.g. 15 minutes, but soon the duration is decreased to one minute although real time ist still six or five minutes.

Can anyone reproduce?

(recent offline maps from Germany-Niedersachsen)

**Comment by utack** [comment]
@stephan75 yes:
https://twitter.com/MAPS_ME/status/837617245312417792

**Comment by stephan75** [comment]
ahhh, thanks ... I was not aware of that twitter topic.

**Comment by utack** [comment]
This is actually fixed entirely, thanks to all developers
