### ISSUE TITLE
METASERVER_URL is empty hence >> Connection failed unsupported URL >> ASSERT FAILED

### ISSUE THREAD

**Issue by mmohiahmed** [mapsme/omim#5096]
Cloned the omim and managed to build and run in iPhone simulator. As soon as I zoom-in to New York city it tries to download data and crashed.

 Little investigation shows that ..

in private.h 
#define METASERVER_URL ""
This empty METASERVER_URL leads to Connection failed unsupported URL to ASSERT FAILED.
How can it be fixed.

Thanks!

LOG TID(1) DEBUG     360.626 platform/platform_unix_impl.cpp:190 GetWritableStorageStatus() statfs return = 0 ; block size = 4096 ; blocks available = 37727599
LOG TID(1) DEBUG     470.567 platform/http_thread_apple.mm:97 -[HttpThread initWith:callback:begRange:endRange:expectedSize:postBody:] ID: 2036801440 Starting connection to 
LOG TID(1) WARNING   470.626 platform/http_thread_apple.mm:197 -[HttpThread connection:didFailWithError:] Connection failed unsupported URL
LOG TID(1) WARNING   470.626 platform/http_request.cpp:108 OnFinish() HttpRequest error: -1002
LOG TID(1) ERROR      591.66 platform/servers_list.cpp:30 ParseServerList() Can't parse server list json: 1 '[' or '{' expected near end of file 
ASSERT FAILED

**Comment by Zverik** [comment]
See #5064.
