### ISSUE TITLE
Continues to request GPS even in standby

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#5110]
STR:
1. Open maps.me
2. Turn your device into standby.

What happens: the app continuously requests GPS and this drains the battery very much.

What should happen: at least once a position could be found, stop the GPS requests

Android 6
Note that for testing you need to turn of the energy save mode for apps, which is included in android.

**Comment by burivuh** [comment]
Do you use the latest release version (we've fixed a similar bug in 6.5.4)?
If so:
What is your device model?
Are you using Google location services or only GPS?

**Comment by rugk** [comment]
GT-I9505/jfltexx; Only GPS.

**Comment by rugk** [comment]
As I also updated to v7.0.5 I'll close this issue and reopen it in case I should encounter it again.
