### ISSUE TITLE
Questions about traffic information

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#5122]
1. What data source does Maps.me use?
2. Does Maps.me contribute traffic data to this source? (if not it might be implemented - **if the user can toogle it!**)
3. Is HTTPS used for querying the traffic data?

**Comment by burivuh** [comment]
1. Different.
2. Yes, of course. Application collects location info when it decides user is riding a vehicle. You can turn sending statistics off - this will also stop gps info contribution. Still we will implement a separate flag in the nearest future. And we can't guarantee that traffic will be available to the users that stop contributing location info. For obvious reasons.
3. Location info is sent through a secure SSL transport and is always anonymized.

**Comment by RicoElectrico** [comment]
> Different.

This doesn't instill confidence. Don't you think that obscuring things kind of goes against OSM philosophy?
I don't know if this vagueness is another cultural thing or maps.me is bound by a non-disclosure contract, but it is reasonable to display all the data sources in the About section where OSM is attributed.

**Comment by rugk** [comment]
> Don't you think that obscuring things kind of goes against OSM philosophy?

Additionally one could analyse the source if needed (unless it is somehow passed at built time).
So asking here is just the easy way of doing it.

Also for 2. it would be very interesting to know the answer to 1. as I might want to know *where* my data flows to.

And as we are already talking about open data I thought you might also want to use/contribute/support projects such as http://opentraffic.io/. (only an example link, I have not checked it and do not necessarily endorse it)

> Still we will implement a separate flag in the nearest future.

Indeed I would appreciate if I could toggle this separately.

>Location info is sent through a secure SSL transport

I seriously hope it is not using SSL, but TLS. (SSL is the old insecure version of TLS)😃

**Comment by burivuh** [comment]
> And as we are already talking about open data I thought you might also want to use/contribute/support projects such as http://opentraffic.io/.

We are eager to help any interesting open traffic project (and we indeed contacted some) but for now this is all.

> I seriously hope it is not using SSL, but TLS. (SSL is the old insecure version of TLS)

They are both frequently referred to as "SSL". Of course we're using TLS.

**Comment by mnemonicflow** [comment]
@burivuh 
Regarding 1. Can you give some examples of the providers/data sources used? 
From looking at the source in traffic_manager.cpp and traffic subdirectory I can see that the traffic data is coming from TRAFFIC_DATA_BASE_URL on a per country region basis.
If the users of the app itself are feeding the traffic data source, can you point where can I find the data upload code that helps feed the traffic source? 
I'm interested to know what data is being uploaded and in what context and how often.

**Comment by mnemonicflow** [comment]
@RicoElectrico @rugk This is the data I've found is being sent to the server: https://gist.github.com/mnemonicflow/41c6b7fbf9794a663d2bb7293bb6135e 
The data from the routing module is almost certainly aggregated from all the users and used to feed the traffic information source, possibly combined with other data that might come from their partnership with traffic information providers like TomTom, INRIX or similar companies.

**Comment by rugk** [comment]
Thanks for analysing the code.
I think that users might want to use offline apps, because they want to prevent that their search term is sent to any server, but well,… I hope it's at least disabled if the "send statistics" option in the settings is disabled.
Also I really don't understand why the viewport matters in these cases.

However there is another thing I wonder about. Maps.me already [acknowledged](https://github.com/mapsme/omim/issues/1073) sending the start and end point of a route to the server in order to check for potential missing maps.
However for traffic information data all this data is not very useful. The only useful thing would be the speed at a specific position (lat./lot.) collected when someone is driving.

So maybe you missed something or so.

**Comment by mnemonicflow** [comment]
I've updated the gist, however I cannot find a place where the speed obtained from the GPS is transmitted to the server, after looking at [all the places where the alohalytics service is used in C++ code](https://github.com/mapsme/omim/search?l=C%2B%2B&q=alohalytics&utf8=%E2%9C%93) and all references to the only way to access the  [m_speed member of the GpsInfo class](https://github.com/mapsme/omim/search?utf8=%E2%9C%93&q=m_speed&type=Code)

The routing session sends to the server the "passed distance on route in meters", and in the tracking module the GPS info is sent to the server on every GPS update at a 20 second interval, however only the latitude, longitude and timestamp are sent from the GpsInfo object: https://github.com/mapsme/omim/blob/master/tracking/reporter.cpp#L46-L58, when the route type is vehicle and the app is in 'tracking'/'follow' mode, aka the user hasn't moved the map manually while navigating.  
Even though the GPS speed is passed from Java through JNI to C++ code:
- https://github.com/mapsme/omim/blob/master/android/src/com/mapswithme/maps/location/LocationHelper.java#L109
- https://github.com/mapsme/omim/blob/master/android/jni/com/mapswithme/maps/LocationHelper.cpp#L13-L44
- https://github.com/mapsme/omim/blob/master/android/jni/com/mapswithme/maps/Framework.cpp#L96
- https://github.com/mapsme/omim/blob/master/map/framework.cpp#L183

Maybe the speed is calculated/determined on the server out of the timestamp and the latitude/longitude positions + distance traveled between points, although I'm not sure how accurate would this be, compared to [the speed obtained from the GPS sattellite](https://developer.android.com/reference/android/location/Location.html#getSpeed()).

Also the setting from the UI to disable/enable statistics sending only applies to the GPS position update in tracking mode, all the other data is still sent to the server even if the setting is disabled.
- https://github.com/mapsme/omim/search?utf8=%E2%9C%93&q=kEnableTrackingKey&type=Code
- https://github.com/mapsme/omim/blob/master/map/framework.cpp#L428-L439
- https://github.com/mapsme/omim/blob/master/routing/routing_session.cpp#L66
- https://github.com/mapsme/omim/blob/master/routing/async_router.cpp#L119

and when the actual sending is performed:
- https://github.com/mapsme/omim/blob/master/routing/async_router.cpp#L345
- https://github.com/mapsme/omim/blob/master/routing/async_router.cpp#L362
m_routingStatisticsCallback is never null, it is always initialized with the value of the anonymous lambda function routingStatisticsFn defined in https://github.com/mapsme/omim/blob/master/map/framework.cpp#L428-L439

**Comment by rugk** [comment]
> Also the setting from the UI to disable/enable statistics sending only applies to the GPS position update in tracking mode, all the other data is still sent to the server even if the setting is disabled.

Would you mind to add this information to your gist? (maybe just: `Can be disabled in settings? Yes / No` for each item there) I think it is very useful.

I think these information are also very useful for https://github.com/mapsme/omim/issues/85 as there it was already pointed out that Maps.me uses a bunch of (proprietary) analytics apps and as you might know FDroid also disallows such analytics callbacks unless the user explicitly opted-in for them.
So also for removing/changing this in a potential FDroid built this is very useful to know.

**Comment by renovatiohominis** [comment]
IMO, in an opensource project like MAPS.ME, a simple question like " what is the source of your tragfic data" deserbes a simple and open answer. And this information should be available to all.

Would the project be unable to disclose the sources of the data, the reasons should also be clearly stated.

Not proceeding this way is opting for closedness instead of open behaviours.

**Comment by jalvesaq** [comment]
I used to get traffic data for my city (Fortaleza, Brazil) until the last upgrade. Now, version 7.1.3-Google says (in Portuguese) "There is no traffic data" when I touch the traffic icon. I am using map generated on January 30, from http://direct.mapswithme.com/regular/daily/

**Comment by burivuh** [comment]
Daily map builds will not support traffic info, only official data releases will.
Traffic updates are designed to be extremely small, to include only essentially new information - that's why they depend on the client  map version. And we can't afford to support more then 3-4 data versions at this moment.

**Comment by burivuh** [comment]
> a simple question like " what is the source of your tragfic data" deserbes a simple and open answer

Okay, I thought it was obvious: "this is a confidential information".

**Comment by jalvesaq** [comment]
@burivuh Thanks for the information!

**Comment by rugk** [comment]
But that's no answer. Why is such a simple thing confidential?

**Comment by burivuh** [comment]
Because it is a matter of business and NDA?

**Comment by softgrow** [comment]
If you look through the code Q1 is not answered at https://github.com/mapsme/omim/blob/master/configure.sh#L61 , i.e. it's inserted at build time and isn't recorded in the repository

**Comment by ghobs91** [comment]
To add some follow up context, here's a tidbit about Maps.me that it's important to know: 

"In November 2014, it was acquired by Mail.Ru Group and became part of its My.com brand."

"On Nov 2020 Mail.ru Group sold Maps.me to the payment processor Daegu Limited, part of Parity.com, which changed the application and content, which led the free software community to develop [Organic Maps ](https://github.com/organicmaps/organicmaps) in response."
