### ISSUE TITLE
UK Postcodes don't work?

### ISSUE THREAD

**Issue by mintsoft** [mapsme/omim#5124]
Hello,

A common means of navigating in the UK is to use postcodes (as they're usually accurate to the street); this doesn't seem to work in maps.me; should it be working already?

If not the geocoding data is available for free from the Ordinance survey (https://www.ordnancesurvey.co.uk/opendatadownload/products.html) under the OS Open Names product.

Thanks,

**Comment by leonmvd** [comment]
Since maps.me is using Openstreetmap, the postal codes should be in there. Searching the wiki it seems that not all postal codes are in there. You could do a proposal for an import though.

**Comment by ygorshenin** [comment]
Hello, @mintsoft.

Generally, search by postcodes in UK should work. Could you please provide examples search queries that don't work?

**Comment by mintsoft** [comment]
@ygorshenin Interesting, on closer inspection, I've found a few that do work; however the majority I've tried don't work. A few non-working examples:
* CW7 4AA
* ST4 2ED
* ST17 9AT
* NG11 7EP
* W10 5SH
* SA10 7DQ
* CO6 1QA

I enter these on the phone as usually lowercase and without the space (i.e co61qa) however styling them correctly doesn't seem to improve the hit rate

**Comment by leonmvd** [comment]
They work on osm e.g. CO6 1QA -> https://www.openstreetmap.org/search?query=CO6%201QA#map=13/51.8740/0.7273 <https://www.openstreetmap.org/search?query=CO6%201QA#map=13/51.8740/0.7273>

**Comment by ygorshenin** [comment]
@mintsoft, thanks for the examples you provided. I checked them - our search engine can currently search only CW7 4AA (you need to download the map of Winsford) and W10 5SH (you need the map of London). Others postcodes can't be found, and the reason is that there're no corresponding OSM objects. @leonmvd , you found CO6 1QA on openstreetmap just because openstreetmap uses http://www.npemap.org.uk/data/ as an additional source of information. We don't use it now, but possibly can, I need to check this.

**Comment by leonmvd** [comment]
Ah I wasn't aware of that, now I see indeed that the search results mention the source. Then my first comment still applies, that an import could be useful

**Comment by mintsoft** [comment]
So if OSM comes back with an actual result like (www.openstreetmap.org/search?query=st174lt) then it should work? If it comes back with an area result like https://www.openstreetmap.org/search?query=CO61QA it shouldn't?

**Comment by ygorshenin** [comment]
Currently our search engine should return meaningful results when one is search by postcodes if and only if there's some OSM object (POI, street, whatever) with corresponding postcode. Otherwise, search won't found anything. The same for openstreetmap.org - they provide results from Nominatim (both empty in links you provided) and results from NPEMap/FreeThePostcode (exactly one result in both cases, but no corresponding OSM objects).

**Comment by mintsoft** [comment]
Ah! So if I understand you correctly, you're saying it should work if I want to go to the london eye using its postcode (for example),  but not for a friend's house or similiar (unless he lives in a monument I guess)

**Comment by nigelsheffield** [comment]
So any chance of getting post codes search working for every address because without postcode searching to get me the right streets at least this is actually pretty useless as a sat nav.
Though useful as a back up at a push..

**Comment by mpimenov** [comment]
@nigelsheffield Could you provide several specific addresses that you were unable to find?

**Comment by nigelsheffield** [comment]
Mk5 7bb
Wf4 5jr
MK2 3py

I'm just entering them in the search box , is this correct or is there some other way of entering a post code?

**Comment by mintsoft** [comment]
@nigelsheffield That's exactly the problem I have; if I'm trying to get to a restaurant or something, fine. But if it's someone's house, useless

**Comment by zonzura** [comment]
I also have issues finding uk postcode in search. Have downloaded the whole uk maps and still can't find a single postcode!  A bit useless app

**Comment by zonzura** [comment]
I also have issues finding uk postcode in search. Have downloaded the whole uk maps and still can't find a single postcode!  A bit useless app

**Comment by mintsoft** [comment]
@zonzura if you use a postcode for somewhere that has an attraction, that should work (for example `CW9 6FW`) however for general purposes postcodes it's useless

**Comment by zonzura** [comment]
Thx mintsoft
I've already uninstalled as it's pretty much useless for anything other than attraction as you mentioned and I don't drive to attractions every day so it had to go

**Comment by tatiana-yan** [comment]
Hello!
UK postcodes supported in release 9.5.
