### ISSUE TITLE
Maps.me lost his core function

### ISSUE THREAD

**Issue by Adem1987** [mapsme/omim#5126]
Thank you, that all of you messed up the most important function in Maps.me.
Now, the app doesn't show me the shortest route from x to y.
I had to give one star in the App Store.
You shouldn't play to much with Maps.me. Take some Beta-Testers. This is the right way.

Good Bye, I'm using Scout now.

**Comment by Airon90** [comment]
This isn't a bug report. Please, give your comment on other platform, such as stores, not here.
Turn your comment into a bug report or please close your issue.
