### ISSUE TITLE
Cannot Edit Place if OpenTable Option Available

### ISSUE THREAD

**Issue by Miserlou** [mapsme/omim#5129]
This may be a feature, not a bug, I'm not sure. It may also be an inaccurate title.

If I open the restaurant "kofookoo" in Hamburg, Germany, there is no "Edit Place" button available like there are on most OSM places. I think that this may have something to do with the "Book" button that has also appeared. I'm not sure, but I would like to be able to edit this place to add more information to the description.

Latest Android from Play Store.

**Comment by Miserlou** [comment]
Ah, this may be a duplicate of https://github.com/mapsme/omim/issues/5082

**Comment by Zverik** [comment]
Thanks for reporting, this will be fixed in #5145.
