### ISSUE TITLE
Some edits including banner_url tag

### ISSUE THREAD

**Issue by ethan-nelson** [mapsme/omim#5131]
Some edits by users using the Maps.Me app seem to be including a `banner_url` tag with a link to a travel booking site related to the place a user is updating. There's at least one instance of a user acknowledging they did not add this ([1]) (only response I've gotten so far, though I've commented on many). As of right now, there are at least 320 instances of this tag present in OSM ([2]).

Though I haven't composited all of the objects present, the few that I did manually check seemed to be recent--within the past few days. I think this tag may be introduced with the edits in error, but I wanted to double check. Do you have any insight or guidance about this?

Thanks for your help!
Ethan aka FTA with the OSMF DWG

[1]: http://www.openstreetmap.org/changeset/44810127
[2]: http://overpass-turbo.eu/s/l5r

**Comment by Zverik** [comment]
Will be fixed in #5145. I will remove all `banner_url` tags after the fixed version is released. Sorry for this mess.

**Comment by ethan-nelson** [comment]
Great, thanks!
Ethan

**Comment by SomeoneElseOSM** [comment]
Just a thought - ref:sponsored isn't the same issue is it?  I saw that on https://www.openstreetmap.org/node/562722222/history .

**Comment by Zverik** [comment]
Yes, it is.

**Comment by pnorman** [comment]
Is this information from an ODbL compatible source? When will it stop being added to the database?

**Comment by Zverik** [comment]
It will stop being added when the next release is out, hopefully next week. I am sorry for these and will remove the tags. Information comes from us, so it is odbl-compatible I guess.
