### ISSUE TITLE
Users can create note with gravely out of date maps

### ISSUE THREAD

**Issue by M1dgard** [mapsme/omim#5132]
E.g. https://www.openstreetmap.org/note/843203

I don't use maps.me myself, but I suppose(/hope) that users can't add POIs when their map is out of date and that's why Rubi1869 created a note.

If their map is out of date, I would give the user a message saying that they need to update it when they want to report a note.

**Comment by Zverik** [comment]
Fixed in #5146.

**Comment by M1dgard** [comment]
Thanks!
