### ISSUE TITLE
Generator Tool Build Issue in Ubuntu 14.04 Server

### ISSUE THREAD

**Issue by khalilst** [mapsme/omim#5160]
I want to build generator tool and I have setup according to documentation.
But after running this command:

`    CONFIG=gtool omim/tools/unix/build_omim.sh -cro`

I've got the errors below and build process fails.

_/root/tools/mapsme/omim/coding/internal/file64_api.hpp:27:5: error: static_assert failed ""
    static_assert(sizeof(off_t) == 8, "");
    ^             ~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [../out/release/tmp/coding/file_container.o] Error 1
make: *** [sub-coding-make_first] Error 2
make: *** Waiting for unfinished jobs...._

Any help appreciated...

**Comment by syershov** [comment]
Please explain version of OS and compiler version. Also would be interesting hardware architecture.

**Comment by khalilst** [comment]
I've already mentioned OS at title, Ubuntu 14.04 Server and I'm using Crang 3.8.
However I had couple of issues and one by one resolved with following tips:

1. Update Alternatives:
`update-alternatives --install /usr/bin/cc cc /usr/bin/clang-3.8 100`
`update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-3.8 100`
`update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-3.8 100`
`update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-3.8 100`

2. Install gcc-4.9:
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt-get update`
`sudo apt-get install gcc-4.9 g++-4.9`

3. Comment line 27 in omim/coding/internal/file64_api.hpp

I hope this helps someone else.
Btw thank you for your attention :)
