### ISSUE TITLE
have buildings without addresses be a different color on the map.

### ISSUE THREAD

**Issue by afonit** [mapsme/omim#5214]
This is a request/suggestion for enhancement.  I am often riding as a passenger or on transport while mapping.  There are lots of POI's on buildings and not addresses.

Because of the POI's it is hard to tell if there is an address on a building or not without:
 * selecting the building and going into the details
 * zooming in really tight to see if the building number shows up on the building.

Just looking to see if this would be easier for others as well to have the buildings a different color like pink or red or something so that when traveling one could easily see what building doesn't have a number and I can just focus on those as we travel by.

This is definitely a small issue - but would be immensely useful in dense areas and drive by mapping (as a passenger).

**Comment by utack** [comment]
That is pretty confusing  
Especially since in many places it is common to add adresses on nodes, and buildings would have the "no address" color despite having one mapped

**Comment by afonit** [comment]
@utack , thanks for the additional context - I was not aware that was the case in other areas.

When the address is added to a node - is that node a part of the building, or is it on some other node like the road by the building?

**Comment by afonit** [comment]
Yes,
I was thinking if the idea had merit - it would be an option to enable, not to have on default.

**Comment by burivuh** [comment]
Hi!

We have basically the same idea in mind. Of course in a special mode only. But we can't implement this at this moment.

**Comment by afonit** [comment]
Closing this - as I have discovered the StreetComplete android app that does this really well, and in thinking about this more the strength of maps.me is its navigation and the ability to explore/discover places.
