### ISSUE TITLE
tool/autobuild/ios.sh script of omim project

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#530]
how to configure to run the tool/autobuild/ios.sh script on omim project?

**Comment by deathbaba** [comment]
It is called automatically from XCode. Why do you need to run it directly?

**Comment by simon247** [comment]
How to set it with the Xcode? I want to build a new project to test it. Thx.

**Comment by deathbaba** [comment]
If you want to build our maps from XCode, please follow environment setup instructions and open/build project in iphone/Maps folder.

**Comment by simon247** [comment]
how about create a new project, but not use the current iphone/Maps folder project.

**Comment by deathbaba** [comment]
Take a look on our project’s properties and settings, and do the same. Script call was configured somewhere in Run Script/Build Phases for target.
