### ISSUE TITLE
[Android] gradlew clean assembleWebRelease error

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#531]
"./gradlew clean assembleWebRelease"  When this step is performed

Exceptions is:
org.gradle.api.tasks.TaskExecutionException: Execution faild for task '3rd_party:BottomSheet:compileReleaseAid'.
......
......
......
"Caused by: java.lang.IllegalStateException:aidl is missing"

Is there something missing?

**Comment by deathbaba** [comment]
It can be an issue with your environment, which is not related to MAPS.ME.

**Comment by xingdavis** [comment]
software environment: mac ox 10.10.5、 xcode 、qt5.5、  jdk1.7、 ndkr1e  Have been stalled.
My operating procedure is:
1. Go directly to the omim root run ./configure.sh ...ok
2. Go to omim/tools/android and run ./set_upandroid.py ...ok
3. Go to omim/android and run ./gralew clean assembleWebRelease...build failed
Please point out where the problem is.
![2015-11-17 2 42 50](https://cloud.githubusercontent.com/assets/11851006/11204610/8fedb892-8d3b-11e5-9316-8b15587a4536.png)

**Comment by deathbaba** [comment]
http://stackoverflow.com/questions/30547767/gradle-code-not-building-aidl-is-missing <http://stackoverflow.com/questions/30547767/gradle-code-not-building-aidl-is-missing>

http://stackoverflow.com/questions/30623448/always-aidl-is-missing-on-android-studio-1-2-1-1 <http://stackoverflow.com/questions/30623448/always-aidl-is-missing-on-android-studio-1-2-1-1>

**Comment by xingdavis** [comment]
Thank you @deathbaba，The problem is solved,but the problem is compiled to 80%.

![2015-11-18 10 19 09](https://cloud.githubusercontent.com/assets/11851006/11231063/e3edc0c8-8ddf-11e5-8ca4-b9204ef578ea.png)
![2015-11-18 10 19 57](https://cloud.githubusercontent.com/assets/11851006/11231074/f2caa37c-8ddf-11e5-9efd-bfe665763f1c.png)
![2015-11-18 10 20 58](https://cloud.githubusercontent.com/assets/11851006/11231080/ff342340-8ddf-11e5-9418-4330c74ded61.png)
![2015-11-18 10 21 15](https://cloud.githubusercontent.com/assets/11851006/11231094/1283e886-8de0-11e5-8bd4-8bb0d403ce57.png)

**Comment by deathbaba** [comment]
qmake is not installed or is not in your path

**Comment by xingdavis** [comment]
@deathbaba Where to set the path?
I have already installed,and can also be found in the QT.
![2015-11-18 11 25 40](https://cloud.githubusercontent.com/assets/11851006/11231870/916bf966-8de7-11e5-84df-930cfbc0765a.png)

**Comment by deathbaba** [comment]
Either add correct path in tools/autobuild/detect_qmake.sh, or use these instructions: http://coolestguidesontheplanet.com/add-shell-path-osx/ <http://coolestguidesontheplanet.com/add-shell-path-osx/>

**Comment by xingdavis** [comment]
Compiler passed, thank you！ @deathbaba
