### ISSUE TITLE
Orlando Airport not rendered (because it is a multipolygon?)

### ISSUE THREAD

**Issue by Codain** [mapsme/omim#5323]
Hi, in current version (7.1.3-Google) and in the previous one Orlando International Airport is not rendered as an airport (it means with a purple polygon and/or an airport icon). Other airports are well rendered.

I assume it is because this airport is defined as a multipolygon/relation (and not a closed way) and the app is not setup to render relations.

Relations with type=multypoligon to define a closed area shall be treated as a closed way.

**Comment by utack** [comment]
The search also does not find it weird  
fwiw JOSM complained that two elements had no "outer" role in the relation, [I added it](https://www.openstreetmap.org/changeset/45717500), try tomorrow's daily maps maybe if it works:
http://direct.mapswithme.com/regular/daily/

**Comment by utack** [comment]
@Codain can you close the issue?
