### ISSUE TITLE
Oldstyle missing from latest vesion

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#5364]
In version Android 7.1.3 I noticed that typing ?oldstyle in the search box has no effect, is it no longer possible to switch to old style?

**Comment by burivuh** [comment]
Yes, old style has been semi-broken for several months now and too few folk have even noticed that. We have not enough resources to support this feature for a such sparse demand. So we disabled it totally.

**Comment by stevegdavis** [comment]
Thanks for the reply. I have just built 7.1.3 myself on Android, is it possible to re-activate it, the reason I ask is that about a year ago I built V5.1.8 and changed the colour of some roads (see issue #894), so can I still change the road colours as I did before?

**Comment by burivuh** [comment]
You can compile your own map styles despite new or old style scheme you're basing them on.

So I see no necessity to provide old style files with the application for that to work.

**Comment by stevegdavis** [comment]
OK, so even without changing any maps styles there is no way I can re-enable the old style switch then in code?

**Comment by burivuh** [comment]
No, only if you revert/write code on you personal fork

**Comment by stevegdavis** [comment]
OK, looking at a comparison between 5.1.8 & 7.1.3 I can see that the code has changed substantially, so I may just try to change the road styles as I did before, thanks for your help.

**Comment by Zverik** [comment]
To substiture the default style with yours, you just need to compile a `drules_proto*.bin` and to put it into `omim/data`. If you changed mapcss files in `omim/data/styles`, you can compile these with `omim/tools/unix/generate_drules.sh`. The app itself uses `drules_proto_clear.bin`.

**Comment by stevegdavis** [comment]
@Zverik , thanks for that, yes I did change the styles before on version 5.1.8 I just thought I would try it on the latest version, can I assume that I would have to download the latest maps direct from your server as I did before? if so can you give me a link as I assume that the maps I used for the old version will not be compatible?

**Comment by Zverik** [comment]
Maps are compatible with any style, though some objects might be missing. [Daily generated maps](http://direct.mapswithme.com/regular/daily/) are built with the same settings as the official maps.

**Comment by stevegdavis** [comment]
OK, thanks for that.
