### ISSUE TITLE
Offer maps downloaded by OsmAnd

### ISSUE THREAD

**Issue by PanderMusubi** [mapsme/omim#5381]
OsmAnd also downloads maps in the directory osmand on the storage card of a mobile device. When these maps are not existing in MAPS.ME or are newer than those in MAPS.ME, automatically use these maps.

Offer a setting in general configuration to enable and disable this functionality

**Comment by burivuh** [comment]
Hi!

Thank you for an idea, but this use case is too rare and implementation too expensive.

**Comment by Zverik** [comment]
MAPS.ME and OsmAnd use drastically different data formats, from compression algorithms to data models. Map files sadly are not interchangable. Implementing support for OsmAnd maps in MAPS.ME is harder than the opposite, I guess.

**Comment by PanderMusubi** [comment]
Thanks for the feedback

**Comment by PanderMusubi** [comment]
Before opening another issue, would syncing or at least offering read-only favorites from OsmAnd be possible? These can be found in osmand/favorites.gpx

**Comment by Zverik** [comment]
That is actually a nice idea. Maps.me currently does not support GPX importing, but it can be done with an external tool.

**Comment by PanderMusubi** [comment]
Okay, I will create a separate issue for this.

**Comment by PanderMusubi** [comment]
Please, see https://github.com/mapsme/omim/issues/5416

**Comment by PanderMusubi** [comment]
please, see that issue for a solution
