### ISSUE TITLE
mapsme dies after an update

### ISSUE THREAD

**Issue by inktrap** [mapsme/omim#541]
I recently updated mapswithme and now the application won't start. This is ``version 5.1.8-Google``.
I suspect that this is a problem for my device only, because no one else has this issue? Anyway, I attached the output of ``adb logcat``. (Github won't let me upload this file, so I uploaded it [here](https://bugs.inktrap.org/mapsme/index.txt))

Second thing: After the application dies I can give feedback which will include system logs as well. I found no way to configure the address this feedback is send to or to check which data it contains. I would love to show you the output of this, but adb logcat was my only solution. If you have tips for better debuggin/bug-reporting, I am glad to hear them. Thanks!

**Comment by deathbaba** [comment]
Thanks for reporting the issue! @yunikkk can you take a look on it, please?

System bug reports are going into Google’s developer console and we can see them directly there.

Have you already tried to reinstall the app?

**Comment by inktrap** [comment]
Yes, reinstalled multiple times and also deleted the app-data.
Checked with the privacy manager and allowed everything.

Are the bug reports only for your application or for everything and
filtered?

**Comment by deathbaba** [comment]
Strange, our developers say that reinstall should help. @yunikkk ?

Bug reports in GP console show only crash call stack and your custom message, no any logs at all.

**Comment by inktrap** [comment]
Sent you the crash call stack and custom message "inktrap" just now.

> Strange, our developers say that reinstall should help. @yunikkk ?

Maybe it helps if I remove the data explicitly via adb?

**Comment by yunikkk** [comment]
Hi!
Which device/android version do you have?

**Comment by inktrap** [comment]
Hi,

 - Oneplus (A0001)
 - Android 5.1.1
 - Cyanogenmod cm-12.1-bacon (YOG4PAO33I)

Excerpts from Dmitry Yunitsky's message of 2015-11-16 11:31:04 +0100:

**Comment by yunikkk** [comment]
Hello again!
Could you please try previous version and confirm if it’s working on your device?

https://www.dropbox.com/s/2lom4ti4m9qee44/android-google-universal-release-5.1.4-151013.apk <https://www.dropbox.com/s/2lom4ti4m9qee44/android-google-universal-release-5.1.4-151013.apk?dl=0>

**Comment by inktrap** [comment]
Hi,

this is strange, it does not work. Tried newest:
(android-google-universal-release-5.1.5-151118.apk)

and mentioned release:
(android-google-universal-release-5.1.4-151013.apk)

both via adb install.

Somehow I believe that this is a special problem for my device (not all
Oneplus devices). Do you have a checklist for stuff I could look out for?

 - I removed all app-data before i deinstalled it manually
 - I checked the privacy manager settings
 - I do not have a firewall app like f.e. AFWall+ which configures iptables
 - …

**Comment by deathbaba** [comment]
What about older releases from here http://maps.me/apk/ <http://maps.me/apk/>

**Comment by inktrap** [comment]
I know that apps are signed, but I think it would be cool to do downloads via https and verify the file with a signature. I only tested if it works to open mapsme

 - works: android-web-release-4.3.1-150423.apk
 - works: android-web-release-4.4.3-150622.apk
 - does not work: android-web-release-4.4.6-150728.apk
   - install finishes
   - mapsme opens and closes after like one second
   - no visible error message
   - if you like a log for this i could upload it
 - works: android-web-universal-release-5.0-150828.apk
 - works: android-web-universal-release-5.0.3-150909.apk
   - updated the maps-data and tested zoom. Works.
 - works: android-web-universal-release-5.1.4-151016.apk

**Comment by inktrap** [comment]
installed the newest version from the app-store and it works. What
happened?

**Comment by yunikkk** [comment]
Hi,
so the app now runs every time and before it was failing every time on startup, right?

Seems that it was indeed some problem with your installation independent of the app version itself.

**Comment by inktrap** [comment]
Yes. Maybe the maps-data had a different version?

Do you have some kind of checklist that ensures a clean uninstall?
Usually deleting data and uninstalling the app should work …

Anyway, I am interesting in how this could happen.

**Comment by deathbaba** [comment]
Deleting the app and MapsWithMe folder is usually enough. It can be some OS installation bug or even broken memory bug.
Btw, does old version crashes now if you install it back?

**Comment by inktrap** [comment]
No, it does not. :clap:
