### ISSUE TITLE
automatic night mode does  ot work  

### ISSUE THREAD

**Issue by Serhioromano** [mapsme/omim#5427]
It only works when I drive route. When it simply shows a map without selected route it never switch to night mode. I have to go to settings and switch it manually.

**Comment by burivuh** [comment]
Hi!

This is by design:

1) Routing mode suggests you are in the car without a light.
2) Map mode doesn't. Many users look at the map during dark hours whilst sitting in their office/home.

Thank you!

**Comment by Serhioromano** [comment]
Then there should be also mode I am in car or home. Because i use it on the car android head unit. Can you make such a parameter? Or make 2 parameters

Navigation -  Day,Night,Auto
Map view - Day,Night,Auto
