### ISSUE TITLE
Not able to download map from my server

### ISSUE THREAD

**Issue by RahmanFard** [mapsme/omim#544]
something strange. 
I have downloaded a country map by old version Mapsme from my android device and after uploading it to my server, I can download it from my custom version of Mapsme. also there is no problem to show and navigate of that map.
But when i download new version of that map from http://direct.mapswithme.com/direct/latest/ and upload to my server, my custom version of Mapsme can not download it.
I do nothing whith download part of souce of Mapsme.
Another thing, When i download a country map from new version of Mapsme from my device and upload to my server, There is no problem of downloading from my custom version, But nothing to show and just a blank page shows in my device.

What should i do to solve the problem?

**Comment by deathbaba** [comment]
Sometimes we change map format and add new feature types (version number in countries.txt is changed).
This means that new code can read old maps and new maps, but old code can’t read new maps.
Probably you need to rebase to update your code base to the most recent version, or stick to using maps from version in your country.txt.
You can also check-out code branch for that ‘old’ version and generate fresh maps on your own server, but with old code base.

**Comment by RahmanFard** [comment]
Thanks for your comment.
Would you please tell me haw can i find the list of source files(c++ & java) that are related to download, read and show maps(World and countries).
I want to over write just this part of source and work with current version of maps.

Thanks again.

**Comment by deathbaba** [comment]
The code is very complex. Please check storage for download, indexer and map to read and show maps.
