### ISSUE TITLE
Feature request: more info about map style development

### ISSUE THREAD

**Issue by easz** [mapsme/omim#549]
My attempt is to add more map styles besides ?light, ?dark..etc.
Or are you going to have such feature that user/developer can dynamically change the style without hard-coding. 

Somehow I began with the instruction https://github.com/mapsme/omim/blob/master/docs/INSTALL.md 
to checkout map-style-editor-new branch.
Actually the build process was not so straightforward as the document states.
I need to run the build script twice to build MAPS.ME.Designer
CONFIG="gtool" omim/tools/unix/build_omim.sh
CONFIG="map_designer" omim/tools/unix/build_omim.sh 
The first time I open MAPS.ME.Designer, it complained about missing kothic files.
After manually copying missing kothic files, it still complains about other missing libs like protobuf 
MAPS.ME.Designer does not show any map and sometime crashes. I am not able to do anything with it.

Next, I try to figure out how to compile drules_proto. Maybe I can just generate new style and try it in Maps.ME application. 
Unfortunately I cannot find the script mentioned in the tools/kothic/README.
What is exactly the submodule status of kothic? does it get update? The original kothic repository looks OK with the HEAD version.

Btw, I can build Maps.ME (Master/HEAD branch) on Mac OS as desktop application successfully, 
and I can generate mwm files and load it in Maps.ME without problem. 
(all the dependencies are installed with homebrew)

**Comment by deathbaba** [comment]
@kshalnev @Zverik Can you please help & update our documentation?

**Comment by easz** [comment]
OK, thanks.

eventually need to tun python setup.py under protobuf to generate some necessary py files.
and protobuf files should be probably also copied to MAPS.ME.Designer content folder?
