### ISSUE TITLE
Embeddable maps

### ISSUE THREAD

**Issue by nvx** [mapsme/omim#5516]
From looking at the current APIs, it looks like the APIs are only intents to control maps.me, not embed the map in your app directly. Think of how Uber embeds Google Maps inside the Uber app for example. It would be quite neat to be able to achieve the same thing with maps.me as well.

**Comment by cordovapolymer** [comment]
That would be great!
Of course now, you can embed OSM using leaflet.js, but mapsme is much more shiny.

**Comment by nvx** [comment]
Sure, although that defeats the purpose of offline maps.

**Comment by burivuh** [comment]
Hi!

I'm sorry but we have no resources to implement and support maps SDK.

Thank you!
