### ISSUE TITLE
Windows 7 build & apk exception error

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#559]
I have managed to do a Windows 7 build (assembleWebDebug) but the resultant 'android-web-universal-debug-5.1.5-151117.apk' crashes with the usual 'Unfortunately, maps.me debug has stopped' when run on my HTC One device (copied via USB cable).

I had numerous lint errors on build to do with the language translation but suppressed those with 'disable MissingTranslation' in the build.gradle file so I am assuming that is not the reason it is crashing.

Looking at the logcat I see:-
11-17 10:35:46.743 E/AndroidRuntime(10725): FATAL EXCEPTION: main

11-17 10:35:46.743 E/AndroidRuntime(10725): java.lang.ExceptionInInitializerError

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.mapswithme.maps.MwmActivity.onCreate(MwmActivity.java:286)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.Activity.performCreate(Activity.java:5165)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.ActivityThread.access$600(ActivityThread.java:162)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.os.Handler.dispatchMessage(Handler.java:99)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.os.Looper.loop(Looper.java:158)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at android.app.ActivityThread.main(ActivityThread.java:5751)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at java.lang.reflect.Method.invokeNative(Native Method)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at java.lang.reflect.Method.invoke(Method.java:511)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at dalvik.system.NativeStart.main(Native Method)

11-17 10:35:46.743 E/AndroidRuntime(10725): Caused by: java.lang.IllegalArgumentException: apiKey not specified

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.flurry.android.FlurryAgent.init(SourceFile:356)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.mapswithme.util.statistics.Statistics.configure(Statistics.java:308)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.mapswithme.util.statistics.Statistics.<init>(Statistics.java:138)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	at com.mapswithme.util.statistics.Statistics.<clinit>(Statistics.java:31)

11-17 10:35:46.743 E/AndroidRuntime(10725): 	... 15 more

11-17 10:35:46.753 D/qdmemalloc(  819): ion: Unmapping buffer  base:0x512f3000 size:4096

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Unmapping buffer  base:0x42c98000 size:1536000

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Unmapping buffer  base:0x40091000 size:4096

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Freeing buffer base:0x0 size:1536000 fd:44

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Freeing buffer base:0x0 size:4096 fd:45

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Unmapping buffer  base:0x431fd000 size:1536000

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Unmapping buffer  base:0x40103000 size:4096

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Freeing buffer base:0x0 size:1536000 fd:65

11-17 10:35:46.753 D/qdmemalloc(  223): ion: Freeing buffer base:0x0 size:4096 fd:66

11-17 10:35:46.753 E/Surface (  627): Invalid SurfaceControl

11-17 10:35:46.753 E/EmbeddedLogger(  627): App crashed! Process: com.mapswithme.maps.pro.debug

11-17 10:35:46.753 E/EmbeddedLogger(  627): App crashed! Package: com.mapswithme.maps.pro.debug v515 (5.1.5-Web-debug)

11-17 10:35:46.753 E/EmbeddedLogger(  627): Application Label: maps.me debug

11-17 10:35:46.753 W/ActivityManager(  627):   Force finishing activity com.mapswithme.maps.pro.debug/com.mapswithme.maps.MwmActivity

I assume that the bit that states the following is the reason:-
'Caused by: java.lang.IllegalArgumentException: apiKey not specified'
at com.flurry.android.FlurryAgent.init(SourceFile:356)

Debug via Android Studio and it fails in file util\statistics.java->configure(..) method where it attempts to initiate the FlurryAgent so maybe it is something to do with the apiKey. 
#define FLURRY_KEY  is empty in private.h ?

[FIXED] I just put #define FLURRY_KEY="FLURRY_KEY" in private.h and it runs OK.

Many Thanks.

**Comment by deathbaba** [comment]
Can you please add any value to FLURRY_KEY in private.h file in the root of the repo, rebuild apk from scratch and try again?

**Comment by stevegdavis** [comment]
Thanks for the reply.
Yes I did that, sorry I did add the fact that I added something to FLURRY_KEY (to the bottom of my last post), anyway it all works OK now.
Shall I close this or leave it open as it may help someone else ?
