### ISSUE TITLE
generate_planet.sh fails

### ISSUE THREAD

**Issue by berolinux** [mapsme/omim#5637]
Running generate_planet.sh fails without producing any usable maps or a usable WorldCoasts.geom file for generate_mwm.sh

$ PLANET=~/Downloads/planet-170313.osm ./omim/tools/unix/generate_planet.sh -a
[2017/03/18 22:38:27]: STATUS Start 
Using tool: /home/bero/repos/maps.me/omim/../omim-build-release/out/release/generator_tool
[2017/03/18 22:38:27]: STATUS Step 2: Creating and processing new coastline in /home/bero/repos/maps.me/omim/data/intermediate_data/coasts/coastlines-latest.o5m
LOG TID(1) INFO      204.318 generator/coastlines_generator.cpp:117 operator()() Not merged coastline, ways 85765487 to 22493851 ( 4339851 points)
LOG TID(1) INFO      207.078 generator/coastlines_generator.cpp:117 operator()() Not merged coastline, ways 479982336 to 479981119 ( 52 points)
LOG TID(1) INFO      207.078 generator/coastlines_generator.cpp:115 operator()() Not merged coastline, way 479981126 ( 26 points)
LOG TID(1) INFO      211.696 generator/coastlines_generator.cpp:147 Finish() Total not merged coasts: 3
LOG TID(1) INFO      211.696 generator/coastlines_generator.cpp:148 Finish() Total points in not merged coasts: 4339929
[2017/03/19 05:48:18]: STATUS Coastline merge failed

**Comment by Zverik** [comment]
Yes it does. And the error is shown: the coastline in the OpenStreetMap is not closed. You have to fix these three errors yourself. Download the ways with IDs shown and then areas around them, filter by a natural=coastline tag, and you'll see what to do.
