### ISSUE TITLE
Error set up Qt enviroment

### ISSUE THREAD

**Issue by vietanhIT** [mapsme/omim#5736]
Please help me!!!

I built project in ubuntu 15.10. I installed qt5.5 from wiki.qt.io. I downloaded package qt-opensource-linux-x64-android-5.5.0-2.run and installed it. But I don't know how to set up Qt enviroment. 

When i tried to  build project ./build_omim.sh,  I have received a error message "You need Qt 5 to build this project. You have Qt 4.8.6".

**Comment by naserbagheri** [comment]
install Qt5
Terminal :
 export QTCHOOSER_RUNTOOL=qtconfig
 export QT_SELECT=5
 ./configer.sh
CONFIG=gtool omim/tools/unix/build_omim.sh -cro

**Comment by Zverik** [comment]
You can also adjust `omim/tools/autobuild/detect_qmake.sh`, adding a path to your Qt there.
