### ISSUE TITLE
Downloading maps via PC and copying them to Android devices no longer works

### ISSUE THREAD

**Issue by fegul** [mapsme/omim#5801]
So I was looking to set up a few phones with MapsMe but the internet connectivity in my area is quite poor so I wanted to do the following:

- Download the APK from http://maps.me/apk/ (it's unclear why there are three installers, which one should I download?)
- Download the maps for my specific country separately and copy them to the phone's memory to save time (e.g. from here: [http://direct.mapswithme.com/direct/latest/](http://direct.mapswithme.com/direct/latest/))

This used to work previously where I would copy over the MapsWithMe folder to the internal storage and install the Google Play version of the APK however lately that seems to have changed.

The `android-web-universal-release-7.2.1-170320.apk ` does not seem to install on many phones so I used the `android-web-release-4.4.6-150728.apk` and then copied over the following folder structure from a phone that I used to download the maps before:
```
- MapsWithMe/
--- 170215/
------ <country-region name>.mwm
--- settings.ini
```
When I copy this folder over to new devices, MapsMe crashes. Now that it seems things have changed from the previous versions of MapsMe we were using, how can I download the maps once and put them on multiple phones without having to re-download the files each and every time on each device?

**Comment by stevegdavis** [comment]
It looks as if it is a version mismatch, the version 4.4.6-150728.apk is old and the latest maps will not work with that version of apk. Have you tried installing the latest release version from play store and then (ignore downloading the maps via the app) if you look at the settings/about, the version number should be 7.2.3-Google Data version 170328. So copy a map from [ http://direct.mapswithme.com/direct/170328/](url) and and that should work it does for me, if it does work and you do not want to repeat the apk install from play store then you could install an apk extractor get the maps.me apk back off the phone (via USB) and then copy/install that on to each phone you have. Note I did not copy any setting.ini file you should not need to do that. Hope that helps.

**Comment by fegul** [comment]
Hi Steve, thanks for the info.

The Play store is blocked in the country I work in so I need to find the standalone APK itself. Is the most recent APK (`android-web-universal-release-7.2.4-170412.apk`) \the correct one to download?
I've had some issues installing it on other phones

**Comment by stevegdavis** [comment]
Hi,
I have just downloaded/installed OK android-web-universal-release-7.2.4-170412.apk on my Samsung S4 without any problems, however when I look at the About screen on the app it tells me that the data version is 170328 (not 170412 as the filename implies) so I have downloaded just 1 map from [http://direct.mapswithme.com/direct/170328/](url) and that works fine, note that it is my understanding that the apk's from  http://maps.me/apk/ may not be stable and they may not be the same as what is released on play store so it could be a case of pot luck but it should work.

**Comment by fegul** [comment]
That is good to know, thank you again!
