### ISSUE TITLE
[Android]Cannot debug application

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#587]
I want to debug through the Android studio.
Do I need API key, do is this ? "echo git@repository:org/omim-private.git | ./configure.sh"

![2015-11-19 9 46 59](https://cloud.githubusercontent.com/assets/11851006/11260091/de0f9ca8-8ea2-11e5-983a-f69ae62f4f28.png)

![2015-11-19 9 51 48](https://cloud.githubusercontent.com/assets/11851006/11260124/353b89c4-8ea3-11e5-9418-775bbf999d5f.png)

**Comment by deathbaba** [comment]
This issue is pending merge in #568, please apply this change: https://github.com/deathbaba/omim/commit/709e6b2bdcbb376aa929a66bfcd0b29a5e0bbbf2 <https://github.com/deathbaba/omim/commit/709e6b2bdcbb376aa929a66bfcd0b29a5e0bbbf2>

**Comment by xingdavis** [comment]
@deathbaba ok
