### ISSUE TITLE
Build Failed for android

### ISSUE THREAD

**Issue by walkingtohorizon** [mapsme/omim#5897]
Here is what i did:
1, run ./configure.sh
2, install Clang, Boost and Qt 5
3. run ./set_up_android.py 
4. run ./gradlew clean assembleWebRelease
but when i run ./gradlew clean assembleWebRelease i get error
**+ echo 'ERROR while building armeabi-v7a config'
+ exit 1
ERROR while building armeabi-v7a config
:cppBuildDebug FAILED

FAILURE: Build failed with an exception.**
what did i do wrong? (i'm using ubuntu 16.04)

**Comment by Zverik** [comment]
Please find the `error:` in the build log, otherwise we cannot help you, anything could break.

**Comment by walkingtohorizon** [comment]
I'm adding build log here. please see and help me
+ echo 'ERROR while building armeabi-v7a config'
+ exit 1
ERROR while building armeabi-v7a config
:cppBuildDebug FAILED

FAILURE: Build failed with an exception.
build log: [log.txt](https://github.com/mapsme/omim/files/951238/log.txt)

**Comment by MrYadro** [comment]
`fatal error: '3party/Alohalytics/src/alohalytics.h' file not found`

I think all you need is to run `git submodule update --init --recursive`

**Comment by walkingtohorizon** [comment]
oh really cool. Thank you very much

**Comment by fukemy** [comment]
hello. i run "git submodule update --init --recursive" then got this message : " fatal: Not a git repository (or any of the parent directories): .git". I download project

**Comment by Zverik** [comment]
You are doing this from a `.git` directory. Please do `cd ..`.

**Comment by fukemy** [comment]
Hello. I post full step that finally got this problem.

Do-Dung-macbook:~ devil2010$ git clone https://github.com/mapsme/omim.git
Cloning into 'omim'...
remote: Counting objects: 370056, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 370056 (delta 0), reused 0 (delta 0), pack-reused 370051
Receiving objects: 100% (370056/370056), 3.17 GiB | 2.29 MiB/s, done.
Resolving deltas: 100% (250946/250946), done.
Checking out files: 100% (27558/27558), done.  Do-Dung-macbook:~ devil2010$ cd omim/        
Do-Dung-macbook:omim devil2010$ ./configure.sh 
If you are developer from MAPS.ME team, please specify a private repository url here.
If not [yet :)], then just press Enter.
-n > 

Initializing repository with default values in Open-Source mode.
Do-Dung-macbook:omim devil2010$ cd tools/
Do-Dung-macbook:unix devil2010$ cd ..
Do-Dung-macbook:tools devil2010$ cd android/
Do-Dung-macbook:android devil2010$ ./set_up_android.py 
Path to Android SDK, "s" to search []:s
Path to Android SDK [/Users/macos/Library/Android/sdk]:
Path to Android NDK, "s" to search []:s
Path to Android NDK [/Users/macos/Library/Android/sdk/ndk-bundle]:
Writing ./../../android/local.properties
Copying to ./../../android/YoPme/local.properties
Copying to ./../../android/YoPme2/local.properties
Copying to ./../../android/UnitTests/local.properties


Do-Dung-macbook:android devil2010$ cd ..
Do-Dung-macbook:tools devil2010$ cd ..
Do-Dung-macbook:android devil2010$ ./gradlew clean assembleWebRelease
....   make: *** [sub-3party-make_first] Error 2
+ echo 'ERROR while building armeabi-v7a config'
+ exit 1
ERROR while building armeabi-v7a config
:cppBuildRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cppBuildRelease'.
> Process 'command 'bash'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9 mins 50.297 secs
Do-Dung-macbook:android devil2010$

**Comment by fukemy** [comment]
plz help :)
