### ISSUE TITLE
Use mapsme as a library module

### ISSUE THREAD

**Issue by tranvantungit** [mapsme/omim#5983]
I would like to use mapsme as a library module for my android project, 
so Android directory is all I need?
Thanks for help!!

**Comment by Zverik** [comment]
Maps.me is not an api or a library. The `android` directory contains an entire application. Try [one of these](https://wiki.openstreetmap.org/wiki/Android#Libraries_for_developers).

**Comment by fukemy** [comment]
hello. Can i used as IOS Library?
