### ISSUE TITLE
Nearly completely useless "The place has gone or never existed" notes

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#6016]
Maps.me instead of POI deletion creates notes like 

> The place has gone or never existed. This is an auto-generated note from MAPS.ME application: a user reports a POI that is visible on a map (which can be outdated), but cannot be found on the ground

This kind of node is nearly useless as it is unclear what object is reported to be gone.

Please, please - include link to node/way/relation in such note to allow easy check what is reported,

I closed many, many notes like that without taking action as it was unclear from note what is reported and user failed to respond to comment asking for clarification.

Note that in some places POI density is extremely high and guessing by looking at closest POI is not helpful.

Note also that different map styles display different POIs, so object reported to be missing may be not visible at all to somebody checking report.

At this moment this type of note is really irritating to people attempting to handle them.

**Comment by yuryleb** [comment]
Even name of the referenced POI will be very usefull - "The place '{name} has gone or never exists" for example :wink:

**Comment by burivuh** [comment]
Added additional info in 7.3.3

**Comment by matkoniecz** [comment]
> Added additional info in 7.3.3

Can you link commit? I attempted creating report note but it failed to appear (may be a separate bug), I attempted to find commit by myself and it also failed.

**Comment by Zverik** [comment]
First, see this example note: https://www.openstreetmap.org/note/1009059
The pull request that fixes this issue: https://github.com/mapsme/omim/pull/6039
