### ISSUE TITLE
How open mwm file with Sqlite Browser

### ISSUE THREAD

**Issue by naeimrezaeian** [mapsme/omim#6075]
hi 
how i can open mwm file with Sqllite browser , after download map from this link daily.mapswithme.com/direct/latest
can not open file because need password !
![ttttttt](https://cloud.githubusercontent.com/assets/7207622/26164019/11d3aeb4-3b34-11e7-925c-a8e3b16dec6a.jpg)

?

**Comment by Zverik** [comment]
MWM files are not sqlite databases.
