### ISSUE TITLE
map view reload

### ISSUE THREAD

**Issue by Ozhvankov** [mapsme/omim#6113]
Hi guys!

so Can U Help me to re-render map view or reload map's (layers)

I'm tested new feature - something like "button" with different (categories) that show on the map right now!
but can't to re-draw (re-render ) the map with new layers information.

right now
user must to tap zoom to re-draw layers

Thanx.

**Comment by rokuz** [comment]
I can recommend you to look at m_forceUpdateScene = true; in FrontendRenderer class.

**Comment by Ozhvankov** [comment]
thanx 

right now I'a used 2 function 
checked state of [MWMSettings setLargeFontSize:value];
and then change LargeFontSize:value two times to make actual state 
and re-render layers :))) 
so Dirty trick I think

**Comment by rokuz** [comment]
I closed the issue, if you will have a problem in the future please reopen it. Good luck :)
