### ISSUE TITLE
Include OSM object ID in "The place has gone or never existed" notes

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#6142]
thanks to #6039 "The place has gone or never existed" notes include now information about name and type of reported objects (see for example https://www.openstreetmap.org/note/1009059#map=18/-33.55390/-70.67544&layers=N).

It would be a good idea to include also OSM id, preferable in form of URL (something along lines "OSM object link: https://www.openstreetmap.org/node/2528061153 ").

It would be helpful during editing allowing to much easier opening reported object.

**Comment by HolgerJeromin** [comment]
https://osm.org/node/2528061153
Would be shorter.

**Comment by Zverik** [comment]
I understand including OSM id would be the best option. Alas, we don't have these numbers in the data.
