### ISSUE TITLE
Can't build android application

### ISSUE THREAD

**Issue by ManWithAndroid** [mapsme/omim#6210]
I tried to follow all the installation steps (on windows and also on linux ubuntu):

- configure.sh
- set_up_android.py
- replace_links.bat
- gradlew.bat

But I allwayes get this error 

`Execution failed for task ':cppBuildRelease'`
`Process 'command 'bash'' finished with non-zero exit value 127`

(On windows, on linux the exit value is 1)

This is the gradle console in pastebin: https://pastebin.com/3xK7Kzqm

Did I missed something? I really try to run this for a few days...

I will rejoice in repentance
Thank.

**Comment by carlos-mg89** [comment]
Try thw using the NDK 13 as said here https://github.com/mapsme/omim/issues/6265

It might be the same problem the guy that opened the issue and I had. Good luck!
