### ISSUE TITLE
OSM edits lost

### ISSUE THREAD

**Issue by rugk** [mapsme/omim#6278]
Could it be that changes are lost when there are crashes during the survey?

E.g. add opening hours and the crash the phone. When the phone is restarted, these information seem to be lost.
Can't you save this in a reliable way offline until it is uploaded and then upload it?

**Comment by andree182** [comment]
#5954

**Comment by rugk** [comment]
Ah, thanks, so closing as a dupe of https://github.com/mapsme/omim/issues/6278.
