### ISSUE TITLE
False URLs in descriptions

### ISSUE THREAD

**Issue by thany** [mapsme/omim#6347]
In descriptions of bookmarks, any sequence of 4 or more numbers is underlined as if it is a URL. 

In most cases, 4 digits isn't a URL at all. It's almost always a date, a price, a year, or a time. 

If you must make phone numbers into links, please do so for numbers that:
1) Aren't prefixed or suffixed by a currency sign
2) Don't look like a date (like `12-04`)
3) Look like actual phone numbers.

Also do this only on a device that can make phone calls to begin with.

**Comment by Zverik** [comment]
We don't parse bookmark descriptions for phone numbers. Please address this report to your phone OS developers.

**Comment by thany** [comment]
There are many apps that don't have this problem, so it can't be blamed on the OS.
