### ISSUE TITLE
Input Fields in the Navigation Tab Not Showing?

### ISSUE THREAD

**Issue by itech4ever** [mapsme/omim#6455]
Hello everyone.  I just noticed that the locally compiled version for iOS (using the latest version or the 874 beta version) cannot give me the input fields that I found in the official Maps.me App from App Store (as attached). Could you let me know if I missed any configurations? Thanks a lot!

![mapsme](https://user-images.githubusercontent.com/2975230/27777415-f2368554-5ff5-11e7-8cb9-1698474a962a.PNG)

**Comment by rokuz** [comment]
Hi, now we are changing design, so there is no any error. These controls have been removed according to new vision. Did you see tooltips at the very bottom of screen when you tried to put start/finish point via placepage?

**Comment by itech4ever** [comment]
Thanks @rokuz , that explains. I will keep working then.

Yes, I did see tooltips.
