### ISSUE TITLE
Path planning can not be automatically corrected

### ISSUE THREAD

**Issue by xingdavis** [mapsme/omim#654]
In the navigation process, when the traveling path shift, can not automatically correct. Is there any way to change it?

**Comment by deathbaba** [comment]
Looks like a bug. Can you please provide more details (and probably screenshot)? Is it android/ios? Latest version from store?

**Comment by xingdavis** [comment]
IOS,Is the latest version. I'll make a test again, and then send a screenshot

**Comment by xingdavis** [comment]
The same with this issue #721

**Comment by deathbaba** [comment]
Looks like it was already fixed on a master branch. Have you re-checked it?

**Comment by xingdavis** [comment]
@deathbaba It's ok now.
