### ISSUE TITLE
car routing through barrier=bollard

### ISSUE THREAD

**Issue by autinerd** [mapsme/omim#6670]
The current version of MAPS.ME is routing cars through barrier=bollard, which could lead to a problem when the user sees it too late and there is no possibility to turn around easily. (See screenshot)

![img_6027](https://user-images.githubusercontent.com/27780930/28497495-cd2a4848-6f88-11e7-96e0-1a6c3ce8b42e.PNG)

**Comment by my-na-me** [comment]
*** urgent *** ;-)

any update?

I don't want to start "mapping" for the renderer or  respectively for the navigation-app

**Comment by flick3** [comment]
Have the same problem. Maps.me has just been updated, but the issue is still there.

**Comment by burivuh** [comment]
Hi! We're sorry, but this feature is still in development.

**Comment by my-na-me** [comment]
@burivuh: Thank you very much for your response & your info about that this ticket is in progress.

btw. tested it by using recently installed v7.5.3 and the issue is still open.

take your time, I hope this will be working some day :-)

**Comment by vincentdephily** [comment]
Not just routing through bollards, but potentially any kind of gate, and specifically http://www.openstreetmap.org/node/1642572279 and http://www.openstreetmap.org/node/1642572284 which even have an `access=no` tag.

**Comment by my-na-me** [comment]
Hi this issue seems solved.
Could you confirm this?

By the way, did this pull fix it?:
https://github.com/mapsme/omim/pull/7882
Or one of the others?:
https://github.com/mapsme/omim/pulls?utf8=%E2%9C%93&q=barrier

**Comment by tatiana-yan** [comment]
Bollards and access=no fixed. There were several pulls which fix road access for roads marked access tags, for barriers and for better tags ordering (i.e. for cars motorcar tag, than motorvehicle if motorcar does not exists, than vehicle, than access than trying to guess based on barrier type). The main one for barriers is #7882. If you want to find minor requests just look at generator/road_access_generator.cpp changes history.
