### ISSUE TITLE
Can I use this maps server configuration?

### ISSUE THREAD

**Issue by ManWithAndroid** [mapsme/omim#6803]
Hi,
I changed the ChunkTask.java so I can have access to the http://direct.mapswithme.com/direct/ maps server:

    String tempServerUrl = "http://direct.mapswithme.com/direct/";
    if(/* mUrl is my url */ true) {
        String[] urlSections = mUrl.split("/");
        //               Maps version      /    File name
        tempServerUrl += urlSections[4] + "/" + urlSections[5];
        //http://direct.mapswithme.com/direct/version/file.mwm
    
    } else {
        tempServerUrl = mUrl;
    }
        
    final URL url = new URL(tempServerUrl);
    urlConnection = (HttpURLConnection) url.openConnection();

Is this OK? Can I use this code?
Thanks.

**Comment by Zverik** [comment]
It is okay for private usage, but if you intend to share your forked app or even publish it on some store, you would need to set up your own maps server.
