### ISSUE TITLE
U Turn restriction

### ISSUE THREAD

**Issue by jalvesaq** [mapsme/omim#6861]
In some cases, it is allowed to turn left, but not to make a u-turn. Example: https://www.openstreetmap.org/directions?engine=osrm_car&route=-3.74684%2C-38.54205%3B-3.74690%2C-38.54239#map=18/-3.74638/-38.54297
However, Maps.me is not respecting U-Turn restrictions:
![screenshot_2017-08-11-16-04-51](https://user-images.githubusercontent.com/891655/29232401-ceb381a0-7ec1-11e7-98d7-fcf413cecba4.png)

**Comment by matkoniecz** [comment]
I also encountered it yesterday - maps me completely ignored http://www.openstreetmap.org/relation/2099958#map=19/49.98784/19.91455 and produced route that was illegal to follow (despite correct OSM tagging).

**Comment by matkoniecz** [comment]
As recommended
in
https://github.com/mapsme/omim/blob/968f8283fec37681f9499d6dca1a3db2f66390ef/docs/CONTRIBUTING.md
I also send an email to bugs@maps.me after reporting this problem at bug
tracker

**Comment by matkoniecz** [comment]
@mapsme can you respond? This is a major bug that makes car routing completely useless in countries where u turn restriction may appear.

Even "we are busy with fatal bugs, we will fix it later" would be nice.

Lack of reaction to reports like this discourages bug reporting.

**Comment by burivuh** [comment]
Hi!

I'm sorry, our QA was too busy for a few weeks and couldn't properly react. Bug will be created soon, thank you.

**Comment by jalvesaq** [comment]
The issue remains in Maps.me 7.5.3-Google, Data version 170917.

**Comment by jalvesaq** [comment]
Still not fixed (8.0.1-Google, Data version 171208)...

**Comment by matkoniecz** [comment]
It seems that mapsme mostly ignites this bug tracker, it was even mentioned that they have some real internal one.

**Comment by bykoianko** [comment]
@jalvesaq and @matkoniecz thanks you for your reports and sorry for late reply!

We're aware of the problem you've mentioned about. The reason is we support only line-point-line restriction now. The restriction you wrote about (https://www.openstreetmap.org/relation/7387135, http://www.openstreetmap.org/relation/2099958#map=19/49.98784/19.91455) is line-line-line and our router doesn't support it. We're planning to support all relation:restriction according to osm spec in the future but I can't give a date.

Vladimir

**Comment by eFrysTon** [comment]
With the new version of the turn restriction editor in iD, if you select the way that leads into the # intersection and then click on the appropriate button to create a "no u-turn" restriction, a two way via restriction like I linked above is automatically created.

**Comment by jalvesaq** [comment]
Unfortunately, the issue is not fixed yet: MAPS.ME 8.6.2-Google, Data version 181213.

**Comment by jalvesaq** [comment]
Still not fixed.

**Comment by jalvesaq** [comment]
Another example of wrong route calculation due to not considering turn restriction when the "via" element is a highway:

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-3.78190%2C-38.55580%3B-3.78191%2C-38.55892

In the above example, drivers traveling from East to West on Silas Munguba Avenue cannot turn left on José Meneleu street. Only drivers coming from Padre Carlos Quixadá street can cross the Silas Munguba Avenue and go to José Meneleu Street, as correctly calculated by OSRM:

![Route_correct](https://user-images.githubusercontent.com/891655/56461406-e3cbd800-6388-11e9-9067-edd5836ebc81.png)


However, users of MAPS.ME would be oriented to turn left which is not only forbidden but also dangerous because the traffic signal would be green for drivers coming from West to East on Silas Munguba Avenue:

![Route_maps me](https://user-images.githubusercontent.com/891655/56461413-f34b2100-6388-11e9-8507-1ea668e557dc.png)


If the driver is careful enough to not turn left, the new route to reach the destination is 2 km longer:

![Route_post_error](https://user-images.githubusercontent.com/891655/56461414-f9d99880-6388-11e9-8e29-f3f6957d6721.png)

**Comment by tatiana-yan** [comment]
Hello. Our routing team is working with these issues right now, see https://github.com/mapsme/omim/pull/10640

**Comment by jalvesaq** [comment]
@tatiana-yan the pull request https://github.com/mapsme/omim/pull/10640 was merged on May 6, but the issue still isn't fixed in Maps.me 9.1.8-Google (data version 190621, Android version 8.1.0).

**Comment by tatiana-yan** [comment]
@gmoryes @bykoianko @vmihaylenko FYI

**Comment by tatiana-yan** [comment]
release-91 branch was created on April 23.
Releases 9.1.0 - 9.1.8 have only serverside modifications, new data and bug fixes.
We are planning to release 9.2 in two weeks. Please check this version.

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by tatiana-yan** [comment]
You are welcome.
Code from master branch builds this route:
<img width="939" alt="Screenshot 2019-07-05 at 20 17 56" src="https://user-images.githubusercontent.com/9213190/60737074-120d8c80-9f62-11e9-985c-5cdf8ccd036a.png">

is it ok?

**Comment by jalvesaq** [comment]
Yes, both routes are correct! The first one seems to prioritize main roads and avoid residential roads and the second seems to prioritize the shortest route. Thanks!

**Comment by jalvesaq** [comment]
It's fixed now (9.2.2-Google, data version 190727). Thank you!
