### ISSUE TITLE
add option to hide hotels from booking.com

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#6881]
at least for some users this is completely useless data cluttering map

what worse, in many cases location quality is poor resulting in hotels scattered in weird locations like center of road

Would it be possible to add option buried in advanced settings so people who really hate it may disable it (making it opt-out would probably result in negligible influence on income from affiliate links or whatever method that is used to earn money from that)

**Comment by jancborchardt** [comment]
Duplicate of https://github.com/mapsme/omim/issues/6279

**Comment by matkoniecz** [comment]
#6279 is about hiding all hotels, mine is about hiding merely poorly positioned ones from booking.com

**Comment by jancborchardt** [comment]
Then it's a duplicate of #5357 ;)

**Comment by matkoniecz** [comment]
Thanks!

**Comment by rpodgorny** [comment]
i've just spent entire hour walking in circles and asking people where the hotel is! ...this is not the first time - to hell with booking.com!
