### ISSUE TITLE
missing install documentation for Ubuntu 16

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#6890]
https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#ubuntu-1404 has documentation for Ubuntu 14 LTS, Ubuntu 16 LTS documentation is missing

**Comment by matkoniecz** [comment]
As recommended in https://github.com/mapsme/omim/blob/968f8283fec37681f9499d6dca1a3db2f66390ef/docs/CONTRIBUTING.md I also send email to bugs@maps.me

**Comment by Zverik** [comment]
On Ubuntu 16.04 you need to install qt5-default and libsqlite3-dev. And then run build_omim.sh -r

If it works, please consider making a pull request to that documentation file :)

**Comment by matkoniecz** [comment]
instructions so far:

start:
```
sudo apt-get install qt5-default and libsqlite3-dev
tools/unix/build_omim.sh -r
```
but info from build_omim output announced that configure.sh is necessary before that.

```
sudo apt-get install qt5-default and libsqlite3-dev
configure.sh
tools/unix/build_omim.sh -r
```

**Comment by matkoniecz** [comment]
@Zverik What is your source and version of protobuf?

**Comment by rokuz** [comment]
Hi, you have to use protobuf from our sources. It's included as a submodule. Version - 3.3.0

**Comment by matkoniecz** [comment]
@rokuz Thanks!  I now progressed to a new error, `o rule to make target 'protobuf/src/google/protobuf/arena.cc', needed by '../../out/release/tmp/protobuf/arena.o'.  Stop.`.

I was missing `git submodule update --init --recursive` step. I did that and now I have:

```Makefile:2847: recipe for target '../out/release/tmp/drape_frontend/choose_position_mark.o' failed
```

full log at https://gist.github.com/matkoniecz/fabee03af7ae528893c7096e62d65825

How one enables more verbose output for `tools/unix/build_omim.sh -r`? It would be nice to know why it failed.

**Comment by rokuz** [comment]
We have 2 autogenerated files: shader_def.hpp and shader_def.cpp. By some reason these files have not been generated. Try run qmake for drape_frontend project

**Comment by matkoniecz** [comment]
```
mateusz@grisznak:~/Desktop/tmp/omim - maps.me/drape_frontend$ qmake
python: can't open file '/home/mateusz/Desktop/tmp/omim': [Errno 2] No such file or directory
WARNING: Failure to find: shader_def.cpp
```

`qmake -r` is doing the same

```
mateusz@grisznak:~/Desktop/tmp/omim - maps.me/drape_frontend$ qmake -Wall
python: can't open file '/home/mateusz/Desktop/tmp/omim': [Errno 2] No such file or directory
WARNING: /home/mateusz/Desktop/tmp/omim - maps.me/common.pri:137: Unescaped backslashes are deprecated
WARNING: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:101: Excess colon in front of opening brace.
WARNING: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:244: Excess colon in front of opening brace.
WARNING: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:255: Excess colon in front of opening brace.
WARNING: Failure to find: shader_def.cpp
```

revealed problem with whitespace in a path (I will open a new issue for that)

I removed whitespace from path and something was compiled, I will produce pull request soon.

-----

Current build instructions (may be complete):

```
ensure that repository path is free from any whitespace (due to https://github.com/mapsme/omim/issues/6999)
sudo apt-get install qt5-default and libsqlite3-dev
configure.sh
tools/unix/build_omim.sh -r
```

Thanks for the help!

**Comment by matkoniecz** [comment]
@rokuz @Zverik 

I run tests (tested using /omim-build-release/out/release build), some tests are failing. Is it because something went wrong during compilation or is it a known problem?

```
tested using /omim-build-release/out/release build
--

tests are mostly passing but there are some failures, examples are included below. Is it a known problem, result of running tests in a wrong way or is it indicator that compiled program is broken?

```
Running ./opening_hours_tests...
Running 23 test cases...
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1337): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1340): error: in "OpeningHours_TestIsActive": check IsActive(rules[1], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1447): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1467): error: in "OpeningHours_TestIsActive": check IsActive(rules[0], time) has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1540): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-07-09 16:50") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1562): error: in "OpeningHours_TestIsOpen": check IsClosed(rules, "2012-10-08 15:59") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1575): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-04-10 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1576): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-05-01 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1577): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2015-04-11 07:15") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1596): error: in "OpeningHours_TestIsOpen": check IsOpen(rules, "2017-05-31 23:35") has failed
/home/mateusz/Desktop/tmp/omim_-_maps.me/3party/opening_hours/opening_hours_tests/opening_hours_tests.cpp(1606): error: in "OpeningHours_TestIsOpen": check !IsOpen(rules, "2017-05-31 23:35") has failed

*** 11 failures are detected in the test module "OpeningHours"


---------

Running bookmarks_test.cpp::Bookmarks_ImportKML
Settings path: /home/mateusz/.config/MapsWithMe/settings.ini
Loaded countries list for version: 160301
Tracking Reporter started
There is no cached user stats info in settings
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: WorldCoasts_obsolete in directory: 
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loaded countries list for version: 170703
Loaded countries list for version: 170703
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: 
Found file: WorldCoasts_obsolete in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loading map: World
Loading map: WorldCoasts
Loading map: minsk-pass
System languages: en_US
Loaded 0 modified, 0 created, 0 deleted and 0 obsolete features.
Editor initialized
Invalid timestamp in Placemark: 2048 bytes in two kilobytes - some invalid timestamp
FAILED
map_tests/bookmarks_test.cpp:123 TEST(cat.GetUserMarkCount() == 4) 0 4 
Tracking Reporter finished
Test took 401 ms

Running bookmarks_test.cpp::Bookmarks_ExportKML
Loaded countries list for version: 170703
Tracking Reporter started
There is no cached user stats info in settings
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: 
Found file: WorldCoasts_obsolete in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loading map: World
Loading map: WorldCoasts
Loading map: minsk-pass
System languages: en_US
Loaded 0 modified, 0 created, 0 deleted and 0 obsolete features.
Editor initialized
Invalid timestamp in Placemark: 2048 bytes in two kilobytes - some invalid timestamp
FAILED
map_tests/bookmarks_test.cpp:123 TEST(cat.GetUserMarkCount() == 4) 0 4 
Tracking Reporter finished
Test took 226 ms


Running bookmarks_test.cpp::Bookmarks_InnerFolder
Loaded countries list for version: 170703
Tracking Reporter started
There is no cached user stats info in settings
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: 
Found file: WorldCoasts_obsolete in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loading map: World
Loading map: WorldCoasts
Loading map: minsk-pass
System languages: en_US
Loaded 0 modified, 0 created, 0 deleted and 0 obsolete features.
Editor initialized
Icon poiIcon37 for point [P] Silvrettastrae[Bieler Hhe] is not supported
FAILED
map_tests/bookmarks_test.cpp:547 TEST(cat.GetUserMarkCount() == 1) 0 1 
Tracking Reporter finished
Test took 233 ms

Running bookmarks_test.cpp::TrackParsingTest_1
Loaded countries list for version: 170703
Tracking Reporter started
There is no cached user stats info in settings
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: 
Found file: WorldCoasts_obsolete in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loading map: World
Loading map: WorldCoasts
Loading map: minsk-pass
System languages: en_US
Loaded 0 modified, 0 created, 0 deleted and 0 obsolete features.
Editor initialized
Icon style6 for point U-turn is not supported
Icon style5 for point Wat Toei is not supported
Icon style3 for point Option1 is not supported
Icon style2 for point Pakkred1 is not supported
Icon style4 for point Pakkred2 is not supported
Icon style1 for point Pakkred3 is not supported
FAILED
map_tests/bookmarks_test.cpp:631 TEST(cat->GetTracksCount() == 4) 0 4 
Tracking Reporter finished
Test took 234 ms

Running bookmarks_test.cpp::TrackParsingTest_2
Loaded countries list for version: 170703
Tracking Reporter started
There is no cached user stats info in settings
New preferred locale: en
New preferred locale: en_US
Found file: World in directory: 
Found file: WorldCoasts in directory: 
Found file: WorldCoasts_obsolete in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Found file: minsk-pass in directory: /home/mateusz/Desktop/tmp/omim-build-release/out/release/../../data/
Loading map: World
Loading map: WorldCoasts
Loading map: minsk-pass
System languages: en_US
Loaded 0 modified, 0 created, 0 deleted and 0 obsolete features.
Editor initialized
Icon m_ylw-pushpin for point XY is not supported
FAILED
map_tests/bookmarks_test.cpp:657 TEST(cat->GetTracksCount() == 1) 0 1 
Tracking Reporter finished
Test took 233 ms

Running geourl_test.cpp::ProcessURL_Smoke
FAILED
map_tests/geourl_test.cpp:13 TEST(my::AlmostEqualULPs(info.m_lat, 53.666) 53 53.666 
Test took 0 ms

Running geourl_test.cpp::ProcessURL_Instagram
FAILED
map_tests/geourl_test.cpp:47 TEST(my::AlmostEqualULPs(info.m_lat, 54.683486138) 54 54.6835 
Test took 0 ms

Running geourl_test.cpp::ProcessURL_GoogleMaps
FAILED
map_tests/geourl_test.cpp:57 TEST(my::AlmostEqualULPs(info.m_lat, 1.3067198) 1 1.30672 
Test took 0 ms
```

**Comment by mhstnsc** [comment]
For me on ubuntu16 compiling with stock qt5 did not work bcause of qtMultimedia widgets or something. So after changing some paths in the qtchooser it compiled however then it does not start because of missmatch between protobuf versions.

```
$ ./MAPS.ME
LOG TID(1) DEBUG  1.6664e-05 platform/platform_linux.cpp:192 Platform() Resources directory: /
LOG TID(1) DEBUG  8.0153e-05 platform/platform_linux.cpp:193 Platform() Writable directory: /
LOG TID(1) DEBUG  9.0441e-05 platform/platform_linux.cpp:194 Platform() Tmp directory: /tmp/
LOG TID(1) DEBUG 0.000100375 platform/platform_linux.cpp:195 Platform() Settings directory: /home/mihai.stanescu/.config/MapsWithMe/
LOG TID(1) DEBUG 0.000183855 platform/platform_linux.cpp:196 Platform() Client ID: c1b6deebc9984495b16a2973e5e653c3
[libprotobuf FATAL /home/mihai.stanescu/work/omim/3party/protobuf/protobuf/src/google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.3.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
Aborted (core dumped)
```

**Comment by matkoniecz** [comment]
https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#ubuntu-1604 is now present, I will open a new issue for missing install instruction for 20.04
