### ISSUE TITLE
Run car route

### ISSUE THREAD

**Issue by 21212124** [mapsme/omim#6964]
I have use Ubuntu 16.04.03 to run aplication.

I'm following these steps: "https://github.com/mapsme/omim/blob/master/docs/MAPS.md". 

I have run this commnad: omim/tools/unix/generate_mwm.sh source.pbf any_random_string_asdf and when I open the application and click on Start point nothing happens. (look at image 1)
![1](https://user-images.githubusercontent.com/30496643/29657831-3226645e-88b9-11e7-96f7-4ba3f0fcb0a0.jpg)

Can anybody help me?
@gardster @biodranik

**Comment by biodranik** [comment]
You can try to analyze the app's log for debug build.
