### ISSUE TITLE
tools/Android/update_assets.sh doesn't exist

### ISSUE THREAD

**Issue by fuadj** [mapsme/omim#6994]
Compared nightly build with the one I tired to compile and found my assets are missing

Solves the problem of https://github.com/mapsme/omim/issues/6860

So how do I update my assets so that sub folders like assets/countries-strings/ exist?

**Comment by Zverik** [comment]
It should not be needed, since all assets there are stored as symlinks to the data directory.

**Comment by fuadj** [comment]
One thing though, the generated apk's assets folder doesn't have subfolders like 
"assets/countries-strings" which was the reason it was also crashing in the debug version.
Attached is the snapshot of assets folders from the extracted my local apk and the one I downloaded from _nightly build_.
![apk differences](https://user-images.githubusercontent.com/1276157/29838883-25b7616e-8d05-11e7-8e90-f4b230497a31.png)

**Comment by Zverik** [comment]
As you can see in https://github.com/mapsme/omim/tree/master/android/assets , the repository contains symlinks for all the directories. There must have been some error when you cloned it.

**Comment by fuadj** [comment]
Yes the symlinks exist, but somehow they are not being compiled into the
android app.

**Comment by fuadj** [comment]
You are right, the problem is the repo was cloned in a **WINDOWS** PC(I'm on linux, had to do it b/c my internet connection isn't fast enough as that PC).

Is it possible to fix the symlinks or do i have to re-clone it?

**Thnx**: for the patience, I've been trying to run the app for past month.

**Comment by Zverik** [comment]
You can create symlinks manually, with `ln -s ../../data/countries-strings .` for each of the directories from inside the `assets` directory.

**Comment by fuadj** [comment]
But doesn't the whole repository also use symlinks for other places, 
i run this and it list a ton of links [https://stackoverflow.com/a/5930443/5753416](url)

**Comment by Zverik** [comment]
Well, for all symlinks in all directories it would be safer to re-clone the whole repository, of course. If you don't plan to do pull requests, try `git clone --depth 1 --recurse-submodules`, and `--branch release-75` if you need the current release branch.

**Comment by fuadj** [comment]
Thanks, really appreciated.

**Comment by fuadj** [comment]
What pointers do you have for me to familiarize with the codebase, (especially android).
And also, omim has Apache 2.0 License, does that mean I can use it for commercial purposes.
