### ISSUE TITLE
Maps.me for destkop

### ISSUE THREAD

**Issue by 21212124** [mapsme/omim#6995]
I am using the MAPS.ME version for desktop and I want to use it to make an embedded system. Can it be done in any way so that the desktop version shows me the route and guides me?
@Krisk0 @Zverik @biodranik @dpa99c @gardster @burivuh @bykoianko @rokuz 

When I clicked on Follow Route it does nothing?
What I can doing?
![1](https://user-images.githubusercontent.com/30496643/29816644-23eea84c-8cb5-11e7-8cdc-d823675d51b3.jpg)

**Comment by rokuz** [comment]
Hi, unfortunately we don't have fully functional version for desktop. We use it only as developers' sandbox.

**Comment by 21212124** [comment]
But can it be done? it's possible?
I have to write a lot of code?
@rokuz

**Comment by rokuz** [comment]
Surely, you can do it if you'd like. It's not easy, but possible. Yeah, it may be a lot of code. Anyway, good luck.

**Comment by vn971** [comment]
@rokuz maps.me version for desktop would be totally awesome!

**Comment by vn971** [comment]
@21212124 can you please give a bit more details on closing the issue? Is the Desktop version considered never to be implemented, or just this bug is considered irrelevant, or..?

**Comment by 21212124** [comment]
Someday it will be implemented but it is not up to me. I am with other projects now.

**Comment by vn971** [comment]
@21212124 hmm, but if you close the issue, then it's not only about your personal time availability, but project-s decision?

Anyway, I guess a proper issue should be opened like "please add support for a Desktop version" (which indeed would be tremendously awesome BTW).

**Comment by 21212124** [comment]
the project took another different path

**Comment by vn971** [comment]
@21212124 in what way, if you don't mind telling? E.g. drop of support of some things, or focus on something?

**Comment by 21212124** [comment]
I didn't deserve such an effort for our project
