### ISSUE TITLE
How to set the map direction?

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#700]
How to set(change) map direction acorrding to the routing direction the routing direction, while the routing is active.

**Comment by deathbaba** [comment]
Can you please clarify your question? Do you want to rotate map in a different way than it is implemented right now?
CC @bykoianko @rokuz

**Comment by simon247** [comment]
Yes, the map could be rotated according the User forward direction automaticity.

**Comment by deathbaba** [comment]
Are you speaking about walking directions mode or about car navigation mode?

**Comment by simon247** [comment]
![a](https://cloud.githubusercontent.com/assets/3993689/11390136/efdc8764-9381-11e5-91c3-808e39cd6fbd.png)

**Comment by simon247** [comment]
Hi @deathbaba, Got it, thanks.
![a](https://cloud.githubusercontent.com/assets/3993689/11390157/193b3736-9382-11e5-8147-64612391a63c.png)
