### ISSUE TITLE
allow changing language used by "add a place"

### ISSUE THREAD

**Issue by matkoniecz** [mapsme/omim#7002]
Entire program is in the English, even local names are displayed in English if name:en is provided but adding place requires using local language.

It is especially weird as language of the system is set to English.

It would be preferable to use for consistency English also during selecting a category of added place.

Also, I am quite curious how maps.me decided that it should display category names in Polish. In my case guess was not wrong but I guess that for tourist it would be baffling to get this selection menu in local language.

**Comment by burivuh** [comment]
Hi!

You can always add just name:en without local language name. I can't see the problem.

If there's no bug (and you use a vanilla firmware), then app uses keyboard language or locale (it depends on Android version) to decide what category translation to use.

**Comment by matkoniecz** [comment]
To clarify:

I want be able to have "add place" category selection menu in English, like other parts of the program. maps.me attempts to be smart and as results most of the program is in the English (like my system) and for no good reason "add place" category selection menu is in English.

Android 6.0.1, Xiaomi Redmi 4.

**Comment by mxa** [comment]
@matkoniecz which language is your keyboard?

**Comment by mxa** [comment]
Possible ~~dup~~__trip__licate of https://github.com/mapsme/omim/issues/3448 and https://github.com/mapsme/omim/issues/3974

**Comment by matkoniecz** [comment]
@mxa Polish as primary language, English as secondary.

**Comment by matkoniecz** [comment]
Duplicate of #3974, #3448 is about another bug with #3974 as root cause
