### ISSUE TITLE
Add geysers to map style.

### ISSUE THREAD

**Issue by JesseCrocker** [mapsme/omim#7042]
This summer i have deleted 20+ incorrectly tagged duplicates of existing geysers in Yellowstone national park that have been added to OpenStreetMap by maps.me users, I believe these duplicates are happening because maps.me does not show geysers, so the users are assuming that the geysers are not mapped, so they end up mapping them as springs.

Information about tagging for geysers: http://wiki.openstreetmap.org/wiki/Tag:natural%3Dgeyser

**Comment by hybridOL** [comment]
This holds for hundreds of other tags as well, and cannot be avoided completely, if not all objects are always shown.
But, important tags, which are either important for navigation or important for tourists should always be checked for inclusion to maps. Geysers are definitely worth including, as they are major touristic targets.

**Comment by JesseCrocker** [comment]
Any chance this will ever get dealt with? Im getting tired of deleting duplicate geysers your users keep adding in yellowstone. It's getting close to the point where im just going to build a bot to auto-revert any change in yellowstone from a maps.me user.

**Comment by tatiana-yan** [comment]
Hello.
We'll add geysers in 8.5 release (~November).

**Comment by tatiana-yan** [comment]
https://github.com/mapsme/omim/pull/9568

**Comment by JesseCrocker** [comment]
Thank You!
