### ISSUE TITLE
Missing STYLES.md content

### ISSUE THREAD

**Issue by adrianalin** [mapsme/omim#7170]
Can't find any details on how to obtain drules_proto.bin from MapCSS.
https://github.com/mapsme/omim/tree/master/docs/STYLES.md missing content.

Can someone provide me with the steps to compile and load a new map style?

**Comment by stevegdavis** [comment]
I did some re-styling of the map styles some time ago in 2015, but you will need to build the MAPS.ME app as a debug build or use a beta version of the app (I built it under Windows 7), maybe now closed issue #894 will help.

**Comment by Zverik** [comment]
pip install protobuf
tools/unix/generate_styles.sh
(or generate_drules.sh for just drules_proto.bin)

**Comment by adrianalin** [comment]
Hello, thanks for replying.
The thing is that i want to add a new style, for example this one http://wiki.openstreetmap.org/wiki/MapCSS/Examples.
For this i followed these steps: 
1. create an example.mapcss file where i copy and paste the content from the example.
2. run tools/unix/generate_styles.sh -s data/styles/example.mapcss -o druls_example_proto.bin
3. compile and run the omim app in debug mode on laptop (using lubuntu)
No results are seen. I would expect to see a map simillar with the one from example.
What am i doing wrong?

**Comment by Zverik** [comment]
As for drules_example_proto — the app only reads `drules_proto_clear.bin`.

As for KeyError: line — look for `[line]` in your mapcss, that would be an error.
