### ISSUE TITLE
[bug] Couldn't be rebuilded routing automatically 

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#721]
Hi @deathbaba, When  the User out of the routing path, it couldn't be rebuilded routiong path automatically.
![c](https://cloud.githubusercontent.com/assets/3993689/11414014/4a23d5a2-942b-11e5-9835-7664ca9a58d4.png)

Maybe there some bug here:
![d](https://cloud.githubusercontent.com/assets/3993689/11414076/f3c0ddee-942b-11e5-8c6c-845e18e0e943.png)

**Comment by deathbaba** [comment]
Thanks for reporting! Is it an App-Store version or from master branch?
@bykoianko @gardster  Can you check it please?

**Comment by simon247** [comment]
master branch

**Comment by gardster** [comment]
This bug was fixed on 10 Nov. Commit: https://github.com/mapsme/omim/commit/4ef24c1559d71c0f0339d38fac145e52510cc8f9#diff-0e856d6860f30ac3870848f7ca1a16c5
This is not the actual master branch!
