### ISSUE TITLE
Bug: Can't select POI type when typing on Russian

### ISSUE THREAD

**Issue by Semigradsky** [mapsme/omim#7328]
MAPS.ME version: 7.5.4-Google
Android 6.0.1 MMB29M

----

Something has happened and now I can't select POI type when typing on Russian.

It's working for English:
![image](https://user-images.githubusercontent.com/1198848/31709961-4a809862-b3fc-11e7-9962-78fdc68d2cc6.png)

But not working for Russian:
![image](https://user-images.githubusercontent.com/1198848/31709964-4e101016-b3fc-11e7-9552-0b95730c906d.png)

**Comment by Alexuser1** [comment]
Hello @Semigradsky !

We plan to fix it in our next release.

Thanks and Regards,
Alexander

**Comment by Semigradsky** [comment]
No reproducing more
