### ISSUE TITLE
Traffic jams layer

### ISSUE THREAD

**Issue by PaulAnnekov** [mapsme/omim#736]
Please, add traffic jams layer. Good feature that needs an investigation:
1. You can use some existing projects that will help analyze GPS data sent from maps.me app by drivers. [opentraffic](https://github.com/opentraffic) looks like what I said.
2. Create your open service that will collect this data.

**Comment by deathbaba** [comment]
Thanks, it's in our plans for the future.

**Comment by socketpair** [comment]
А в планах есть маршрутизация с учетом яндекс пробок ? Если да - то всё, ни одной киллер фичи у конкурентов не будет.  Ну может тока диктовка адреса. Но один фиг изза шума и радио оно не работает как положено.

Так как находить соответствия между векторными картами невозможно, может, накладывать яндекспробки как картинку, и те места что попали на осм дороги - помечать что там пробка. Конечно не так примитивно, но суть идеи в этом.

**Comment by PaulAnnekov** [comment]
@socketpair 1st of all, I don't think that yandex traffic jams license will allow to integrate them with maps.me. 2nd, both maps are too different, it will be much more simpler and logical to create own traffic jams component.

**Comment by deathbaba** [comment]
Correct. We don’t plan to license Yandex Traffic, because it’s not global.

We either start our own (or crowd sourced) traffic project, or join any existing open one.

**Comment by PaulAnnekov** [comment]
@deathbaba did you take a look at [opentraffic](https://github.com/opentraffic) (I didn't :pensive:)? What do you think of it?

**Comment by deathbaba** [comment]
Not yet. Will check it out, thanks.

**Comment by Paviluf** [comment]
It would be very great to have traffic on Maps.me.

**Comment by Paviluf** [comment]
For info, I contacted opentraffic.io to ask them if we can use freely their data and this is their answer
> Alyssa Wright, Oct 14, 13:52 PDT
> 
> Hello Jeremy,
> 
> Thank you for contacting us at OpenTraffic headquarters. We appreciate your traffic interest. We are currently locked in the basement preparing a large scale unveiling of the platform. Once released you will be able to freely use the traffic data!
> 
> We recommend joining our newsletter to follow our progress and stay involved: http://eepurl.com/cg7Ncb
> 
> Kind regards,
> The OpenTraffic Team.

**Comment by utack** [comment]
Seems to be included now, can this be closed?

**Comment by PaulAnnekov** [comment]
@utack attach a link to PR if it's included. I don't see it.

**Comment by utack** [comment]
True, I heard it did not show up in iOs yet, Android version 7.0.5 does have that new traffic layer

**Comment by PaulAnnekov** [comment]
Probably only testers have access to it in Google Play. Anyway, I see a lot off PRs with `traffic` keyword, so they have already implemented this feature and we should wait for apps release. Will close this issue.

**Comment by Paviluf** [comment]
That's awesome guys ! I'm eager to test it.
Thanks !

**Comment by PaulAnnekov** [comment]
I see only 36 countries are supported now and, as I understand, my country (Ukraine) is not in this list, because I get error in app ver 7.0.5. Could anyone send a link to code where these countries defined or at least write them here.

**Comment by bonanza123** [comment]
@PaulAnnekov I guess that is not easy to say because in my case MAPS.ME requested map updates before I could use traffic information. I guess the "trigger" whether its available is in the maps.

Does anyone know where the traffic data is coming from? Are we users also contributing to this data?

**Comment by PaulAnnekov** [comment]
Traffic jams availability is controlled from here https://github.com/mapsme/omim/blob/0fee76b13821f31460095e7066673635bc1b085b/traffic/traffic_info.cpp. grep for `NoData`. If server responds with 404, then you will see `traffic_data_unavailable` localized message. Maybe countries list is not exposed in this repo.

Url for getting traffic data is composed here https://github.com/mapsme/omim/blob/0fee76b13821f31460095e7066673635bc1b085b/traffic/traffic_info.cpp#L66, but `TRAFFIC_DATA_BASE_URL` value is not in this repo too :(.

**Comment by bam80** [comment]
Is it clear now from which source the traffic data is coming from?

**Comment by serdmx** [comment]
Tell me, please


>Четверг,  4 января 2018, 2:46 +03:00 от bam80 <notifications@github.com>:
>
>Is it clear now from which source the traffic data is coming from?
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
nissan primera

**Comment by bam80** [comment]
Seems the `TRAFFIC_DATA_BASE_URL` is hidden from the repo:
https://twitter.com/mak_sim_mak/status/814032857463189504
Maybe we could sniff it?

**Comment by utack** [comment]
https://traffic.maps.me/ ?

**Comment by bam80** [comment]
@utack how did you know it?

**Comment by utack** [comment]
OS-Monitor lists all open connections  
https://f-droid.org/packages/com.eolwral.osmonitor/
![screenshot_20180104-033317](https://user-images.githubusercontent.com/8551234/34548089-2579a9e6-f100-11e7-8352-bda4c68181a2.png)
