### ISSUE TITLE
How to run own Map server ?

### ISSUE THREAD

**Issue by chathudan** [mapsme/omim#759]
I build Android client successfully and it working. I would like to have my own map server so  
I downloaded latest maps from http://direct.mapswithme.com/direct/latest/ and edited  DEFAULT_URLS_JSON. But I cannot download the maps using Android app.  Are there any specific configurations ?

**Comment by deathbaba** [comment]
There are no any specific configurations. Please check adb error logs on a device to understand what is going wrong.

**Comment by chathudan** [comment]
Thank you for your reply , I'm getting
 platform/servers_list.cpp:30 ParseServerList()  Can't parse server list json: 1 '[' or '{' expected near 'https' https://MY_SERVER/maps/151103/

**Comment by deathbaba** [comment]
So your json file has invalid format.

**Comment by chathudan** [comment]
I did not see any json file here http://direct.mapswithme.com/direct/latest/ 

What is the valid json file should I add ? Could you please give me an example ?

**Comment by deathbaba** [comment]
"[\"http://your.server/\"]"

**Comment by chathudan** [comment]
This is what I add for DEFAULT_URLS_JSON  "https://MY_SERVER/maps/" 
and I downloaded  maps of  version **151103**, all files are located in https://MY_SERVER/maps/151103, where should I add json file and what's the name of it ?

**Comment by deathbaba** [comment]
It is what should be added to DEFAULT_URLS_JSON instead. It should be a valid JSON format, not just a string with a server url.

**Comment by chathudan** [comment]
thank you it worked

**Comment by fukemy** [comment]
@chathudan hello. Can you provide type of DEFAULT_URLS_JSON? I still got error
