### ISSUE TITLE
Remove the "offline" label please

### ISSUE THREAD

**Issue by thany** [mapsme/omim#7591]
The USP that maps.me is an offline mapping tool may as well be removed. It's no longer offline. You (devs) have been adding so much online-only commercial bullshit, that you can't really call it offline anymore while keeping a straight face.

Or, have some balls and remove those features that noone asked for and just charge a few euros for the app. I paid for MapsWithMe Pro, and at the time I was happy to do so. Now I regret it deeply.

If you call your app offline, make it truly and fully offline.

**Comment by thany** [comment]
Or offer extra/online features in the form of plugins. Traffic density, Uber, Booking.com, Ratings, etc. These should all be plugins if you (devs) need them available to us (users). Then, the main app can be called "offline" without it being brushed off as mere fallacy.

**Comment by R3gi** [comment]
>(…) You (devs) have been adding so much online-only commercial bullshit (…)

Sadly, I have to agree.
> Or offer extra/online features in the form of plugins.

+1

**Comment by thany** [comment]
They're not gonna do it, of course. Bunch of pillocks think they're better than us, it seems. They refuse to fix severe performance/usability bugs, and at the same time they keep pushing updates with seemingly no actually useful fixes in them. Only more and more bollocks features.

**Comment by richlv** [comment]
@thany, your comments here and on other issues seem to be very demanding and rude. while nobody can force you not to act like a dick, consider that it makes others less likely to help you ;)

back to the original issue, the app seems to be perfectly usable offline for map browsing, searching and routing. i don't think adding the online features somehow makes those features useless and i suggest to close this issue.

**Comment by thany** [comment]
@richlv, The MAPS.me team nowhere and in very few other issues seem to be very obstinate. While nobody can force them to fix a real issue and act like they care, consider that it makes me less likely to remain friendly to them ;)

back to the original issue, the app seems to be very demanding in wanting internet access. It core value is offline maps, which definitely works, but the bullshit features that have been built-in to keep the app free (which I bloody paid for back when it wasn't) demand internet access to do anything remotely useful. I think adding online-only makes this app no longer a "offline" app and I suggest to keep this issue open until it is resolved.

**Comment by thany** [comment]
Figures.
