### ISSUE TITLE
Opening hours: wrong result with additional rule

### ISSUE THREAD

**Issue by SelfishSeahorse** [mapsme/omim#7718]
Yet another opening hours bug: opening hours that include an [additional rule separator](http://wiki.openstreetmap.org/wiki/Key:opening_hours/specification) (`,`) are not correctly displayed. For example, `opening hours = Mo-Fr 09:00-12:00, 14:00-18:00` is wrongly displayed as Mon-Fri 09:00-18:00.

**Comment by rbovard** [comment]
Same as #5119

**Comment by SelfishSeahorse** [comment]
Oh, I'm sorry! I didn't remember that I even commented on your bug report. 😳
