### ISSUE TITLE
Supposed high energy consumption.

### ISSUE THREAD

**Issue by lcharles123** [mapsme/omim#780]
This is the screen which is listed as a high energy consumer: https://i.imgur.com/8vOc5e5.png
I did not open the app and location services are disabled from fully charged, and it is listed as a consumer of much energy.
It says it is using GPS all the time, or at least trying to use: https://i.imgur.com/vCVkjBX.png
Despite this there was no clue of extra energy worn the charge life has not changed.
So apparently there is no critical problem, but users who see it will think this app uses much battery and will not like it.
Android 4.4.2
Blu studio c mini

**Comment by deathbaba** [comment]
Thanks, we are already looking for this GPS-related bug for several months. Can you please try to disable "Use Google Play Services" in MAPS.ME settings and try to reproduce the bug?

**Comment by lcharles123** [comment]
The bug does not appear in the latest version, good work!

**Comment by ReyhanJB** [comment]
Can you provide the commit that fixes this problem?
