### ISSUE TITLE
iPhone X Layout Issues

### ISSUE THREAD

**Issue by thomersch** [mapsme/omim#7808]
On iPhone X (iOS 11.2, but also before) there are a few layout issues, caused by the new safe area, which defines where active elements should be located.

**Examples**

View doesn't use the full height: 
![img_1e1f49236554-1](https://user-images.githubusercontent.com/948605/33945886-863a0e38-e020-11e7-8621-a874c9612cad.jpeg)

Buttons are too close to the home indicator, making them difficult to hit:
![img_7d378fd657b5-1](https://user-images.githubusercontent.com/948605/33945921-9f413d84-e020-11e7-931d-ef984acfefe2.jpeg)

After selecting a search result, both toolbars overlap
![img_5567adce930b-1](https://user-images.githubusercontent.com/948605/33945951-b8b84870-e020-11e7-8fb6-62dafc053e6b.jpeg)

Top bar also overlaps and is partially eaten by the notch
![img_c5f055b8940f-1](https://user-images.githubusercontent.com/948605/33948524-5c2d5670-e027-11e7-96c5-d00ed144e16f.jpeg)

Would be great if you could have a look on those things, thanks!

**Comment by ForkWithMe** [comment]
This is the official answer from devs to App Store reviews, I'll leave it here:

> Thanks for your feedback. We plan to adjust interface for iPhone X in the beginning of the next year as it requires time and we have a small team with limited resources. Sorry for the inconveniences and thanks for your understanding.
