### ISSUE TITLE
german localization tourism-information-office (Reisebüro) wrong

### ISSUE THREAD

**Issue by FountainMapper** [mapsme/omim#7844]
The german text for "information=office" is broken. The current word is "Reisebüro", which means travel agency (which is different). 
Correct would be "Fremdenverkehrsamt" or "Touristeninformationsbüro" or "Touristeninformation". I prefer the more formal "Fremdenverkehrsamt".

Example node:
https://www.openstreetmap.org/node/2983237403

Version: 7.6.5-Google

**Comment by mpimenov** [comment]
Fixed, see #7855.
Is the other usage of "Reisebüro" correct? Here we use "Reisebüro" or "Touren" as synonyms for "shop-travel_agency":
https://github.com/mapsme/omim/blob/master/data/categories.txt#L6210

**Comment by FountainMapper** [comment]
#7855 Confirmed.
I guess the synonyms are used:
-to add a POI (type "Touren" and get the "Reisebüro" recommended as type of the POI)
-to use the search function (search for "Touren" and get as result the travel agencies (Reisebüro) nearby)

In these cases "Touren" is a good synonym. Are synonyms used somewere else?
It would be a bad idea to display the word "Touren" in the map. It would be like label a bakery with "Bread".

**Comment by mpimenov** [comment]
You are right about the usage. Another place is what we show in the UI when you click on a POI with that type, but the '^' sign in the line I mentioned means that we explicitly want to show "Reisebüro" and not "Touren".
