### ISSUE TITLE
Routing ignores access restrictions - second ticket

### ISSUE THREAD

**Issue by brunetton** [mapsme/omim#7869]
This is a duplicate of #5127, but I was not able to re-open the original bug.
The problem seems to be back again (7.6.4-google - 171020):

Routing ignores access restrictions (motor_vehicle=no).

For example, let's consider [this way](https://www.openstreetmap.org/way/421307164) with tags:
highway=unclassified
motor_vehicle=no
name=Route d'Hecq

It's easy to find a trip that takes this road:
![2017-12-13 00 56 05](https://user-images.githubusercontent.com/86322/33914880-9a77813a-dfa0-11e7-8c5c-2510429cd8dc.png)

The correct path should have avoid this unauthorized road.

**Comment by tatiana-kondakova** [comment]
Hello! Can you update the map to latest (171208) version? You need both new application and new maps to make it work. 
<img width="914" alt="screen shot 2017-12-21 at 15 33 08" src="https://user-images.githubusercontent.com/9213190/34256073-97a32732-e664-11e7-965a-f058694474ce.png">

**Comment by brunetton** [comment]
Thanks. Indeed, with v 171208 it works as excepted :+1:
