### ISSUE TITLE
Maps.me website help points to rejected OSM proposal

### ISSUE THREAD

**Issue by pataquets** [mapsme/omim#7877]
Reading the website help (in Spanish) on new metro routing, I've followed a link to OSM wiki page:
https://wiki.openstreetmap.org/wiki/Proposed_features/Metro_Mapping

But the proposal appears as rejected.
Is this okay?

**Comment by Zverik** [comment]
Yes. It's not a proposal per se, more like a tutorial. In a few weeks I'll turn it into a regular wiki page.

**Comment by pataquets** [comment]
For the record: now the [docs](https://support.maps.me/hc/en-us/articles/115004415773) refer to a more appropriate [guidelines wiki page](https://wiki.openstreetmap.org/wiki/Metro_Mapping).
I couldn't find it in the Spanish docs, though.
