### ISSUE TITLE
I can't clone omim

### ISSUE THREAD

**Issue by borneq** [mapsme/omim#7955]
I try cloning omim.git
first: counts large amount of data
next: is error:

D:\github>git clone https://github.com/mapsme/omim.git
Cloning into 'omim'...
remote: Counting objects: 387786, done.
remote: Compressing objects: 100% (2/2), done.
effrror: RPC failed; curl 56 OpenSSL SSL_read: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac, errno 0
atal: The remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

**Comment by Zverik** [comment]
We are sorry, but there is nothing we can do to fix that: the issue is between you and github. The repository is indeed very big, cloning it can take an hour, and any kind of errors can happen in that time. I've personally cloned it a couple times in the past week, and I had no issues.
