### ISSUE TITLE
Use moderator comment for additional detail on a new feature or update.

### ISSUE THREAD

**Issue by drkludge** [mapsme/omim#7975]
I just updated to 8.0.3 on Android. I used the moderator comment for several osm updates. I was disappointed that the moderator comment was not added to the osm change set comment. That would be a nice enhancement to editing.

**Comment by burivuh** [comment]
@Zverik, please look at this

**Comment by Zverik** [comment]
Thanks for editing with Maps.me. We do not add moderator comments to changesets, because they are properties of objects, not the general editing session. We post them to OpenStreetMap as notes, and you can see them on the OSM website by enabling the notes layer.
