### ISSUE TITLE
Bookmark Sets freezes

### ISSUE THREAD

**Issue by thany** [mapsme/omim#8030]
When I go into bookmark sets using the button on the main screen, the app freezes for a good 5-7 seconds. I even get the "not responding" dialog asking me to close the app, or to wait, or to "report" it.

This app isn't exactly easy on the battery, is it? 😌
I mean, considering some of the other performance issues that have gone unaddressed for several months, if not over a year. Well, here's one more for ya.

I'm on Android 7.1.2, Galaxy S7. The app is up-to-date, and so are the maps.

**Comment by rrrafalsz** [comment]
started having this issue in the latest release (8.0.7) on android 5.1, huawei lua-l21

**Comment by rokuz** [comment]
How many kml/kmz files do you have? Could you please send it to bugs@maps.me with comment that you have freezes on such bookmarks set. Thank you.

**Comment by thany** [comment]
I got 16 sets, 5 of them contain around or slightly above one hundred bookmarks. But only one is active/visible.

I'll send that e-mail, but I think It's best to keep communication in this issue, for future reference.

**Comment by rokuz** [comment]
Thanks, we will research your problem.

> also, when i open the app, the bookmarks are not showing.
The bookmarks are not shown at all, or they appear several seconds later?

**Comment by rrrafalsz** [comment]
> The bookmarks are not shown at all, or they appear several seconds later?
i remember encountering several scenarios:

- the bookmarks would never show and the app would eventually freeze and force quit
- the bookmarks would show after a while and the app would be very slow
- the bookmarks would not show, and when i tried to open the bookmark list, it would freeze

since then i've downgraded to a stable release so i can't test again.

**Comment by rokuz** [comment]
@rrrafalsz by the way how many bookmarks do you have?

**Comment by rrrafalsz** [comment]
@rokuz 
i have:

- 22 sets
- about 50-300 bookmarks in each
- one particular set of 23000 bookmarks (turned off)

**Comment by rokuz** [comment]
@rrrafalsz Unfortunately visibility (turn on/off) flag is a part of KML format and stored inside KML, so we have to read whole KML-file to determine that fact (including one with  23000 bookmarks). We will try to figure this problem out in one of future releases. Thanks.

**Comment by thany** [comment]
You could make the visibility *not* part of the KML and store the flag locally, as it were.

**Comment by rokuz** [comment]
@thany Your problem is different. It will be fixed in the version 8.1 coming soon.

**Comment by thany** [comment]
Technically it's the issue that @rrrafalsz has that's different, because I started this ticket ;)

**Comment by rokuz** [comment]
@thany The version 8.1 is in store. Please check it out

**Comment by rrrafalsz** [comment]
version 8.1 has solved my issue. if @thany confirms, i believe this ticket can be closed.

**Comment by thany** [comment]
I think we can close this issue. I wasn't seeing the problem anymore, so I suppose it's been solved from your end, and on my phone somehow simultaneously or something ;)
