### ISSUE TITLE
Allow search in a wider radius

### ISSUE THREAD

**Issue by utack** [mapsme/omim#804]
The search seems to be cut off based on the current view.
This can mean results are not found, please include a button to widen the search radius or automatically continue searching in all maps in the background.

**Comment by deathbaba** [comment]
It was an “improvement” required by Google review team to pass “ready to feature on Google Play” criteria.
We’re working on a new search engine and probably change it. Please check search quality again in 1-2 months and ping our team :)

**Comment by utack** [comment]
Any way to force it higher (even if it has to be messing with config files in /data/data)?
Or maybe it is simple to revert, for self-builders?
Thanks

**Comment by deathbaba** [comment]
Can’t tell you exact code location or that commit. @vng @mpimenov can you help please?

**Comment by utack** [comment]
Here?
https://github.com/mapsme/omim/blob/fd3eb0e4f19e9db963ed8160d3beef804683295a/iphone/Maps/maps.me%20WatchKit%20Extension/FrameworkUtils/MWMFrameworkUtils.mm#L109

**Comment by deathbaba** [comment]
I suppose yes, for iOS only.

**Comment by utack** [comment]
Any update on this, can someone remember how to allow a bigger radius?

**Comment by deathbaba** [comment]
@vng @mpimenov ping?

**Comment by ighsiwwx** [comment]
It is concerning that Google is influencing apps in this way.

**Comment by mpimenov** [comment]
I'm not sure this is as simple as tweaking one constant. The best option for now is to wait until the reworked search is released.
If the wider radius is indispensable for you, consider building the app from the new-search branch. It should work out of the box but you'll have to download the maps anew.

**Comment by utack** [comment]
Absolutely not in a hurry, and glad to hear it is a "long term goal"

**Comment by utack** [comment]
It works flawlessly in the latest beta.
Guess this can be closed now
