### ISSUE TITLE
wrong POI location

### ISSUE THREAD

**Issue by cocoonbud** [mapsme/omim#805]
![ty4oh5 qnqj 6mk o g3 ow](https://cloud.githubusercontent.com/assets/14837546/11522061/fc4d043a-98ed-11e5-8472-102cffa62dc1.jpg)

Hi, 
By using the method of the picture above, I tried to add  self-defined POI  but turned out to be wrong positions  presenting on the map. The longitude and latitude  （model.lat and model.lng）of the position presented on  the map is not the same as I defined.

**Comment by deathbaba** [comment]
It’s because coordinates in this API should use Mercator projection, not just lat/lon in degrees. Please check indexer/mercator.hpp.
