### ISSUE TITLE
omin.pro missing

### ISSUE THREAD

**Issue by RiemanZeta** [mapsme/omim#8066]
Idk If I'm being stupid, but I can't find the omin.pro file. I've initalized the repo and everything. I've even built the android apk successfully. I've searched my entire computer and no omin.pro. file exists. What am I doing wrong?

The wiki says "Start Qt Creator, open omim.pro" to work in Qt Creator.

**Comment by Zverik** [comment]
We've moved from `qmake` to `cmake`: now you open `CMakeList.txt`.

**Comment by amenk** [comment]
I stumbled at the same problem ... we should update the readme. I can make a pull request once I figured out how to setup the project :-)
