### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by RiemanZeta** [mapsme/omim#8075]
Trying to build webRelease with gradle. I was able to generate an apk before, but now I get this error with gradle. 

/Users/USER/Desktop/map_app/omim/map/cloud.cpp:36:32: error: use of undeclared identifier 'CLOUD_URL'
std::string const kServerUrl = CLOUD_URL;

Any ideas?

**Comment by Zverik** [comment]
Please run the `configure.sh` script from the repo root. This happens sometimes, when we add new variables to the `private.hpp` file.

**Comment by RiemanZeta** [comment]
I did that and I still get the same error. I even made a fresh pull from the repo.

**Comment by greshilov** [comment]
Looks like we fix it. Please, try again :)

By the way, you can add ```-Parm``` or ```-Px86``` for gradle wrapper to build app on defined abi. This param will speed up this process in two times!
Full command: ```./gradlew assembleWebRelease -Parm```

**Comment by RiemanZeta** [comment]
Thanks for the fix and useful info!
