### ISSUE TITLE
Modifying Android app and base C++ code from Android Studio?

### ISSUE THREAD

**Issue by gkitarp** [mapsme/omim#8121]
Hi guys, Thanks a lot for this project and your support in the open source community! Appreciate your work!
I would like to clone the current repo and explore, edit and build the Android app's code base as per the documentation here [https://github.com/mapsme/omim/wiki/%5BAndroid%5D-How-to-build-project](url)

1. Will these instructions work on Mac OSX 10.11.6 using latest Android Studio on the latest Android SDK? 

2. If I have to change the C++ base code along with Android Java code, do I need to install Qt 5.5 (I think higher versions may not be compatible?), Clang and Boost according to this:
https://github.com/mapsme/omim/blob/master/docs/CONTRIBUTING.md

3. What is the build process when changing the C++ code and Android code? Do I need to separately first compile the C++ code each time I change it and then build the Android code after I change the Android code? I understand I can change the C++ code within Android Studio.

4. I'm not going to build or edit the iOS code, so do I still need to install XCode also?

**Comment by mpimenov** [comment]
1. They should.
2. Yes for clang and boost, probably no for Qt. In case you'll need to install it, Qt 5.7 is definitely ok.
3. No, Gradle must handle changes both in the core and in the Android code. Running ```./gradlew``` should recompile everything that you need. However, if you intend to change the core code without touching the Android code, you might want to recompile the tests. To do this, the best option is CMake (though you can also run some of the tests from the XCode project).
4. No, XCode is not needed in this case.
