### ISSUE TITLE
[feature request] Use server encryption 

### ISSUE THREAD

**Issue by twzkxkan** [mapsme/omim#817]
Using HTTPS for map downloads makes it harder to block or modify traffic as well as increasing user privacy.

**Comment by deathbaba** [comment]
HTTPS also increases servers loading and is not as reliable in roaming and open wifi networks. And it is can not be cached by transparent proxies.

**Comment by twzkxkan** [comment]
Thank you for taking the time to respond, those reasons are insightful. Shall I close this issue?

**Comment by deathbaba** [comment]
You can safely close it now, we always keep HTTPS in mind for the future.
