### ISSUE TITLE
Add bike commuting

### ISSUE THREAD

**Issue by pizzamaker** [mapsme/omim#820]
Right now you can only choose between car and walking. Add bikes please!

**Comment by deathbaba** [comment]
It’s in our plans for the future. And we need to add a relief support first, to get altitude of any point on a map.

**Comment by utack** [comment]
Would be a great addition.
OSRM should already support it?

**Comment by deathbaba** [comment]
I don’t think we’ll reuse OSRM. Bike routes size will be quite significant.

**Comment by rokuz** [comment]
Implemented
