### ISSUE TITLE
addr:interpolation is not supported

### ISSUE THREAD

**Issue by exacj** [mapsme/omim#8228]
If you search for "522 runnymede road" on openstreetmap.org you will get a result.

If you search for the same-thing on MAPS.ME (with the area downloaded of-course) you will not find the place.

But if you search for "512 runnymede road" you get a result on both OSM and MAPS.ME

It seems like MAPS.ME does not support addr:interpolation

**Comment by burivuh** [comment]
Yes, this is exactly the problem. Unfortunately we have no resources to do it this year.
