### ISSUE TITLE
[feature request] Whether  there is an independent POI database in the MWM file?

### ISSUE THREAD

**Issue by simon247** [mapsme/omim#825]
Whether  there is an independent POI database in the MWM file?

**Comment by deathbaba** [comment]
Can you please clarify your question? MWM file contains all features from OpenStreetMap in a compressed format.

**Comment by simon247** [comment]
When I search 'food' on Mapsme, where the search result list come from?

**Comment by deathbaba** [comment]
From OpenStreetMap data, which is compressed and saved in our MWM format.

**Comment by simon247** [comment]
OK thanks,  How can I open the MWM file,  Or what tool should I use to exported the data.  We want to add some special POI data on it, but maybe there is some duplicated data. How could we do it. Many Thanks.

**Comment by deathbaba** [comment]
You can export all data directly from http://www.openstreetmap.org
