### ISSUE TITLE
OpenStreetMap import will break if links aren't updated before May 7

### ISSUE THREAD

**Issue by grischard** [mapsme/omim#8289]
http://planet.openstreetmap.org is available over https, and will [start redirecting to https on 2018-05-07](https://github.com/openstreetmap/operations/issues/200).

Your project seems to be using curl, which [will not follow redirects by default](https://davidwalsh.name/curl-follow-redirects).

Would it please be possible to update all files from `http://planet.openstreetmap.org` to `httpS://planet.openstreetmap.org` before then?

Ideally, would it be possible to make all requests to openstreetmap.org over https?

**Comment by Zverik** [comment]
Hi Guillaume, thanks for the heads-up. We are using `osmupdate`, and I have no idea which scheme it uses. I guess I'll fix any issues when they arise.

**Comment by grischard** [comment]
https://github.com/mapsme/omim/blob/8906f0b7c9a215cf52ac8f63ee6c8515fd831776/tools/unix/generate_planet.sh uses curl on planet.openstreetmap.org

**Comment by Zverik** [comment]
Fixing that in #8320.
