### ISSUE TITLE
Support for conditional turn restriction

### ISSUE THREAD

**Issue by Xyxy-** [mapsme/omim#8308]
While navigating in a car with Maps.me, I've stumbled upon a conditional turn restriction that was not enforced. I even actually took that in front of a nice policeman : you can imagine the mess :D

Apparently, this is only due to a few flags that should be set up when using OSRM - because OSRM does support conditional turn restriction. It shouldn't be so complicated, as far as I understand.

See more details here
https://github.com/Project-OSRM/osrm-backend/issues/4366#issuecomment-372965090

However, I do not understand the details of the implementation. In particular, I'm curious to know if the condition is enforced at departure time or at the time you're supposed to reach that turn.

danpat has a few words about it, but I'm not sure if it still applies.
https://github.com/Project-OSRM/osrm-backend/issues/3414

I'm sure you can figure it out though, now that you reached that level of expertise with OSRM :)

**Comment by bykoianko** [comment]
Dear Xyxy.

Thanks you for your recommendation, but we stoped using OSRM one and half year ago when we implemented traffic jam. We had to do it to be able to change the weight of edges dynamically.

For the time being we don't support any conditional restriction, but probably we'll implement time conditional restriction (including turn conditional) in the future.

Regards,
Vladimir
