### ISSUE TITLE
Render landuse=village_green as green

### ISSUE THREAD

**Issue by utack** [mapsme/omim#844]
Issue is in title, "landuse=village_green" is currently grey on the map, should probably the same color as landuse=grass

**Comment by deathbaba** [comment]
Thanks, we’ll take a look.

**Comment by deathbaba** [comment]
Can you please check the master branch? They should already be green there. We’re planning release in about a week.

**Comment by utack** [comment]
Where does one get a daily build?

**Comment by Zverik** [comment]
[Maps are here](http://direct.mapswithme.com/regular/daily/), [my daily builds are here](http://osmz.ru/mwm/) (temporarily stalled, because of memory issues).

**Comment by utack** [comment]
It is correctly rendered as green in the latest nightly build
