### ISSUE TITLE
Current location is unknown

### ISSUE THREAD

**Issue by ston3o** [mapsme/omim#8443]
I can't use location.

Here the message : `Current location is unknown. Mabye your are in a building or in a tunnel.`

Android Version : 4.4.4
Maps.me Version : android-web-release-8.1.3-180330.apk
Logcat debug : 
```
D/dalvikvm( 2576): WAIT_FOR_CONCURRENT_GC blocked 8ms                                           
D/0-Settings/BW( 2004): ReadCodeTask:IOException happen when get NotifyCode                    
W/0-System.err( 2004): java.io.IOException: read failed: EINVAL (Invalid argument)             
D/dalvikvm( 2576): GC_CONCURRENT freed 511K, 79% free 3349K/15472K, paused 1ms+2ms, total 19ms 
D/dalvikvm( 2576): WAIT_FOR_CONCURRENT_GC blocked 9ms                                          
W/0-System.err( 2004):  at libcore.io.IoBridge.read(IoBridge.java:435)                           
W/0-System.err( 2004):  at java.io.FileInputStream.read(FileInputStream.java:179)              
W/0-System.err( 2004):  at java.io.InputStreamReader.read(InputStreamReader.java:233)           
W/0-System.err( 2004):  at java.io.BufferedReader.fillBuf(BufferedReader.java:145)             
W/0-System.err( 2004):  at java.io.BufferedReader.readLine(BufferedReader.java:397)            
W/0-System.err( 2004):  at com.tinno.batterywarning.ReadCodeTask.getNotifyCode(ReadCodeTask.java:187)
W/0-System.err( 2004):  at com.tinno.batterywarning.ReadCodeTask.sendWarningMessage(ReadCodeTask.java:58)
W/0-System.err( 2004):  at com.tinno.batterywarning.ReadCodeTask.run(ReadCodeTask.java:44)     
W/0-System.err( 2004):  at java.util.Timer$TimerImpl.run(Timer.java:284)                        
W/0-System.err( 2004): Caused by: libcore.io.ErrnoException: read failed: EINVAL (Invalid argument)
W/0-System.err( 2004):  at libcore.io.Posix.readBytes(Native Method)                             
W/0-System.err( 2004):  at libcore.io.Posix.read(Posix.java:128)                                  
W/0-System.err( 2004):  at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
W/0-System.err( 2004):  at libcore.io.IoBridge.read(IoBridge.java:425)
W/0-System.err( 2004):  ... 8 more
```

**Comment by alexzatsepin** [comment]
Hi @ston3o,

Unfortunately, the stack trace that you attached is not related to your location issue. Could you please enable logging in the app settings and put it in comments. So I'll be able to figure out of the main reason of your problem. How to get logs output you can read here - https://github.com/mapsme/omim/wiki/%5BAndroid%5D-How-to-get-log-output.

**Comment by ston3o** [comment]
Hello @alexzatsepin,

Here my log files from `/storage/emulated/legacy/Android/data/com.mapswithme.maps.pro/files` : 
- [logcat.log](http://termbin.com/lvxa)
- [location.log](http://termbin.com/xyih)
- [misc.log](http://termbin.com/p9wy)
- [core.log](http://termbin.com/n6kl)

Thanks for your help !

**Comment by ston3o** [comment]
I tested in a building and on the street. Same results.
I don't have google play on my phone.
Yes I have an 4G internet connection.
I tried Waze application and the GPS works fine.

**Comment by ston3o** [comment]
Ah it's worked during a small time, but now my phone has no battery.
I'll let you know when my phone is charged.

**Comment by ston3o** [comment]
In fact, it's works, I just need to move to enable location. Waze doesn't need to move to enable it. But It doesn't matter, I prefer maps.me ;)

Thanks for your help @alexzatsepin ;)
