### ISSUE TITLE
WorldCoasts.geom

### ISSUE THREAD

**Issue by g3ngar** [mapsme/omim#8564]
Hello world. 

I do not have enough processing power to generate by myself the `WorldCoasts.geom` file as instructed in the [docs](https://github.com/mapsme/omim/blob/master/docs/MAPS.md#the-planet). Is there any place where I can download this file (something like what [http://direct.mapswithme.com/direct/latest/](http://direct.mapswithme.com/direct/latest/) is for downloading the `.mwm` files)?

> **Context**: I'm building a map for a single country, so I downloaded the country OSM data from [geofabrik](https://www.geofabrik.de/) and successfully generated the `.mwm` file following the [docs](https://github.com/mapsme/omim/blob/master/docs/MAPS.md#a-single-region) instructions. However, when I zoom in the map,the water regions outside the country boundaries aren't blue. I'm guessing it's because  as specified in the [docs](https://github.com/mapsme/omim/blob/master/docs/MAPS.md#the-planet), the generated map has no coastlines since I did not used the `COASTS=WorldCoasts.geom` parameter while generating.

**Comment by Zverik** [comment]
There is no fixed place to download `WorldCoasts.*` files, but you can [take these](https://transfer.sh/O2EWu/coasts-180417.zip) (you need both files).

**Comment by g3ngar** [comment]
Thanks a lot!

**Comment by g3ngar** [comment]
It did the trick, thanks a lot!

**Comment by Zverik** [comment]
Great!
