### ISSUE TITLE
Logo proposal for "Maps.me"

### ISSUE THREAD

**Issue by moenawar85** [mapsme/omim#8606]
Hello Sir... I would like to contribute with your project by created a new logo. I'm waiting for your response and answer, If you like it I will send the original file that editable in CDR / PDF and PNG also. If you have any suggestion with color or something else I will fix it.
![map me logo final](https://user-images.githubusercontent.com/36834147/39312353-93acb858-4999-11e8-9880-b535cae4419b.png)
![map me logo icon app](https://user-images.githubusercontent.com/36834147/39312393-acc14700-4999-11e8-9ae9-7c7fd34d018c.png)

Best regards, Moenawar.
Thank you indeed.

Discord: @moenawar#1364
Twitter : @moen85
Steemit: http//www.steemit.com/@moenawar

**Comment by burivuh** [comment]
Hi!

We do not plan to change our logo

Thank you!

**Comment by thany** [comment]
@moenawar85 Maps.me is a commercial company. Of course they won't just change their logo. Sorry to say, but getting Maps.me to do *anything* is nearly impossible. Just look at the ridiculous number of issues that have piled up. The neglect is really quite amazing.
