### ISSUE TITLE
iOS App Not Compiling

### ISSUE THREAD

**Issue by abellao** [mapsme/omim#866]
I'm receiving a `Command /bin/sh failed with exit code 1` error while compiling.

Steps to reproduce:
1. Download master branch
2. Go to `iphone/Maps/` directory and open `Maps.xcodeproj`
3. Run on Simulator or Device
4. Receive error

I'm using Xcode 7.1.1 on OS X 10.11.1

Is this the correct way to compile the app for iOS?

**Comment by deathbaba** [comment]
Have you installed QT as mentioned in instructions? What is the exact error in the log?

**Comment by abellao** [comment]
Thanks, I missed the Qt 5 installation.

**Comment by iStig** [comment]
hello @abellao @deathbaba 
I have install qt5 , but it still compiling failed.  i use xcode 7.2,  osx 10.11
![image](https://cloud.githubusercontent.com/assets/2696927/12739058/dda306ea-c9a0-11e5-9066-5fcfe542d343.png)

steps:
1.git clone --recursive
2.Run configure.sh
3.run brew install qt5.
4.Download Qt Creator with Qt 5.
5.Open omim/iphone/Maps/Maps.xcodeproj in XCode.
6.Open "Product → Scheme → Edit Scheme", then "Info" and change build configuration to Simulator.
7.omim/tools/autobuild/detect_qmake.sh     add the path into path array
 details:
![image](https://cloud.githubusercontent.com/assets/2696927/12739169/fee13510-c9a1-11e5-9446-acf407516d78.png)
8.Run the project (Product → Run).

i do not know clear with the error ,pls help ,thanks a lot

**Comment by deathbaba** [comment]
I'm not sure, but can you try to use a different folder for the project, without Chinese chars in path?

**Comment by iStig** [comment]
thank you, i will try again right now

**Comment by iStig** [comment]
@deathbaba  thanks for help . now it can be compiling .  i will be attention about it next time.
