### ISSUE TITLE
Integrate omin in my own iOS app

### ISSUE THREAD

**Issue by cadizjavier** [mapsme/omim#867]
This is a fantastic library, since the open source release i want to embed this maps in my own iOS app.
I compile it just fine but im struggling to identify the sections that i need to extract to use only an small subset of features.
Im struggling finding any tutorial or documentation that clears the path so im asking here for advices in doing such task.
Any suggestions in what should i do ?

**Comment by deathbaba** [comment]
It is not an easy task, as we never “cut” parts of MAPS.ME app. If you successfully do it, you can create this documentation :)

In general, it is not an easy task. You should probably start with C++ core libraries and link them to your iOS app in the same way as we linked them in MAPS.ME.

**Comment by rahul606** [comment]
Hi @cadizjavier did you find the solution ? As I am also trying to do the same.

**Comment by cadizjavier** [comment]
@rahul606 Im waiting now for the support for Offline Maps of Mapbox GL. See this issue https://github.com/mapbox/mapbox-gl-native/issues/584 . They say that this feature will be released in March.

**Comment by rahul606** [comment]
@cadizjavier thx for the quick reply. I will follow the issue of mapbox

**Comment by prebenl** [comment]
If you need a library that supports integration as a module and offline mode right now, you can have a look at Skobbler maps:
http://developer.skobbler.com/getting-started/ios

I'm also following the development of offline mode in Mapbox. My impression is however that both Skobbler and Mapbox are inferior in the way they render the maps, compared to Maps.me. But for now I don't have the time/budget to make a modularized version. Hopefully someone will get together and have a go at it in the future.

**Comment by deathbaba** [comment]
You can also alternatively invest relatively small efforts into extending MAPS.ME API to solve your tasks.
Now it can show point (or points) on a map and return user back into a calling application, but it can be extended significantly. Of course, user needs to install MAPS.ME app to use the API, but it can benefit everyone.
