### ISSUE TITLE
Rendering problems on Android 8 / Galaxy S9

### ISSUE THREAD

**Issue by thany** [mapsme/omim#8689]
I'm not sure if this is due to Android 8 (Oreo) or to the odd screen resolution of the Galaxy S9, but the app is showing some weird rendering artefacts. It also doesn't use the whole screen. It seems to insist on a 16:9 or 9:16 ratio, so a ~1cm black bar remains on my screen.

Possibly related, going from screen to screen may leave remnants of previous screens. Rendering artefacts, or bugs, or wahtever you might call them. This did not happen on my previous phone, being a Galaxy S7 with Android 7.

*) Both phones run LineageOS, but as said, it *can* run absolutely artefact-free on LOS, so please try not to put blame on custom ROM trickery.

**Comment by Alexuser1** [comment]
Hello @thany,

The issue can't be reproduced on official firmware by Samsung. Here are the screenshots. We don't support unofficial ROM's. We'll close the issue.

![img1](https://user-images.githubusercontent.com/18442270/41975003-338c73aa-7a22-11e8-9b50-328efba3310c.jpg)

**Comment by thany** [comment]
LineageOS is not unofficial.

And why do you only support Samsung firmwares? Are you getting a bag of moneys from them?
