### ISSUE TITLE
Some KML file tracks are not shown on map after import on Android

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#872]
I have noticed that some KML files that have been created by a web based route planner such as cycle.travel do not appear on the map after a successful import (import success toast message appears OK). 
KML file innards shown below. The track/route appears OK in online checkers such as GPSVisualizer and other Android apps such as GPX Viewer.

<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.0">
  <Document>
    <Placemark>
      <LineString>
        <coordinates>
-2.24511,51.86483,0
-2.24355,51.86399,0
-2.24587,51.86210,0
-2.24776,51.85977,0
-2.24763,51.85968,0
-2.24856,51.85858,0
-2.24866,51.85796,0
-2.24956,51.85693,0
-2.24853,51.85578,0
-2.25076,51.85213,0
-2.25452,51.84805,0
-2.25821,51.84974,0
-2.26038,51.84766,0
-2.26248,51.84669,0
-2.26348,51.84572,0
-2.26381,51.84588,0
-2.26415,51.84601,0
-2.26429,51.84607,0
-2.26991,51.84016,0
-2.27199,51.83934,0
-2.27478,51.83931,0
-2.27712,51.83882,0
-2.28375,51.83396,0
-2.28519,51.83375,0
-2.28946,51.83481,0
-2.29148,51.83309,0
-2.29434,51.83203,0
-2.29641,51.83179,0
-2.29978,51.83226,0
-2.30559,51.83059,0
-2.30471,51.82956,0
-2.30385,51.82697,0
-2.30522,51.82372,0
-2.30548,51.82237,0
-2.30498,51.82130,0
-2.31122,51.81931,0
-2.31328,51.81910,0
-2.31947,51.81738,0
-2.32091,51.81731,0
-2.32281,51.81762,0
-2.32613,51.81716,0
-2.32855,51.81514,0
-2.32941,51.81098,0
-2.33466,51.80809,0
-2.33727,51.80770,0
-2.33881,51.80800,0
-2.34051,51.80877,0
-2.34290,51.80877,0
-2.34324,51.80504,0
-2.34399,51.80293,0
-2.34384,51.80161,0
-2.34401,51.79857,0
-2.34450,51.79718,0
-2.34354,51.79691,0
        </coordinates>
      </LineString>
      <Style>
        <LineStyle>
          <color>#ff0000ff</color>
        </LineStyle>
      </Style>
    </Placemark>
  </Document>
</kml>

**Comment by deathbaba** [comment]
This does not look like a valid KML format. Can you please upload original KML file somewhere and share a link with us?

**Comment by stevegdavis** [comment]
Looking the PC screen now it looks as if some of what I cut/paste in to the dialog box is missing, will try Dropbox.

**Comment by stevegdavis** [comment]
Link to KML file:-
https://www.dropbox.com/s/92bhtgri02brbp6/cycle_travel.kml?dl=0

**Comment by deathbaba** [comment]
Your file is in KML2.0 format, but we support KML2.2 only. Please compare it with http://tracks.org.nz/paths/83.kml for example. The main difference is an "id" parameter to reference color style.

**Comment by stevegdavis** [comment]
OK that's fair enough, many thanks I will close this issue now.
