### ISSUE TITLE
Please use the entire screen

### ISSUE THREAD

**Issue by thany** [mapsme/omim#8738]
I have a ~1cm black bar at the bottom of my screen (in portrait) and then the button bar. Can maps.me please use the entire screen, rather than a fixed portion of it? Thanks.

I'm using the latest version from Play on a Galaxy S9. Resolution is 2960x1440, or roughly **19:9** (yep, that's 19:9 not 16:9)

![screenshot_maps me_20180522-124109](https://user-images.githubusercontent.com/152227/40357895-dccfe590-5dbd-11e8-8b05-3432f50fde53.png)

That black bar includes the buttons, so the app can decide to use the absolute entirety of the screen, or just up to the buttons. But not this. Like this we have a strange bar of wasted screen real estate.

There are other apps suffering from the same problem, but most don't. It might just be a simple compatibility thing. Or it might be that apps have gotten persistent on the screen aspect ratios, or it might be that the app was never tested on anything other than one or two devices that both happen to sport the same aspect ratio. Either way, it looks odd, and it produces [some strange artefacts](https://github.com/mapsme/omim/issues/8689) that cannot be captured in a screenshot.

**Comment by Alexuser1** [comment]
Hello @thany,

The issue can't be reproduced on official firmware by Samsung. Here are the screenshots. We don't support unofficial ROM's. We'll close the issue.

![img1](https://user-images.githubusercontent.com/18442270/41975003-338c73aa-7a22-11e8-9b50-328efba3310c.jpg)

**Comment by thany** [comment]
I'm not asking for support. I'm just asking to use the entire screen. Don't close the issue becuse it's happening on a flavour of the OS you don't know about. It's very bad practice to only support a small range of firmwares.

The point is that this may still happen on other firmwares for other "long" phones. 

And really, every ROM is a custom ROM. Almost noone runs AOSP.
On top of that, LineageOS is by far the most popular custom Android flavour, and it is in no way unofficial. It's just unsupported by the OEM. You are in no position to blacklist such people.

Heck, it might be an easy fix.

I *have to* use the LineageOS ROM, simply because the stock ROM is unuasable for me. So I consider it unethical of you, to actively refuse to fix a small problem that so happens to only occur on my device. Shame on you.
