### ISSUE TITLE
Maps road/highway colours

### ISSUE THREAD

**Issue by stevegdavis** [mapsme/omim#894]
I would like to be able to change the colour of some of the minor roads on a map (in the classic style) as some are hard to discern outdoors on a sunny day with glare on the phone screen.
I assume that I would have to build my own maps but I see that the instructions are mainly for building/creating maps under unix and I know you chaps use macs but I want to do it under Windows.
I can see some of the styles in files such as colors_light.mapcss etc.. but any further help would be appreciated, thanks.
I currently build the app under Windows 7 using Android Studio.

**Comment by deathbaba** [comment]
@kshalnev @Zverik can you please help with documentation about styles?

@stevegdavis Can you please share some screenshots with us, where roads are looking bad? Our designers can take a look and tune it up too.

**Comment by Zverik** [comment]
We haven't done this under Windows, but if you want this change only for yourself, you can skip rebuilding the application, and just use python scripts. Alas, we don't have a preview application for Windows.

You need to edit `data/styles/clear/style-clear/colors.mapcss`. These numbers are referred from `data/styles/clear/include/roads.mapcss`, where you can find road classes you'd like to recolor.

After editing the file, run `python tools/kothic/src/libkomwm.py -s data/styles/clear/style-clear/style.mapcss -o data/drules_proto_clear.bin` That would make a drules_proto_clear.bin, which you need to copy to a device, into a `MapsWithMe` folder. Please note it would be loaded only with debug or beta versions of the maps.me app.

If you can build the `apk` file, the modified style will be included there.

**Comment by stevegdavis** [comment]
@deathbaba  - Attached is a screen shot from a UK_England map that shows a secondary road in yellow and 2 unclassified roads (as called in the UK with no road number) in white with grey edges (see Knapp Lane or Slad Lane), these unclassified roads are the types I would like to see coloured. Thanks.
![screenshot_2015-12-08-14-36-39](https://cloud.githubusercontent.com/assets/15140454/11658551/2a9a20e4-9dbb-11e5-875a-95f95d38ce05.png)

**Comment by stevegdavis** [comment]
@Zverik many thanks,  I will have a go at that. I will leave this issue open for a while in case I get stuck and need to ask more questions.

**Comment by stevegdavis** [comment]
@Zverik   - Is the file drules_proto_clear.bin only for the 'new' light map style only as I would like to change the 'old' classic map style (ie. ?oldstyle) ?

**Comment by Zverik** [comment]
The classic style is in the `data/styles/legacy` directory, and compiled to `data/drules_proto.bin`.

**Comment by stevegdavis** [comment]
@Zverik  OK, many thanks I did think it was that, I am having trouble running the python script at the moment I haven't altered any style files I am just trying to generate a bin file but the python interpreter tells me when I run libkomwm.py:-
Import error: No module named google.protobuf.internal 
on line 6 that reads:-
import mapcss.webcolors
Not sure why that is ?.
Sorry I am not familiar with Python at all.

**Comment by Zverik** [comment]
You need to install protobuf library (`pip install protobuf`). For that you might need to install pip application, or you can search for it in your python distribution.

**Comment by stevegdavis** [comment]
@Zverik many thanks for that, it all 'builds' OK and I can now change the styles as desired. I will play around with some other styles and then when I am satisfied I will close this issue.

**Comment by Zverik** [comment]
\o/

**Comment by stevegdavis** [comment]
@deathbaba - I have coloured the 2 minor (unclassified UK) roads see screenshot compared with the 1st one I attached earlier:-
![screenshot_2015-12-14-10-26-44](https://cloud.githubusercontent.com/assets/15140454/11778628/976afa40-a24d-11e5-9be8-5cd8d963a655.png)

**Comment by deathbaba** [comment]
Good! :)
