### ISSUE TITLE
Login with OSM

### ISSUE THREAD

**Issue by nasirkhan** [mapsme/omim#8974]
Login with Open Street Map is not working from the android app. I checked account credential o the OSM website and it worked there.

**Comment by amenk** [comment]
@nasirkhan which version are you using?

**Comment by ForkWithMe** [comment]
Hi, 

The issue (#8991) has been fixed in release 8.3. You can create a build from a release-83 branch, download nightly build or wait a bit for an official update in Google Play and App Store. 

P.S.: if you're a beta tester in Google Play, you can already use the new version.

**Comment by nasirkhan** [comment]
@amenk the version is 8.2.9-Google.

I am not a beta tester right now, but i would love to be one. @ForkWithMe Can you please share the link to become a beta tester?

**Comment by ForkWithMe** [comment]
Version 8.3.3 has been released in Google Play, authorisation in OSM is working with the new version.
