### ISSUE TITLE
Question: which exact QT version to use

### ISSUE THREAD

**Issue by amenk** [mapsme/omim#9043]
I am going to download QT from https://www1.qt.io/offline-installers/
 They have QT 5.6 and 5.9.

The contribution.md implies QT 5.5

Which exact version is currently used in development?

Should I use an archived QT 5.5 version?

I want to avoid downloading the wrong version because the download is expensive in my area and takes long.

**Comment by Zverik** [comment]
Any Qt newer than 5.5 would also work. I use 5.9, for example.
