### ISSUE TITLE
Allow negative IDs sorted the way JOSM saves them (-1, -2...)

### ISSUE THREAD

**Issue by amenk** [mapsme/omim#9096]
I found out that osmconvert.c has code to check whether Ids in the input file are sorted numerically -2 -1 and so on.

JOSM sorts differently by absolute value, negatives first. 

Would you accept a pull request to allow JOSM sorted files?

Is it only about altering the check or would this cause further complications?

See also https://github.com/osmcode/osmium-tool/issues/121

**Comment by Zverik** [comment]
Thanks for the suggestion, Alexander. We in maps.me keep a forked version of osmctools, so we're not affected when anything in the upstream breaks. And since we're using it only to extract and convert parts of the planet, we don't really care of the order of negative ids.

Please try to make said pull request to the main osmctools repository: https://gitlab.com/osm-c-tools/osmctools

**Comment by amenk** [comment]
@Zverik Maps with Me does not seem to be compatible with negative IDs ...

     07-16 14:59:59.956  8311  8548 F libc    : /Volumes/Android/buildbot/src/android/ndk-r15-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::out_of_range: vector" failed

**Comment by amenk** [comment]
@Zverik for a test I downloaded Ethiopia.osm.pbf from geofarbik, built the Ethiopia.mwm with the generator tool and put it on the phone. There should not be negative Ids there. Still the app crashes.  Shall I open a dedicated issue for that?

**Comment by Zverik** [comment]
That is a completely different issue. Depends on where exactly you put the mwm file, and which branch did you check out to build the generator. You should use the one that your maps.me version supports. For example, `release-82` for 8.2.x.

**Comment by amenk** [comment]
Quick fix:

        if(otype<=oo_sequencetype &&
            (otype<oo_sequencetype || id<oo_sequenceid ||
            (oo_ifn>1 && id<=oo_sequenceid))) {
          //oo__error= 92;   // comment out this line, around Line 11192
          WARNv("wrong sequence at %s %"PRIi64,
            ONAME(oo_sequencetype),oo_sequenceid)
          WARNv("next object is %s %"PRIi64,ONAME(otype),id)
          }
        }  // dependencystage>=32
      }  // no diff contents is to be considered

**Comment by amenk** [comment]
Actually negative IDs seem to clash with base/geo_object_id.cpp:15 

     uint64_t const kReservedMask = 0x00FF000000000000;

Which is checked in the process of creating a map - so for now I am resorting to renumber the negative IDs.
