### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by nasirkhan** [mapsme/omim#9121]
Is there any possibility to add an option to login with Google? 
Usually i do not use facebook that much and the OSM login is not functional right now. Even the OSM may be fixed soon, it would be great to have Google login at the settings.

**Comment by Zverik** [comment]
Alas, no. Google has disabled an in-browser login on mobile devices, and any alternative options are blocked by OSM website devs: https://github.com/openstreetmap/openstreetmap-website/pull/1433
