### ISSUE TITLE
Please add direction arrows for oneway roads

### ISSUE THREAD

**Issue by SelfishSeahorse** [mapsme/omim#9389]
It were very helpful if the allowed direction of travel for oneway roads was visible on the map.

See example rendering from openstreetmap-carto:

![screenshot_2018-09-03-21-08-55](https://user-images.githubusercontent.com/14875493/44999556-7700fa80-afbe-11e8-8a92-981ecea60aea.png)

**Comment by burivuh** [comment]
Fixed for 8.4
Thanks!
