### ISSUE TITLE
release compile

### ISSUE THREAD

**Issue by RahmanFard** [mapsme/omim#955]
I have a problem with release compile. 
Last release variant, Android studio, MAC 

make[1]: *** No rule to make target `../3party/Alohalytics/src/cpp/alohalytics.cc', needed by `../out/production/tmp/stats_client/alohalytics.o'.  Stop.
make: *** [sub-stats-make_first] Error 2

Please help me.

**Comment by deathbaba** [comment]
Please clone/update repository with submodules.
