### ISSUE TITLE
Request for more maps update

### ISSUE THREAD

**Issue by Mesgary** [mapsme/omim#959]
In most of the countries which have a good OSM map coverage, updating the map file with each version is a good period, but in countries like IRAN which has a lot of important daily updates, I think updating with each version is not good enough. I think for these countries you have to set update period less than version update. Maybe a weekly update or at least monthly update is needed.

**Comment by Zverik** [comment]
Hi, we have unofficial [daily map builds](http://direct.mapswithme.com/regular/daily/). They are not guaranteed to be working or contain all the features the official maps have, but at least they are build daily. We are working on increasing update frequency of official maps, but it won't happen in the near time.

**Comment by Mesgary** [comment]
I mean you make this available through the application directly.

**Comment by deathbaba** [comment]
We'll do it in the future. Frequent map updates are essential for every OSM-based app. Thanks for your concern.
