### ISSUE TITLE
Rendering long Persian names

### ISSUE THREAD

**Issue by Mesgary** [mapsme/omim#960]
Rendering long Persian names which is longer than a line, divided to two line incorrectly. For example the "مرکز تربیت معلم نسیبه" should be split to "مرکز تربیت معلم" (first 3 words) and "نسیبه" (last word), while as you see in attached screenshot, it is split in "تربیت معلم نسیبه" (last 3 words) in first line and "مرکز" (first word) in second line.
You can find it under English name "Nasibeh Training Teacher University" with ID=25624946.
![photo_2015-12-12_22-21-19](https://cloud.githubusercontent.com/assets/15173479/11763442/fc0d22b8-a11f-11e5-9363-fffb6ca5a75d.jpg)

**Comment by Mesgary** [comment]
Just as a reminder, in RTL languages like Persian, words read and count from the Right to the Left ;)

**Comment by deathbaba** [comment]
Thanks! Have you checked it on a fresh master branch? Or only in the app store version?

**Comment by Mesgary** [comment]
Sorry. I submitted it wrong. It was for another application. I close it.
