### ISSUE TITLE
Save route when app is closed

### ISSUE THREAD

**Issue by utack** [mapsme/omim#962]
Currently when the app is closed manually or due to ram shortness the route is deleted.
Maybe it could be saved fully or at least ask if it should be calculated again.

**Comment by deathbaba** [comment]
Route should be saved if you move app into a background. If it doesn’t, it’s a bug.

**Comment by utack** [comment]
When moving the app to background the route is indeed saved
When closing the app from the "recent apps" menu or when it is closed when the ram runs out, it is not saved.
Tested on 2015.12.12 daily build

**Comment by deathbaba** [comment]
How do you simulate "RAM runs out" scenario without moving the app into a background?

**Comment by utack** [comment]
Move app to background from app switcher
Open app again
Route is still there and navigation running


Move app to background from app switcher
Open all sorts of other apps, maps.me app is forced to close thereby
Open app again
Route is gone and navigation stopped

**Comment by deathbaba** [comment]
Which app switcher do you use? Is it a very common case?

**Comment by utack** [comment]
The stock android app overview.
It can be reproduced, but under normal conditions it is not a problem, because the app stays open for navigation.

**Comment by rokuz** [comment]
Must be fixed, please, open new issue if you can reproduce it
