### ISSUE TITLE
unable to make map edits

### ISSUE THREAD

**Issue by richlv** [mapsme/omim#9653]
Latest maps.me on iOS.
For a while now, unable to edit any objects - the edit control is missing completely.

Possibly related - I have several maps, and some are not up to date. The one where I am attempting to make edits is completely updated.

**Comment by vitalyzhakov** [comment]
Hello!

I have the same bug in latest version in Android on two different phones (Android 6.0.1, Android 7.1.2).
It's reproducing for 3 days.

**Comment by vitalyzhakov** [comment]
Hello!
Yesterday's evening I went to maps.me page on Play Market.
I saw update button for application.

After updating application, I've updated all maps. After that bug has not reproducing for me.

PS. As soon as the problem appeared, I have visited maps.me page on play market and there was no updates.

**Comment by richlv** [comment]
Thank you for the info. I've checked multiple times, and no updates for maps.me are available.
I do not want to update all of the maps, keeping several because I visited those places and maps.me tells me that deleting them will remove my edits - still hoping maps.me will add a way to see what those non-uploaded changes are...

**Comment by richlv** [comment]
An update became available shortly after I made the previous comment, and applying it resolved the inability to edit - looks like it indeed was some longer delay in updates :)

Closing.
